import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const file=path.resolve(dir,'..','..','.dist','firebase','index.html');
if(!fs.existsSync(file))throw new Error('LEVEL UP home missing');
let h=fs.readFileSync(file,'utf8');
const hero=`<section class="hero lu-home-hero"><div><div class="hero-kicker">HITOBITO LEVEL UP</div><h1>今の自分に、<br><span>ひとつだけ。</span></h1><p class="hero-copy">今の悩みに合う練習を選んで、すぐ始める。短いゲームで判断と行動を反復します。</p><div class="lu-home-actions"><a class="primary" href="#levelup-state-diagnosis-v3">30秒で選ぶ ↓</a><a href="#training-games">一覧から探す</a></div></div><aside><small>HOW TO USE</small><b>悩みを選ぶ。</b><b>1本やる。</b><b>日常で使う。</b></aside></section>`;
if(!/<section class="hero">[\s\S]*?<\/section>/.test(h))throw new Error('hero missing');
h=h.replace(/<section class="hero">[\s\S]*?<\/section>/,hero).replace('<h2>Training Games</h2>','<h2>すべてのトレーニング</h2>');
const d=h.match(/<section class="lu-v3" id="levelup-state-diagnosis-v3">[\s\S]*?<\/section>/)?.[0];
const s='<section class="levelup-search" id="levelup-search"';
if(!d||!h.includes(s))throw new Error('diagnosis/search missing');
h=h.replace(d,'').replace(s,d+'\n'+s);
if(!h.includes('id="lu-home-redesign-v1"')){
const css=`<style id="lu-home-redesign-v1">
body{background:radial-gradient(circle at 76% -16%,rgba(216,255,91,.055),transparent 28%),linear-gradient(180deg,#0b0d0b,#070907)!important}body:before{opacity:.1!important}.shell{width:min(1100px,calc(100% - 34px))!important}.top{min-height:62px!important;padding:10px 0 12px!important;border-bottom:1px solid rgba(255,255,255,.07)!important;background:transparent!important;backdrop-filter:none!important}.brand{font-size:11px!important;letter-spacing:.2em!important;color:#d9ddd4!important}
.lu-home-hero{padding:60px 0 42px!important;display:grid!important;grid-template-columns:minmax(0,1fr) 200px!important;gap:50px!important;align-items:end!important}.lu-home-hero .hero-kicker{margin:0 0 17px!important;color:#8f9689!important;font-size:10px!important;letter-spacing:.2em!important}.lu-home-hero h1{margin:0!important;font-family:"Hiragino Mincho ProN","Yu Mincho",serif!important;font-size:clamp(48px,7.4vw,84px)!important;line-height:1.04!important;letter-spacing:-.055em!important;font-weight:700!important;text-shadow:none!important}.lu-home-hero h1 span{color:#d8ff5b!important}.lu-home-hero .hero-copy{display:block!important;margin:22px 0 0!important;max-width:650px!important;color:#a7ada2!important;font-size:14px!important;line-height:1.8!important}.lu-home-actions{display:flex;gap:10px;margin-top:26px}.lu-home-actions a{display:flex;align-items:center;justify-content:center;min-height:47px;padding:0 18px;border:1px solid rgba(255,255,255,.13);border-radius:999px;color:#d8ddd2;font-size:12px;font-weight:850}.lu-home-actions .primary{background:#d8ff5b;color:#11160d;border-color:#d8ff5b}.lu-home-hero aside{display:grid;gap:8px;padding:18px 0 3px 19px;border-left:1px solid rgba(255,255,255,.12)}.lu-home-hero aside small{margin-bottom:5px;color:#6f756d;font-size:8px;letter-spacing:.18em}.lu-home-hero aside b{font-family:"Hiragino Mincho ProN","Yu Mincho",serif;color:#d8dcd4;font-size:16px;font-weight:600}
.lu-v3{margin:0 0 18px!important;padding:27px!important;border:0!important;border-radius:27px!important;background:linear-gradient(145deg,#f2efe7,#e9e5da)!important;color:#171914!important;box-shadow:0 20px 60px rgba(0,0,0,.24)!important}.lu-v3-kicker{color:#72776c!important}.lu-v3 h2{color:#171914!important;font-family:"Hiragino Mincho ProN","Yu Mincho",serif!important;font-size:clamp(34px,5vw,52px)!important;line-height:1.08!important;font-weight:700!important}.lu-v3-lead{margin:11px 0 18px!important;color:#5f635b!important;font-size:12px!important}.lu-v3-problems{gap:9px!important}.lu-v3-problem{min-height:64px!important;padding:13px 15px!important;border:1px solid rgba(23,25,20,.11)!important;border-radius:16px!important;background:rgba(255,255,255,.58)!important;color:#23261f!important;font-size:13px!important}.lu-v3-problem b{color:#48622d!important}
.levelup-search{grid-template-columns:210px 1fr!important;gap:16px!important;align-items:center!important;margin:0 0 32px!important;padding:13px 15px!important;border:1px solid rgba(255,255,255,.08)!important;border-radius:17px!important;background:rgba(255,255,255,.025)!important;box-shadow:none!important}.levelup-search-copy{display:block!important}.levelup-search-kicker,.levelup-search p{display:none!important}.levelup-search h2{margin:0!important;color:#cfd4ca!important;font-size:13px!important}.levelup-search-box{min-height:48px!important;background:#0c0f0c!important}.section-head{margin:36px 0 14px!important}.section-head h2,.section-head strong{font-size:13px!important;letter-spacing:.04em!important;text-transform:none!important}.grid{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:16px!important}.catalog-divider{margin:14px 0 2px!important;border-bottom:1px solid rgba(255,255,255,.07)!important}.premium-book-card,.premium-book-card.title-xlong,.premium-book-card .card-link,.premium-book-card.title-xlong .card-link{min-height:310px!important}.premium-book-card .card-link{padding:26px 22px 20px 24px!important}.premium-book-card .icon{display:none!important}.premium-book-card h2,.premium-book-card.title-long h2,.premium-book-card.title-xlong h2{margin:38px 2px 23px!important;font-size:clamp(22px,2vw,28px)!important;line-height:1.43!important;overflow:visible!important}.premium-book-card.title-xlong h2{font-size:clamp(20px,1.7vw,24px)!important}.premium-book-card .book-obi{padding:13px 14px!important;background:rgba(7,9,7,.48)!important;border:1px solid rgba(255,255,255,.075)!important;border-left:2px solid color-mix(in srgb,var(--cover-accent) 62%,white 4%)!important;color:#d8ded0!important;font-size:12.5px!important;line-height:1.65!important;box-shadow:none!important}
@media(max-width:900px){.lu-home-hero{grid-template-columns:1fr 170px!important;gap:32px!important}.grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:650px){.shell{width:min(100% - 20px,1100px)!important}.lu-home-hero{display:block!important;padding:34px 2px 29px!important}.lu-home-hero h1{font-size:clamp(40px,12vw,58px)!important}.lu-home-hero .hero-copy{margin-top:16px!important;font-size:13px!important}.lu-home-hero aside{display:none!important}.lu-home-actions{margin-top:20px}.lu-v3{padding:20px 16px!important;border-radius:21px!important}.lu-v3 h2{font-size:37px!important}.lu-v3-problems{grid-template-columns:1fr!important}.lu-v3-problem{min-height:58px!important;font-size:12.5px!important}.levelup-search{grid-template-columns:1fr!important;gap:8px!important;padding:11px!important}.levelup-search h2{font-size:12px!important}.grid{grid-template-columns:1fr!important;gap:12px!important}.premium-book-card,.premium-book-card.title-long,.premium-book-card.title-xlong,.premium-book-card .card-link,.premium-book-card.title-long .card-link,.premium-book-card.title-xlong .card-link{min-height:268px!important}.premium-book-card h2,.premium-book-card.title-long h2,.premium-book-card.title-xlong h2{font-size:24px!important}.premium-book-card .book-obi{font-size:13px!important}}
</style>`;h=h.replace('</head>',css+'\n</head>')}
fs.writeFileSync(file,h);
const out=fs.readFileSync(file,'utf8');
for(const x of ['id="lu-home-redesign-v1"','今の自分に、','30秒で選ぶ','すべてのトレーニング','.premium-book-card .icon{display:none!important}'])if(!out.includes(x))throw new Error('redesign missing '+x);
if(!(out.indexOf('lu-home-hero')<out.indexOf('id="levelup-state-diagnosis-v3"')&&out.indexOf('id="levelup-state-diagnosis-v3"')<out.indexOf('id="levelup-search"')))throw new Error('home order invalid');
console.log('[Firebase] LEVEL UP home redesign injected.');