const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={age:40,end:90,hours:{sleep:7,work:8,phone:3,move:1,chores:1}};
const items=[['sleep','睡眠'],['work','仕事・勉強'],['phone','スマホ・動画'],['move','移動'],['chores','家事・身支度']];
const fmt=new Intl.NumberFormat('ja-JP',{maximumFractionDigits:1});
function yearsLeft(){return Math.max(0,state.end-state.age)}
function used(){return Object.values(state.hours).reduce((a,b)=>a+b,0)}
function free(){return Math.max(0,24-used())}
function lifeYears(h){return yearsLeft()*h/24}
function ym(v){const y=Math.floor(v),m=Math.round((v-y)*12);return m===12?`${y+1}年0か月`:`${y}年${m}か月`}
function renderSliders(){const box=$('#sliders');box.innerHTML='';for(const [key,label] of items){const row=document.createElement('div');row.className='sliderRow';row.innerHTML=`<div class="sliderHead"><span>${label}</span><strong><b>${state.hours[key]}</b><small>時間/日</small></strong></div><input type="range" min="0" max="14" step="0.5" value="${state.hours[key]}" data-key="${key}" aria-label="${label}の1日平均時間">`;box.appendChild(row)}$$('#sliders input').forEach(el=>el.addEventListener('input',e=>{state.hours[e.target.dataset.key]=+e.target.value;render()}))}
function render(){if(state.age>=state.end){state.end=state.age<90?90:100;$$('.endAge button').forEach(b=>b.classList.toggle('active',+b.dataset.end===state.end))}$('#ageValue').textContent=state.age;const f=free(),fy=lifeYears(f),y=Math.floor(fy),m=Math.round((fy-y)*12);$('#freeYears').textContent=m===12?y+1:y;$('#freeMonths').textContent=m===12?0:m;$('#freePercent').textContent=Math.round(f/24*100);$('#cardFree').textContent=ym(fy);$('#warning').hidden=used()<=24;const bar=$('#lifeBar');bar.innerHTML='';const rows=$('#rows');rows.innerHTML='';const card=$('#cardBreakdown');card.innerHTML='';for(const [key,label] of items){const h=state.hours[key],v=lifeYears(h);const seg=document.createElement('i');seg.style.width=`${h/24*100}%`;bar.appendChild(seg);rows.insertAdjacentHTML('beforeend',`<div class="lifeRow"><span>${label}<small>${h}時間/日</small></span><strong>${ym(v)}</strong></div>`);card.insertAdjacentHTML('beforeend',`<div class="cardLine"><span>${label}</span><b>${ym(v)}</b></div>`)}const seg=document.createElement('i');seg.className='free';seg.style.width=`${f/24*100}%`;bar.appendChild(seg);rows.insertAdjacentHTML('beforeend',`<div class="lifeRow"><span>自由時間<small>${fmt.format(f)}時間/日</small></span><strong>${ym(fy)}</strong></div>`);card.insertAdjacentHTML('beforeend',`<div class="cardLine"><span>自由時間</span><b>${ym(fy)}</b></div>`)}
function shareText(){const parts=items.map(([k,l])=>`${l} ${ym(lifeYears(state.hours[k]))}`).join('\n');return`あなたの人生、何に消えてる？\n${state.age}歳→${state.end}歳までと仮定\n\n${parts}\n自由時間 ${ym(lifeYears(free()))}\n\nhttps://levelup.hitobito.jp/apps/jinsei-kieteru/`}
function blob(canvas){return new Promise(r=>canvas.toBlob(r,'image/png',.95))}
async function shareFile(){const c=$('#shareCanvas'),x=c.getContext('2d');x.fillStyle='#c9ff45';x.fillRect(0,0,1080,1350);x.fillStyle='#151713';x.font='900 52px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';x.fillText('あなたの人生、何に消えてる？',70,105);x.font='700 25px sans-serif';x.fillStyle='#4e573b';x.fillText(`${state.age}歳 → ${state.end}歳までと仮定`,70,155);x.fillStyle='#151713';x.font='850 30px sans-serif';x.fillText('自由に残る人生',70,290);x.font='950 94px sans-serif';x.fillText(ym(lifeYears(free())),70,395);let yy=550;x.font='800 25px sans-serif';for(const [k,l] of items){x.fillText(l,70,yy);x.textAlign='right';x.fillText(ym(lifeYears(state.hours[k])),1010,yy);x.textAlign='left';yy+=92}x.font='900 28px sans-serif';x.fillText('LEVEL UP',70,1230);x.font='700 21px sans-serif';x.fillText('levelup.hitobito.jp',70,1270);return new File([await blob(c)],'jinsei-kieteru.png',{type:'image/png'})}
async function share(){const st=$('#status');st.textContent='';try{const file=await shareFile();if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({title:'あなたの人生、何に消えてる？',text:'人生の時間配分を可視化しました。',url:'https://levelup.hitobito.jp/apps/jinsei-kieteru/',files:[file]});return}if(navigator.share){await navigator.share({title:'あなたの人生、何に消えてる？',text:shareText(),url:'https://levelup.hitobito.jp/apps/jinsei-kieteru/'});return}await navigator.clipboard.writeText(shareText());st.textContent='結果をコピーしました'}catch(e){if(e?.name!=='AbortError')st.textContent='シェアできませんでした'}}
$('#ageRange').addEventListener('input',e=>{state.age=+e.target.value;render()});$$('.endAge button').forEach(b=>b.addEventListener('click',()=>{state.end=+b.dataset.end;$$('.endAge button').forEach(x=>x.classList.toggle('active',x===b));render()}));$('#shareBtn').addEventListener('click',share);$('#copyBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(shareText());$('#status').textContent='結果をコピーしました'});$('#resetBtn').addEventListener('click',()=>{state.age=40;state.end=90;state.hours={sleep:7,work:8,phone:3,move:1,chores:1};$('#ageRange').value=40;$$('.endAge button').forEach(b=>b.classList.toggle('active',+b.dataset.end===90));renderSliders();render();scrollTo({top:0,behavior:'smooth'})});renderSliders();render();