(() => {
  'use strict';
  const STORAGE_KEY='levelup:habit-raid:v1';
  const EMOJIS=['📚','🏃','💧','🧘','🧹','✍️','💪','🌱','🧠','🎸','🛏️','🥗'];
  const BOSSES=[['先延ばしスライム','👾'],['だるさゴーレム','🗿'],['三日坊主ドラゴン','🐉'],['誘惑ミミック','🧰'],['めんどくさ大王','👹']];
  const COMPANIONS=[
    {id:'sprout',name:'はじまりスプラウト',emoji:'🌱',rarity:'N'},{id:'drop',name:'みずタマ',emoji:'💧',rarity:'N'},{id:'book',name:'ページン',emoji:'📘',rarity:'N'},
    {id:'fox',name:'コツコツギツネ',emoji:'🦊',rarity:'R'},{id:'owl',name:'集中フクロウ',emoji:'🦉',rarity:'R'},{id:'bolt',name:'即行ボルト',emoji:'⚡',rarity:'R'},
    {id:'moon',name:'継続ムーン',emoji:'🌙',rarity:'SR'},{id:'phoenix',name:'復帰フェニックス',emoji:'🔥',rarity:'SR'},{id:'dragon',name:'習慣ドラゴン',emoji:'🐲',rarity:'SSR'}
  ];
  const XP_BASE=100,$=id=>document.getElementById(id);
  const els={level:$('levelValue'),streak:$('streakValue'),coins:$('coinValue'),xpBar:$('xpBar'),xpText:$('xpText'),bossCard:$('bossCard'),bossName:$('bossName'),bossArt:$('bossArt'),bossHpText:$('bossHpText'),bossHpBar:$('bossHpBar'),bossHint:$('bossHint'),comboRow:$('comboRow'),feverLabel:$('feverLabel'),missions:$('missions'),todayLabel:$('todayLabel'),habitList:$('habitList'),emptyState:$('emptyState'),addHabitBtn:$('addHabitBtn'),emptyAddBtn:$('emptyAddBtn'),statsView:$('statsView'),collectionView:$('collectionView'),statsSummary:$('statsSummary'),weekBars:$('weekBars'),statsList:$('statsList'),collectionGrid:$('collectionGrid'),habitDialog:$('habitDialog'),habitForm:$('habitForm'),habitDialogTitle:$('habitDialogTitle'),habitName:$('habitName'),habitGroup:$('habitGroup'),habitMinutes:$('habitMinutes'),emojiPicker:$('emojiPicker'),deleteHabitBtn:$('deleteHabitBtn'),closeHabitDialog:$('closeHabitDialog'),rewardDialog:$('rewardDialog'),rewardEyebrow:$('rewardEyebrow'),rewardIcon:$('rewardIcon'),rewardTitle:$('rewardTitle'),rewardText:$('rewardText'),rewardBtn:$('rewardBtn'),toast:$('toast'),damagePop:$('damagePop'),soundBtn:$('soundBtn')};
  const uid=()=>crypto.randomUUID?crypto.randomUUID():`h${Date.now()}${Math.random().toString(16).slice(2)}`;
  const defaultData=()=>({habits:[{id:uid(),name:'読書',group:'学習',minutes:10,emoji:'📚',createdAt:Date.now()},{id:uid(),name:'ストレッチ',group:'健康',minutes:0,emoji:'🧘',createdAt:Date.now()+1}],logs:{},timers:{},player:{level:1,xp:0,coins:0,bossKills:0,collection:['sprout'],pity:0},boss:null,missionClaims:{},sound:true});
  let data=load(),editingId=null,selectedEmoji=EMOJIS[0],toastTimer=null,rewardAction=null,audioCtx=null;
  function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  const today=()=>dateKey(),xpNeed=(l=data.player.level)=>XP_BASE+(l-1)*35,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),safeNumber=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
  function load(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!p)return defaultData();const b=defaultData();return {...b,...p,habits:Array.isArray(p.habits)?p.habits:b.habits,logs:p.logs&&typeof p.logs==='object'?p.logs:{},timers:p.timers&&typeof p.timers==='object'?p.timers:{},player:{...b.player,...(p.player||{}),collection:Array.isArray(p.player?.collection)?p.player.collection:b.player.collection},missionClaims:p.missionClaims&&typeof p.missionClaims==='object'?p.missionClaims:{}}}catch{return defaultData()}}
  const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(data));
  function formatDuration(sec){if(sec<60)return `${Math.max(1,Math.round(sec))}秒`;const m=Math.floor(sec/60),s=Math.floor(sec%60);return s?`${m}分${s}秒`:`${m}分`}
  function getDayLog(k=today()){if(!data.logs[k])data.logs[k]={};return data.logs[k]}
  function getEntry(id,k=today()){const e=data.logs[k]?.[id];return e&&typeof e==='object'?{count:safeNumber(e.count),seconds:safeNumber(e.seconds)}:{count:0,seconds:0}}
  const setEntry=(id,k,e)=>{getDayLog(k)[id]=e};
  function lastDates(n=7){return Array.from({length:n},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(n-1-i));return d})}
  const totalForDay=k=>Object.values(data.logs[k]||{}).reduce((a,e)=>a+safeNumber(e.count),0),secondsForDay=k=>Object.values(data.logs[k]||{}).reduce((a,e)=>a+safeNumber(e.seconds),0);
  function streak(){let c=0,d=new Date();d.setHours(12,0,0,0);if(totalForDay(dateKey(d))===0)d.setDate(d.getDate()-1);while(totalForDay(dateKey(d))>0&&c<3650){c++;d.setDate(d.getDate()-1)}return c}
  const completionsToday=()=>totalForDay(today()),secondsToday=()=>secondsForDay(today()),uniqueHabitsToday=()=>Object.values(data.logs[today()]||{}).filter(e=>safeNumber(e.count)>0).length;
  const bossMaxHp=()=>60+Math.min(140,(data.player.level-1)*8)+(data.player.bossKills%5)*10;
  function ensureBoss(){if(!data.boss||data.boss.day!==today()){const i=(new Date().getDate()+data.player.bossKills)%BOSSES.length,m=bossMaxHp();data.boss={day:today(),index:i,hp:m,maxHp:m,chain:0};save()}}
  const currentBoss=()=>{ensureBoss();return data.boss};
  function bossDamage(){const combo=currentBoss().chain%3,crit=Math.random()<.14;return {value:(12+Math.floor(Math.random()*7)+combo*3)*(crit?2:1),crit}}
  function playTone(type='hit'){if(!data.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime,cfg=type==='level'?[520,820,.18]:type==='chest'?[380,650,.16]:type==='ko'?[180,520,.22]:[210,140,.08];o.connect(g);g.connect(audioCtx.destination);o.frequency.setValueAtTime(cfg[0],now);o.frequency.exponentialRampToValueAtTime(cfg[1],now+cfg[2]);g.gain.setValueAtTime(.07,now);g.gain.exponentialRampToValueAtTime(.001,now+cfg[2]);o.start();o.stop(now+cfg[2])}catch{}if(navigator.vibrate)navigator.vibrate(type==='ko'?[35,35,55]:18)}
  function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),1700)}
  function damagePop(v,crit){els.damagePop.textContent=`${crit?'CRIT! ':''}-${v}`;els.damagePop.classList.remove('show');void els.damagePop.offsetWidth;els.damagePop.classList.add('show')}
  function addXp(a){data.player.xp+=a;let levels=0;while(data.player.xp>=xpNeed()){data.player.xp-=xpNeed();data.player.level++;levels++}if(levels){rewardAction=()=>openChest('LEVEL UP BONUS');showReward('LEVEL UP!','⚡',`Lv.${data.player.level} になった。宝箱を1個ゲット！`,'宝箱を開ける');playTone('level')}}
  const addCoins=n=>data.player.coins+=n;
  function completeHabit(id,seconds=0){const h=data.habits.find(x=>x.id===id);if(!h)return;const prev=getEntry(id);setEntry(id,today(),{count:prev.count+1,seconds:prev.seconds+Math.max(0,seconds)});delete data.timers[id];const b=currentBoss();b.chain++;const dmg=bossDamage();b.hp=Math.max(0,b.hp-dmg.value);const fever=b.chain%3===0;addXp(fever?32:20);addCoins(fever?22:12);save();els.bossCard.classList.remove('hit');void els.bossCard.offsetWidth;els.bossCard.classList.add('hit');damagePop(dmg.value,dmg.crit);playTone('hit');toast(`${h.emoji} ${h.name} 完了！ +${fever?32:20}XP${fever?' FEVER!':''}`);if(b.hp<=0){els.bossCard.classList.add('ko');playTone('ko');data.player.bossKills++;addCoins(70);addXp(55);const idx=(b.index+1)%BOSSES.length,max=bossMaxHp();setTimeout(()=>{data.boss={day:today(),index:idx,hp:max,maxHp:max,chain:b.chain};save();els.bossCard.classList.remove('ko');render();rewardAction=()=>openChest('BOSS DROP');showReward('BOSS DOWN!','🎁','ボス撃破！ +70🪙 +55XP。宝箱を落とした。','宝箱を開ける')},620)}render()}
  function showReward(eyebrow,icon,text,button='受け取る'){els.rewardEyebrow.textContent=eyebrow;els.rewardIcon.textContent=icon;els.rewardTitle.textContent=eyebrow==='LEVEL UP!'?'レベルアップ！':eyebrow==='BOSS DOWN!'?'ボス撃破！':'仲間が増えた！';els.rewardText.textContent=text;els.rewardBtn.textContent=button;if(!els.rewardDialog.open)els.rewardDialog.showModal()}
  function rollCompanion(){data.player.pity=safeNumber(data.player.pity);let r=Math.random(),pool;if(data.player.pity>=7){pool=COMPANIONS.filter(c=>['SR','SSR'].includes(c.rarity));data.player.pity=0}else if(r<.04){pool=COMPANIONS.filter(c=>c.rarity==='SSR');data.player.pity=0}else if(r<.18){pool=COMPANIONS.filter(c=>c.rarity==='SR');data.player.pity=0}else if(r<.47){pool=COMPANIONS.filter(c=>c.rarity==='R');data.player.pity++}else{pool=COMPANIONS.filter(c=>c.rarity==='N');data.player.pity++}return pool[Math.floor(Math.random()*pool.length)]}
  function openChest(source='CHEST'){const c=rollCompanion(),isNew=!data.player.collection.includes(c.id);if(isNew)data.player.collection.push(c.id);else addCoins(c.rarity==='N'?15:c.rarity==='R'?25:c.rarity==='SR'?45:80);save();render();rewardAction=null;showReward(source,c.emoji,`${c.name}　${isNew?`${c.rarity} 仲間を獲得！`:'ダブり → コインに変換！'}`,'OK');playTone('chest')}
  function awardMission(key){const ck=`${today()}:${key}`;if(data.missionClaims[ck])return;data.missionClaims[ck]=true;addCoins(30);addXp(25);save();render();toast('ミッション報酬 +30🪙 +25XP');playTone('chest')}
  const isMissionClaimed=k=>!!data.missionClaims[`${today()}:${k}`];
  function render(){ensureBoss();renderPlayer();renderBoss();renderMissions();renderHabits();renderStats();renderCollection();save()}
  function renderPlayer(){els.level.textContent=data.player.level;els.streak.textContent=`🔥 ${streak()}日`;els.coins.textContent=`🪙 ${data.player.coins}`;const n=xpNeed();els.xpBar.style.width=`${clamp(data.player.xp/n*100,0,100)}%`;els.xpText.textContent=`${data.player.xp} / ${n} XP`}
  function renderBoss(){const b=currentBoss(),info=BOSSES[b.index%BOSSES.length];els.bossName.textContent=info[0];els.bossArt.textContent=info[1];els.bossHpText.textContent=`${b.hp} / ${b.maxHp}`;els.bossHpBar.style.width=`${clamp(b.hp/b.maxHp*100,0,100)}%`;const combo=b.chain%3;[...els.comboRow.querySelectorAll('i')].forEach((i,n)=>i.classList.toggle('on',n<combo));els.comboRow.classList.toggle('fever',combo===0&&b.chain>0);els.feverLabel.textContent=combo===0&&b.chain>0?'FEVER!':`あと${3-combo}回`;els.bossHint.textContent=combo===2?'次の完了でFEVER報酬！':'習慣を1回完了すると攻撃。3連続でFEVER。'}
  function renderMissions(){const ms=[{key:'three',icon:'⚔️',name:'習慣を3回クリア',value:completionsToday(),goal:3,label:`${Math.min(completionsToday(),3)}/3`},{key:'variety',icon:'🧩',name:'2種類の習慣をやる',value:uniqueHabitsToday(),goal:2,label:`${Math.min(uniqueHabitsToday(),2)}/2`},{key:'tenmin',icon:'⏱️',name:'合計10分取り組む',value:secondsToday(),goal:600,label:`${Math.min(Math.floor(secondsToday()/60),10)}/10分`}];els.missions.innerHTML='';for(const m of ms){const ready=m.value>=m.goal,claimed=isMissionClaimed(m.key),row=document.createElement('div');row.className=`mission ${claimed?'done':''}`;row.innerHTML=`<div class="mission-icon">${m.icon}</div><div><strong>${escapeHtml(m.name)}</strong><small>${m.label} ・ 報酬 30🪙 + 25XP</small></div><button class="claim" type="button" ${!ready||claimed?'disabled':''}>${claimed?'GET':'受取'}</button>`;row.querySelector('button').addEventListener('click',()=>awardMission(m.key));els.missions.appendChild(row)}const d=new Date();els.todayLabel.textContent=`${d.getMonth()+1}/${d.getDate()}`}
  function renderHabits(){els.habitList.innerHTML='';els.emptyState.hidden=data.habits.length>0;const dates=lastDates();for(const h of data.habits){const t=data.timers[h.id],e=getEntry(h.id),card=document.createElement('article'),elapsed=timerElapsed(h.id),timeLabel=t?(t.paused?`▶ 再開 ${formatDuration(elapsed)}`:`⏸ ${formatDuration(elapsed)}`):(h.minutes>0?`⏱ ${h.minutes}分`:'⏱ 計る');card.className=`habit-card ${t?'active':''}`;card.innerHTML=`<div class="habit-top"><div class="habit-icon">${h.emoji||'⭐'}</div><div class="habit-copy"><strong>${escapeHtml(h.name)}</strong><div class="habit-meta">${h.group?`<span class="group-tag">${escapeHtml(h.group)}</span>`:''}<span>今日 ${e.count}回${e.seconds?` ・ ${formatDuration(e.seconds)}`:''}</span></div></div><button class="edit-habit" type="button" aria-label="${escapeHtml(h.name)}を編集">•••</button></div><div class="habit-actions"><button class="done-btn" type="button">✓ できた！</button><button class="timer-btn ${t?(t.paused?'paused':'running'):''}" type="button">${timeLabel}</button></div>${t?`<div class="timer-row"><button type="button" data-action="finish">■ タイマー完了</button><button type="button" data-action="cancel">× 取消</button></div>`:''}<div class="week-dots">${dates.map(d=>`<i class="${getEntry(h.id,dateKey(d)).count>0?'done':''}"></i>`).join('')}<span>過去7日</span></div>`;card.querySelector('.done-btn').addEventListener('click',()=>completeHabit(h.id));card.querySelector('.edit-habit').addEventListener('click',()=>openHabitDialog(h.id));card.querySelector('.timer-btn').addEventListener('click',()=>toggleTimer(h.id));card.querySelector('[data-action="finish"]')?.addEventListener('click',()=>finishTimer(h.id));card.querySelector('[data-action="cancel"]')?.addEventListener('click',()=>{delete data.timers[h.id];save();render();toast('タイマーを取り消した')});els.habitList.appendChild(card)}}
  function timerElapsed(id){const t=data.timers[id];if(!t)return 0;return safeNumber(t.accumulated)+(t.paused?0:Math.max(0,(Date.now()-t.startedAt)/1000))}
  function toggleTimer(id){const t=data.timers[id];if(!t){data.timers[id]={startedAt:Date.now(),accumulated:0,paused:false};toast('タイマー開始')}else if(t.paused){t.startedAt=Date.now();t.paused=false;toast('再開')}else{t.accumulated=timerElapsed(id);t.paused=true;toast('一時停止')}save();render()}
  function finishTimer(id){const sec=timerElapsed(id);if(sec<1){toast('1秒以上やってから完了しよう');return}completeHabit(id,Math.round(sec))}
  function renderStats(){const dates=lastDates(),total=dates.reduce((a,d)=>a+totalForDay(dateKey(d)),0),sec=dates.reduce((a,d)=>a+secondsForDay(dateKey(d)),0),max=Math.max(1,...dates.map(d=>totalForDay(dateKey(d))));els.statsSummary.innerHTML=`<div class="stat-tile"><strong>${total}</strong><small>7日クリア</small></div><div class="stat-tile"><strong>${Math.round(sec/60)}</strong><small>取り組み分</small></div><div class="stat-tile"><strong>${streak()}</strong><small>連続日</small></div>`;els.weekBars.innerHTML=dates.map(d=>{const c=totalForDay(dateKey(d));return `<div class="day-bar"><i style="height:${Math.max(3,c/max*110)}px"></i><span>${['日','月','火','水','木','金','土'][d.getDay()]}</span></div>`}).join('');els.statsList.innerHTML='';for(const h of data.habits){const c=dates.reduce((a,d)=>a+getEntry(h.id,dateKey(d)).count,0),s=dates.reduce((a,d)=>a+getEntry(h.id,dateKey(d)).seconds,0),row=document.createElement('div');row.className='stat-habit';row.innerHTML=`<strong>${h.emoji} ${escapeHtml(h.name)}</strong><span>${c}回${s?` ・ ${formatDuration(s)}`:''}</span>`;els.statsList.appendChild(row)}}
  function renderCollection(){els.collectionGrid.innerHTML='';for(const c of COMPANIONS){const owned=data.player.collection.includes(c.id),el=document.createElement('div'),cls=c.rarity==='R'?'rare':c.rarity==='SR'?'epic':c.rarity==='SSR'?'legend':'';el.className=`companion ${cls} ${owned?'':'locked'}`;el.innerHTML=`<span class="emoji">${owned?c.emoji:'❔'}</span><strong>${owned?escapeHtml(c.name):'???'}</strong><small>${c.rarity}</small>`;els.collectionGrid.appendChild(el)}}
  function openHabitDialog(id=null){editingId=id;const h=data.habits.find(x=>x.id===id);els.habitDialogTitle.textContent=h?'習慣を編集':'習慣を追加';els.habitName.value=h?.name||'';els.habitGroup.value=h?.group||'';els.habitMinutes.value=h?.minutes??0;selectedEmoji=h?.emoji||EMOJIS[0];els.deleteHabitBtn.hidden=!h;renderEmojiPicker();els.habitDialog.showModal();setTimeout(()=>els.habitName.focus(),120)}
  function renderEmojiPicker(){els.emojiPicker.innerHTML='';EMOJIS.forEach(e=>{const b=document.createElement('button');b.type='button';b.textContent=e;b.className=e===selectedEmoji?'active':'';b.addEventListener('click',()=>{selectedEmoji=e;renderEmojiPicker()});els.emojiPicker.appendChild(b)})}
  function saveHabit(ev){ev.preventDefault();const name=els.habitName.value.trim();if(!name)return;const group=els.habitGroup.value.trim(),minutes=clamp(Math.round(safeNumber(els.habitMinutes.value)),0,600);if(editingId){const h=data.habits.find(x=>x.id===editingId);if(h)Object.assign(h,{name,group,minutes,emoji:selectedEmoji})}else data.habits.push({id:uid(),name,group,minutes,emoji:selectedEmoji,createdAt:Date.now()});save();els.habitDialog.close();render();toast(editingId?'習慣を更新した':'新しいクエストを追加！')}
  function deleteHabit(){if(!editingId)return;const h=data.habits.find(x=>x.id===editingId);if(!h||!confirm(`「${h.name}」を削除しますか？過去の記録は残ります。`))return;data.habits=data.habits.filter(x=>x.id!==editingId);delete data.timers[editingId];save();els.habitDialog.close();render();toast('習慣を削除した')}
  function escapeHtml(s){return String(s).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[ch]))}
  function switchView(v){els.statsView.hidden=v!=='stats';els.collectionView.hidden=v!=='collection';document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='stats')renderStats();if(v==='collection')renderCollection()}
  els.addHabitBtn.addEventListener('click',()=>openHabitDialog());els.emptyAddBtn.addEventListener('click',()=>openHabitDialog());els.habitForm.addEventListener('submit',saveHabit);els.closeHabitDialog.addEventListener('click',()=>els.habitDialog.close());els.deleteHabitBtn.addEventListener('click',deleteHabit);els.rewardBtn.addEventListener('click',()=>{if(rewardAction){const fn=rewardAction;rewardAction=null;els.rewardDialog.close();fn()}else els.rewardDialog.close()});els.soundBtn.addEventListener('click',()=>{data.sound=!data.sound;els.soundBtn.textContent=data.sound?'♪':'×';els.soundBtn.setAttribute('aria-pressed',String(data.sound));save();toast(data.sound?'効果音 ON':'効果音 OFF')});document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('[data-close-view]').forEach(b=>b.addEventListener('click',()=>switchView('home')));
  setInterval(()=>{if(Object.keys(data.timers).some(id=>!data.timers[id].paused))renderHabits()},1000);render();
})();
