(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-arigatou-real-v1';
  const cats={person:['人','👤'],system:['仕組み','⚙️'],tool:['道具','🧰'],energy:['エネルギー','⚡'],nature:['自然','🌿'],history:['蓄積','📚']};
  let modal,currentCat='person',found=[];
  function ensureLauncher(){const replay=$('#replayButton');if(!replay||$('[data-real-thanks-launch]'))return;const b=document.createElement('button');b.type='button';b.className='primary-button real-thanks-launch';b.dataset.realThanksLaunch='1';b.textContent='目の前の1つで、本当に探す →';b.addEventListener('click',open);replay.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-thanks-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-thanks-card" role="dialog" aria-modal="true" aria-labelledby="realThanksTitle">
    <div class="real-thanks-head"><div><small>REAL LIFE / SUPPORT HUNT</small><h2 id="realThanksTitle">いま目の前にあるものの、<br>後ろを3つ掘る。</h2></div><button data-rth-close type="button" aria-label="閉じる">×</button></div>
    <section data-rth-step="input"><p>ありがたいと思わなくていい。実在する支えを見つけるだけ。</p><label><span>いま使っている／目の前にあるもの</span><input data-rth-target maxlength="70" placeholder="例：スマホ、コーヒー、電車、エアコン"></label><div class="real-thanks-meter"><div><span>いま「後ろ」が見えている感じ</span><strong><b data-rth-before-v>3</b>/10</strong></div><input data-rth-before type="range" min="0" max="10" value="3"></div><button class="real-thanks-primary" data-rth-start type="button" disabled>支えを探す →</button></section>
    <section data-rth-step="hunt" hidden><div class="real-thanks-target"><small>TARGET</small><strong data-rth-target-out></strong></div><div class="real-thanks-lenses">${Object.entries(cats).map(([id,v],i)=>`<button type="button" data-rth-cat="${id}" class="${i===0?'selected':''}"><span>${v[1]}</span>${v[0]}</button>`).join('')}</div><label><span>このレンズで見える支え</span><input data-rth-support maxlength="70" placeholder="例：配送した人、通信網、電池の材料"></label><button class="real-thanks-primary" data-rth-add type="button" disabled>1つ発見する ＋</button><div class="real-thanks-found" data-rth-found></div><div class="real-thanks-breadth"><span>発見 <b data-rth-count>0</b>/3</span><span>観察幅 <b data-rth-breadth>0</b>/6</span></div><button class="real-thanks-primary" data-rth-measure type="button" disabled>見え方の変化を測る →</button></section>
    <section data-rth-step="after" hidden><div class="real-thanks-chain" data-rth-chain></div><div class="real-thanks-meter"><div><span>いま「後ろ」が見えている感じ</span><strong><b data-rth-after-v>3</b>/10</strong></div><input data-rth-after type="range" min="0" max="10" value="3"></div><small>感謝の気分ではなく、「支えを具体的に見つけられる感覚」をそのまま。</small><button class="real-thanks-primary" data-rth-finish type="button">Before / Afterを見る</button></section>
    <section data-rth-step="done" hidden><h3 data-rth-done-title>当たり前の後ろに、具体物が増えた。</h3><div class="real-thanks-result" data-rth-result></div><div class="real-thanks-delta" data-rth-delta></div><div class="real-thanks-history" data-rth-history hidden></div><button class="real-thanks-secondary" data-rth-again type="button">別のものでもう1回</button></section>
  </div>`;document.body.appendChild(modal);$('[data-rth-close]',modal).onclick=close;$('[data-rth-target]',modal).oninput=()=>{$('[data-rth-start]',modal).disabled=$('[data-rth-target]',modal).value.trim().length<1};$('[data-rth-before]',modal).oninput=e=>$('[data-rth-before-v]',modal).textContent=e.target.value;$('[data-rth-after]',modal).oninput=e=>$('[data-rth-after-v]',modal).textContent=e.target.value;$('[data-rth-start]',modal).onclick=startHunt;$$('[data-rth-cat]',modal).forEach(b=>b.onclick=()=>pickCat(b));$('[data-rth-support]',modal).oninput=()=>{$('[data-rth-add]',modal).disabled=$('[data-rth-support]',modal).value.trim().length<1};$('[data-rth-add]',modal).onclick=add;$('[data-rth-measure]',modal).onclick=measure;$('[data-rth-finish]',modal).onclick=finish;$('[data-rth-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function show(n){$$('[data-rth-step]',modal).forEach(s=>s.hidden=s.dataset.rthStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-rth-target]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-thanks-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-thanks-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();found=[];currentCat='person';$('[data-rth-target]',modal).value='';$('[data-rth-support]',modal).value='';$('[data-rth-before]',modal).value='3';$('[data-rth-after]',modal).value='3';$('[data-rth-before-v]',modal).textContent='3';$('[data-rth-after-v]',modal).textContent='3';$('[data-rth-start]',modal).disabled=true;$('[data-rth-add]',modal).disabled=true;$$('[data-rth-cat]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rthCat==='person'));renderFound();show('input')}
  function startHunt(){const t=$('[data-rth-target]',modal).value.trim();if(!t)return;$('[data-rth-target-out]',modal).textContent=t;show('hunt');try{window.LevelUpTelemetry?.step?.('real-thanks-hunt')}catch{}}
  function pickCat(b){currentCat=b.dataset.rthCat;$$('[data-rth-cat]',modal).forEach(x=>x.classList.toggle('selected',x===b));$('[data-rth-support]',modal).focus({preventScroll:true})}
  function add(){const v=$('[data-rth-support]',modal).value.trim();if(!v)return;found.push({cat:currentCat,text:v});$('[data-rth-support]',modal).value='';$('[data-rth-add]',modal).disabled=true;renderFound();try{window.LevelUpTelemetry?.action?.(`real-thanks-${currentCat}`)}catch{}}
  function renderFound(){if(!modal)return;const box=$('[data-rth-found]',modal);box.innerHTML=found.map((f,i)=>`<div><span>${cats[f.cat][1]}</span><strong>${esc(f.text)}</strong><button type="button" data-remove="${i}" aria-label="削除">×</button></div>`).join('');$$('[data-remove]',box).forEach(b=>b.onclick=()=>{found.splice(Number(b.dataset.remove),1);renderFound()});const breadth=new Set(found.map(f=>f.cat)).size;$('[data-rth-count]',modal).textContent=String(found.length);$('[data-rth-breadth]',modal).textContent=String(breadth);$('[data-rth-measure]',modal).disabled=found.length<3||breadth<2}
  function measure(){const before=$('[data-rth-before]',modal).value;$('[data-rth-after]',modal).value=before;$('[data-rth-after-v]',modal).textContent=before;$('[data-rth-chain]',modal).innerHTML=`<strong>${esc($('[data-rth-target]',modal).value.trim())}</strong>${found.map(f=>`<span>→ ${cats[f.cat][1]} ${esc(f.text)}</span>`).join('')}`;show('after')}
  function finish(){const before=Number($('[data-rth-before]',modal).value),after=Number($('[data-rth-after]',modal).value),delta=after-before,breadth=new Set(found.map(f=>f.cat).size),target=$('[data-rth-target]',modal).value.trim();$('[data-rth-done-title]',modal).textContent=delta>0?'見えなかった「後ろ」が、少し見えた。':delta===0?'感覚は同じ。でも3つの支えを具体化した。':'感覚は下がった。でも発見した事実は残る。';$('[data-rth-result]',modal).innerHTML=`<small>${esc(target)} を支えていたもの</small>${found.map(f=>`<div><span>${cats[f.cat][1]}</span><b>${esc(f.text)}</b><em>${cats[f.cat][0]}</em></div>`).join('')}`;$('[data-rth-delta]',modal).textContent=`「後ろ」が見える感じ ${before} → ${after}　／　観察幅 ${breadth}/6`;save({delta,breadth,count:found.length});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'arigatou-sagashi',delta,breadth,count:found.length}}));window.LevelUpTelemetry?.complete?.('real-thanks')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-rth-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const avg=runs.reduce((s,r)=>s+Number(r.breadth||0),0)/runs.length;el.hidden=false;el.textContent=`現実ハント ${runs.length}回。平均観察幅 ${avg.toFixed(1)}/6。`; }catch{}}
  function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  ensureLauncher();
})();
