(() => {
'use strict';
const N=15,MAX=100;
const TRAITS={late:'少し遅れがち',detailed:'細部を詰める',blunt:'反応がそっけない',hasty:'すぐ進めたい',longtalk:'話が長くなりやすい',slowreply:'返信が遅め',cautious:'慎重に確認したい',improv:'その場で決める',perfection:'完成度を上げ続ける',verbal:'口頭で進めたい',forgetful:'抜けが出やすい',critic:'まず懸念点を見る',social:'雑談が多め',silent:'リアクションが薄い',interrupt:'結論を急ぐ',solo:'一人で進めたい',changeable:'優先順位が変わりやすい',early:'早く始めすぎる',deep:'一つを深掘りする',multitask:'同時に抱えやすい'};
const SURNAMES=['田中','佐藤','鈴木','高橋','伊藤','渡辺','山本','中村','小林','加藤','吉田','山田','佐々木','山口','松本','井上','木村','林','清水','斎藤','阿部','森','池田','橋本','石川'], GIVENS=['葵','蓮','凛','湊'], TK=Object.keys(TRAITS);
const ROSTER=[];let ri=0;for(const s of SURNAMES)for(const g of GIVENS){ROSTER.push({id:ri,name:`${s} ${g}`,shortName:`${s}さん`,trait:TK[ri%TK.length]});ri++;}
const O=(change,place,request,distance,task)=>({change,place,request,distance,task});
const S=(id,level,trait,situation,problem,best,good,options,safety=false)=>({id,level,trait,situation,problem,best,good,options,safety});
const SC=[
S('late',1,'late','{{name}}は朝会にまた5分遅れてきた。','朝一の引き継ぎが毎回止まる。','place',['request'],O('遅刻を直すよう長く話す','朝一の依存タスクから外す','「9:30までに共有」に変える','朝会への参加を減らす','午後に完結する仕事を任せる')),
S('detail',1,'detailed','{{name}}は資料の余白や言い回しまで細かく直す。','今日出したい企画書が完成しない。','task',['request'],O('「細かすぎる」と指摘する','初稿レビューから外す','「15時は論点だけ確認」にする','レビュー回数を1回にする','最終品質チェックを任せる')),
S('blunt',1,'blunt','{{name}}は返事が短く、愛想もほとんどない。','新人が「怒られている気がする」と萎縮している。','distance',['place'],O('もっと愛想よくするよう求める','新人との直接ペアを外す','語尾に一言足すよう依頼する','窓口を一人はさんで接点を整える','一人で完結する集計を任せる')),
S('hasty',1,'hasty','{{name}}は結論が見えるとすぐ次へ進めたがる。','確認不足のまま公開しそうになる。','request',['task'],O('「せっかちを直して」と注意する','公開操作の席から離す','公開前チェック3項目だけ必須にする','最終承認者を別にする','初動が重要な一次対応を任せる')),
S('long',1,'longtalk','{{name}}の話は情報量が多く、会議で長くなりやすい。','30分会議が毎回60分になる。','request',['distance'],O('「話を短くして」と説教する','会議の最後だけ参加してもらう','先に3行メモ、発言は2分にする','詳細は別スレッドへ切り出す','議事録と背景整理を任せる')),
S('slowreply',2,'slowreply','{{name}}へのチャットは半日返ってこないことがある。','小さな承認待ちで作業が止まる。','request',['distance'],O('返信を早くするよう注意する','隣の席に移す','YES/NOだけを期限つきで送る','一定時間で代理承認に切り替える','返信不要で完結する仕事にする')),
S('cautious',2,'cautious','{{name}}は「念のため」を重ね、確認項目を増やす。','小さなテスト公開まで止まっている。','task',['request'],O('もっと大胆になるよう説得する','意思決定の場から外す','止めてよい条件を3つだけ決める','本番判断だけ参加してもらう','リスク洗い出し役に固定する')),
S('improv',2,'improv','{{name}}は会話中に思いつくと、その場で仕様を変える。','チームの作業範囲が毎日動く。','request',['place'],O('思いつきで変えないよう叱る','アイデア出し会だけ参加してもらう','変更案は翌日のバックログへ入れる','実装担当との直チャットを減らす','ゼロイチの企画案を任せる')),
S('perfect',2,'perfection','{{name}}は80点でも提出せず、完成度を上げ続ける。','初稿が共有されず、周囲が動けない。','request',['task'],O('完璧主義をやめるよう言う','締切直前の担当から外す','60点版を12時に強制共有する','レビュー担当を別にする','最終仕上げ工程を任せる')),
S('verbal',2,'verbal','{{name}}は口頭で話すと早いが、記録をほとんど残さない。','翌日「何を決めた？」が起きる。','request',['place'],O('文章を書く習慣をつけてもらう','記録係とペアにする','会話後に選択肢を1タップ確認する','重要案件は口頭窓口を一本化する','対面ヒアリングを任せる')),
S('forget',3,'forgetful','{{name}}は忙しくなると、細かな依頼が抜ける。','頼んだかの確認に毎日時間を使う。','request',['task'],O('もっと注意深くするよう説教する','常に目の届く席にする','依頼は口頭禁止、1つの一覧に集める','確認は夕方1回だけにする','抜けても影響が小さい独立タスクを任せる')),
S('critic',3,'critic','{{name}}は新案を聞くと、まず弱点や失敗条件を挙げる。','アイデア出しの場で全員が黙ってしまう。','place',['task'],O('もっと前向きになるよう頼む','発散会ではなく評価会から参加してもらう','最初の10分は懸念を言わないルールにする','アイデア担当との直接討論を減らす','リスクレビューを任せる')),
S('social',3,'social','{{name}}は人と話すのが好きで、席を回って雑談する。','集中中のメンバーが何度も中断される。','place',['distance'],O('仕事中は雑談しないよう注意する','交流が必要な窓口席へ移す','雑談は休憩帯にまとめてもらう','集中席をサイレントゾーンにする','新人オンボーディングを任せる')),
S('silent',3,'silent','{{name}}は会議でほぼ頷かず、反応も短い。','進行役が不安になり、説明を繰り返す。','request',['distance'],O('もっと反応してほしいと伝える','発言の多い人の隣にする','理解したら「OK」だけ押してもらう','口頭確認をやめ最後に一括確認する','一人で深く読むレビューを任せる')),
S('interrupt',3,'interrupt','{{name}}は途中で結論が見えると、説明を遮って先へ進める。','若手の報告が最後まで聞かれず、情報が抜ける。','request',['place'],O('最後まで聞くよう注意する','質疑は報告の後半だけ参加してもらう','最初に結論、その後「追加3点」の型にする','若手との1対1報告を減らす','緊急時の意思決定を任せる')),
S('solo',4,'solo','{{name}}は一人だと速いが、共同作業では共有が減る。','チーム制作で途中経過が見えない。','task',['request'],O('もっと協調的になるよう求める','常にペア作業にする','毎日17時に成果物だけ自動共有する','相談窓口を一人に絞る','境界が明確な単独モジュールを任せる')),
S('changeable',4,'changeable','{{name}}は状況が変わるたび優先順位を変える。','周囲が毎回作業を切り替え、全部が遅くなる。','distance',['request'],O('一度決めたら変えないよう説得する','進行会議から外す','変更案は「翌日反映」に統一する','優先順位を変えられる窓口を一人にする','緊急案件の振り分けだけ任せる')),
S('multi',4,'multitask','{{name}}は頼まれると断らず、同時に7件くらい抱える。','どの仕事も8割で止まり、確認待ちが増える。','request',['task','distance'],O('もっと集中するよう注意する','依頼が来ない席に移す','同時進行は2件まで、追加は待ち列へ','依頼窓口を一人にする','短時間で閉じる小タスクを中心に任せる')),
S('safety',4,'hasty','{{name}}が安全確認を飛ばして作業を進めようとしている。','事故につながる可能性がある。','distance',['request'],O('性格を直すまで説教を続ける','危険工程から一時的に外す','安全手順と停止条件を明文化する','作業を止め責任者・安全ルールへ上げる','別の軽作業だけ任せる'),true),
S('harass',4,'blunt','{{name}}の発言が相手への侮辱になり、同僚が苦痛を訴えた。','「その人らしさ」で済ませてはいけない。','distance',['request'],O('人格を改めるまで言い争う','被害を受けた人との配置だけ変える','許容されない言動を明確に伝え記録する','接触を止め、上司・人事・相談窓口へ上げる','一人作業へ変えて終わらせる'),true)
];
const LV={1:'LEVEL 1 · 分かりやすい癖',2:'LEVEL 2 · 仕事の設計',3:'LEVEL 3 · 人間関係の摩擦',4:'LEVEL 4 · 複合問題'};
const META={place:{label:'配置を変える',icon:'↔'},request:{label:'頼み方を変える',icon:'✉'},distance:{label:'距離を変える',icon:'◎'},task:{label:'任せる仕事を変える',icon:'◆'},change:{label:'直させる',icon:'!'}};
const $=id=>document.getElementById(id),E={hero:$('heroScreen'),game:$('gameScreen'),result:$('resultScreen'),start:$('startBtn'),retry:$('retryBtn'),home:$('homeBtn'),how:$('howBtn'),howDialog:$('howDialog'),closeHow:$('closeHowBtn'),dialogStart:$('dialogStartBtn'),sound:$('soundBtn'),best:$('bestPill'),progressFill:$('progressFill'),progressText:$('progressText'),combo:$('comboValue'),comboPill:$('comboPill'),flow:$('flowValue'),relation:$('relationValue'),time:$('timeValue'),cost:$('costValue'),flowDelta:$('flowDelta'),relationDelta:$('relationDelta'),timeDelta:$('timeDelta'),costDelta:$('costDelta'),level:$('levelLabel'),personNo:$('personNo'),personName:$('personName'),personTrait:$('personTrait'),problem:$('problemText'),situation:$('situationText'),actionGrid:$('actionGrid'),feedback:$('feedbackPanel'),feedbackBadge:$('feedbackBadge'),feedbackGrade:$('feedbackGrade'),feedbackTitle:$('feedbackTitle'),feedbackBody:$('feedbackBody'),feedbackDeltas:$('feedbackDeltas'),continueBtn:$('continueBtn'),encounter:$('encounter'),roster:$('roster'),solved:$('solvedLabel'),placeCount:$('placeCount'),requestCount:$('requestCount'),distanceCount:$('distanceCount'),taskCount:$('taskCount'),adapted:$('adaptedCount'),adaptRate:$('adaptRate'),optRate:$('optRate'),finalCost:$('finalCost'),maxCombo:$('maxCombo'),resultNote:$('resultHeroNote'),barPlace:$('barPlace'),barRequest:$('barRequest'),barDistance:$('barDistance'),barTask:$('barTask'),chartPlace:$('chartPlace'),chartRequest:$('chartRequest'),chartDistance:$('chartDistance'),chartTask:$('chartTask'),resultMessage:$('resultMessage'),heroPeople:$('heroPeople')};
let st={};
const clamp=n=>Math.max(0,Math.min(MAX,n));
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function session(){const normal=SC.filter(x=>!x.safety);return[...shuffle(normal.filter(x=>x.level===1)).slice(0,4),...shuffle(normal.filter(x=>x.level===2)).slice(0,4),...shuffle(normal.filter(x=>x.level===3)).slice(0,4),...shuffle(normal.filter(x=>x.level===4)).slice(0,2),...shuffle(SC.filter(x=>x.safety)).slice(0,1)];}
const tpl=(t,n)=>String(t).replaceAll('{{name}}',n.shortName);
function build(){const pts=[[8,18],[22,10],[39,15],[63,9],[81,17],[92,31],[14,39],[29,33],[72,34],[87,45],[7,60],[20,70],[36,64],[66,67],[83,63],[94,76],[14,85],[31,83],[58,86],[78,88]];E.heroPeople.innerHTML=pts.map((p,i)=>`<i class="hero-person" style="left:${p[0]}%;top:${p[1]}%;animation-delay:${-(i%7)*.45}s"></i>`).join('');E.roster.innerHTML=ROSTER.map(n=>`<span class="npc-dot" data-id="${n.id}" title="${n.name}"></span>`).join('');updateBest();}
function safeGet(k){try{return localStorage.getItem(k)}catch{return null}}function safeSet(k,v){try{localStorage.setItem(k,v)}catch{}}
function updateBest(){const b=Number(safeGet('dont-change-people-best')||0);E.best.textContent=b?`BEST ${b}`:'BEST --';}
function reset(){st={turn:0,session:session(),flow:50,relation:65,time:100,cost:0,combo:0,maxCombo:0,solved:0,change:0,best:0,good:0,counts:{place:0,request:0,distance:0,task:0},used:new Set(),locked:false,sound:true};E.roster.querySelectorAll('.npc-dot').forEach(d=>d.className='npc-dot');render();}
function start(){reset();E.hero.classList.add('hidden');E.result.classList.add('hidden');E.game.classList.remove('hidden');if(E.howDialog.open)E.howDialog.close();next();window.scrollTo({top:0,behavior:'auto'});}
function pickNpc(trait){let pool=ROSTER.filter(n=>n.trait===trait&&!st.used.has(n.id));if(!pool.length)pool=ROSTER.filter(n=>!st.used.has(n.id));const n=pool[Math.floor(Math.random()*pool.length)];st.used.add(n.id);return n;}
function next(){if(st.turn>=st.session.length)return finish();st.locked=false;E.feedback.classList.add('hidden');const sc=st.session[st.turn],n=pickNpc(sc.trait);st.npc=n;E.progressFill.style.width=`${st.turn/N*100}%`;E.progressText.textContent=`${st.turn+1} / ${N}`;E.level.textContent=LV[sc.level];E.personNo.textContent=`PERSON ${String(n.id+1).padStart(2,'0')} / 100`;E.personName.textContent=n.name;E.personTrait.textContent=TRAITS[n.trait];E.problem.textContent=tpl(sc.problem,n);E.situation.textContent=tpl(sc.situation,n);markActive(n.id);actions(sc,n);tone(300,.025,.03);}
function actions(sc,n){E.actionGrid.innerHTML=['place','request','distance','task','change'].map(k=>`<button type="button" class="action-button ${k}" data-action="${k}"><span class="action-icon">${META[k].icon}</span><span class="action-copy"><b>${META[k].label}</b><small>${tpl(sc.options[k],n)}</small></span><em>›</em></button>`).join('');E.actionGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>resolve(b.dataset.action,sc,n));}
function outcome(a,sc){if(a==='change')return{grade:'change',flow:-4,relation:-10,time:-15,cost:20};if(a===sc.best)return{grade:'best',flow:12,relation:4,time:-2,cost:0};if(sc.good.includes(a))return{grade:'good',flow:6,relation:2,time:-4,cost:0};if(sc.safety)return{grade:'bad',flow:-8,relation:-6,time:-8,cost:5};return{grade:'bad',flow:-2,relation:-1,time:-6,cost:0};}
function fb(a,o,sc){if(a==='change')return['CHANGE COST +20','相手を変えにいった。正しさは伝えても、仕事・関係・時間を同時に使う。'];if(sc.safety&&a==='distance')return['安全を優先した。','これは「合わせる」問題ではない。距離・停止・相談・ルールへ上げる。'];const t={place:['配置を動かした。','組み合わせや順番を変えると、人格を直さず摩擦を減らせる。'],request:['頼み方を動かした。','期限・粒度・手順を変えれば、相手はそのままでも仕事は変わる。'],distance:['距離を動かした。','接点・窓口・境界線は、自分側で設計できる。'],task:['仕事を動かした。','癖を消すより、その癖が困りにくい仕事へ寄せられる。']};return o.grade==='bad'?['方向は変えたが、まだ遠い。',t[a][1]]:t[a];}
function resolve(a,sc,n){if(st.locked)return;st.locked=true;const o=outcome(a,sc);st.flow=clamp(st.flow+o.flow);st.relation=clamp(st.relation+o.relation);st.time=clamp(st.time+o.time);st.cost+=o.cost;st.solved++;if(a==='change'){st.change++;st.combo=0}else{st.counts[a]++;st.combo=(o.grade==='best'||o.grade==='good')?st.combo+1:Math.max(0,st.combo-1);st.maxCombo=Math.max(st.maxCombo,st.combo)}if(o.grade==='best')st.best++;if(o.grade==='good')st.good++;render(o);markDone(n.id,a);showFb(a,o,sc);E.actionGrid.querySelectorAll('button').forEach(b=>{b.disabled=true;if(b.dataset.action===a)b.classList.add('selected',o.grade==='best'?'best':o.grade==='good'?'good':'bad')});E.encounter.classList.remove('flash-good','flash-bad');void E.encounter.offsetWidth;E.encounter.classList.add(o.grade==='best'||o.grade==='good'?'flash-good':'flash-bad');play(o.grade);}
function showFb(a,o,sc){const [t,b]=fb(a,o,sc),badge={best:['SETTING CHANGED','◎'],good:['WORKS','○'],bad:['NOT ENOUGH','△'],change:['CHANGE COST +20','×']}[o.grade];E.feedbackBadge.textContent=badge[0];E.feedbackGrade.textContent=badge[1];E.feedbackTitle.textContent=t;E.feedbackBody.textContent=b;E.feedback.classList.toggle('wrong',o.grade==='bad'||o.grade==='change');E.feedbackDeltas.innerHTML=[['FLOW',o.flow],['関係',o.relation],['時間',o.time],['説得',o.cost]].map(([l,v])=>`<span class="${v>0&&l!=='説得'?'positive':v<0||(l==='説得'&&v>0)?'negative':''}">${l} ${v>0?'+':''}${v}</span>`).join('');E.feedback.classList.remove('hidden');E.feedback.scrollIntoView({behavior:'smooth',block:'nearest'});}
function delta(el,v,cost=false){el.textContent=`${v>0?'+':''}${v}`;el.style.color=cost&&v>0?'#ff9a9a':v>=0?'#b8f25a':'#ff9a9a';el.classList.remove('show');void el.offsetWidth;el.classList.add('show');}
function render(o){E.flow.textContent=st.flow;E.relation.textContent=st.relation;E.time.textContent=st.time;E.cost.textContent=st.cost;E.combo.textContent=st.combo;E.comboPill.classList.toggle('hot',st.combo>=3);E.solved.textContent=`${st.solved}人対応`;E.placeCount.textContent=st.counts.place;E.requestCount.textContent=st.counts.request;E.distanceCount.textContent=st.counts.distance;E.taskCount.textContent=st.counts.task;if(o){delta(E.flowDelta,o.flow);delta(E.relationDelta,o.relation);delta(E.timeDelta,o.time);delta(E.costDelta,o.cost,true)}}
function markActive(id){E.roster.querySelectorAll('.npc-dot').forEach(d=>d.classList.remove('active'));const d=E.roster.querySelector(`[data-id="${id}"]`);if(d)d.classList.add('active')}
function markDone(id,a){const d=E.roster.querySelector(`[data-id="${id}"]`);if(d){d.classList.remove('active');d.classList.add(`done-${a}`)}}
function finish(){E.game.classList.add('hidden');E.result.classList.remove('hidden');const adapted=N-st.change,ar=Math.round(adapted/N*100),op=Math.round((st.best+st.good*.5)/N*100);E.adapted.textContent=adapted;E.adaptRate.textContent=`${ar}%`;E.optRate.textContent=`${op}%`;E.finalCost.textContent=st.cost;E.maxCombo.textContent=st.maxCombo;E.resultNote.textContent=st.change===0?'15人とも、人格を直さずに処理した。':`「直させる」を選んだのは${st.change}回。次はレバーを探せる。`;const total=Math.max(1,Object.values(st.counts).reduce((a,b)=>a+b,0)),bars=[['place',E.barPlace,E.chartPlace],['request',E.barRequest,E.chartRequest],['distance',E.barDistance,E.chartDistance],['task',E.barTask,E.chartTask]];bars.forEach(([k,b,l])=>{l.textContent=st.counts[k];b.style.width=`${st.counts[k]/total*100}%`});const dom=Object.entries(st.counts).sort((a,b)=>b[1]-a[1])[0][0],msg={place:'組み合わせや順番を動かすのが得意。人の相性を工程へ戻せている。',request:'頼み方を設計するのが得意。相手の性格より伝達条件を見ている。',distance:'距離と境界線を作るのが得意。接点の量を自分側で調整できている。',task:'仕事の渡し方を変えるのが得意。弱点を消すより強みに寄せている。'};E.resultMessage.textContent=msg[dom];const score=Math.round(ar*.55+op*.45),old=Number(safeGet('dont-change-people-best')||0);if(score>old)safeSet('dont-change-people-best',String(score));updateBest();window.scrollTo({top:0,behavior:'smooth'});tone(620,.12,.04);setTimeout(()=>tone(790,.14,.035),120)}
function tone(f,d=.04,g=.03){if(!st.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!window.__dcAudio)window.__dcAudio=new C();const c=window.__dcAudio,o=c.createOscillator(),x=c.createGain();o.type='sine';o.frequency.value=f;x.gain.value=g;o.connect(x);x.connect(c.destination);o.start();x.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}}
function play(g){if(g==='best'){tone(520,.06,.04);setTimeout(()=>tone(690,.06,.035),70)}else if(g==='good')tone(500,.07,.035);else tone(190,.1,.045)}
E.continueBtn.onclick=()=>{if(st.locked){st.turn++;next()}};E.start.onclick=start;E.dialogStart.onclick=start;E.retry.onclick=start;E.home.onclick=()=>{E.result.classList.add('hidden');E.game.classList.add('hidden');E.hero.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};E.how.onclick=()=>E.howDialog.showModal();E.closeHow.onclick=()=>E.howDialog.close();E.sound.onclick=()=>{st.sound=!st.sound;E.sound.textContent=st.sound?'♪':'×';E.sound.setAttribute('aria-label',st.sound?'効果音をオフにする':'効果音をオンにする');if(st.sound)tone(440,.04,.03)};E.howDialog.onclick=e=>{if(e.target===E.howDialog)E.howDialog.close()};
st.sound=true;build();reset();
})();
