(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-dont-change-real-v1';
  const LEVERS={
    place:{name:'配置を変える',prompt:'その人に依存して止まる場所を、どこから外す？'},
    request:{name:'頼み方を変える',prompt:'「何を・いつまでに・どの形で」をどう明確にする？'},
    distance:{name:'距離を変える',prompt:'接点・確認回数・窓口をどう減らす／整える？'},
    task:{name:'任せる仕事を変える',prompt:'その人の癖が弱点になりにくい仕事へ、何を移す？'}
  };
  const SAFETY={stop:'接触・作業をいったん止める',record:'事実を記録する',escalate:'責任者・人事・相談窓口へ上げる',rule:'安全ルール・停止条件を確認する'};
  let modal,safety=false,lever='request',safetyAction='stop',before=8;
  const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));

  function ensureLauncher(){const retry=$('#retryBtn');if(!retry||$('[data-real-people-launch]'))return;const b=document.createElement('button');b.type='button';b.className='real-people-launch';b.dataset.realPeopleLaunch='1';b.textContent='今の一人で、関わり方を変える →';b.addEventListener('click',open);retry.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-people-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-people-card" role="dialog" aria-modal="true" aria-labelledby="realPeopleTitle"><div class="real-people-head"><div><small>REAL LIFE / CHANGE THE SYSTEM</small><h2 id="realPeopleTitle">相手の人格ではなく、<br>自分側の設計を変える。</h2></div><button type="button" data-rp-close aria-label="閉じる">×</button></div>
    <section data-rp-step="input"><label><span>いま「変わってほしい」と思っている相手の行動</span><textarea data-rp-behavior maxlength="180" placeholder="例：返信が遅く、承認待ちで作業が止まる。"></textarea></label><div class="real-people-safety"><span>これは安全・ハラスメント・明確な権利侵害を含む？</span><div><button type="button" data-rp-safety="normal" class="selected">含まない</button><button type="button" data-rp-safety="safety">含む／判断に迷う</button></div></div><div class="real-people-meter"><div><span>いま「相手を変えたい」圧</span><strong><b data-rp-before-v>8</b>/10</strong></div><input data-rp-before type="range" min="0" max="10" value="8"></div><button class="real-people-primary" data-rp-next type="button" disabled>自分側のレバーを見る →</button></section>
    <section data-rp-step="lever" hidden><div class="real-people-normal" data-rp-normal><p>相手を説得し続ける前に、変えられる構造を1つ。</p><div class="real-people-levers">${Object.entries(LEVERS).map(([id,v],i)=>`<button type="button" data-rp-lever="${id}" class="${i===1?'selected':''}"><b>${v.name}</b><small>${v.prompt}</small></button>`).join('')}</div><label><span data-rp-prompt>「何を・いつまでに・どの形で」をどう明確にする？</span><textarea data-rp-action maxlength="180" placeholder="例：承認依頼をYES/NOの2択＋17時期限で送る。"></textarea></label></div><div class="real-people-danger" data-rp-danger hidden><div class="real-people-warning"><b>ここは「相手に合わせる」問題ではありません。</b><span>危険・ハラスメント・権利侵害は、距離を取り、記録し、必要なら組織・専門窓口へ上げる。</span></div><div class="real-people-safety-actions">${Object.entries(SAFETY).map(([id,v],i)=>`<button type="button" data-rp-safe-action="${id}" class="${i===0?'selected':''}">${v}</button>`).join('')}</div><label><span>今できる保護行動を1つ</span><textarea data-rp-protect maxlength="180" placeholder="例：今日の発言を日時と事実だけ記録し、上司に共有する。"></textarea></label></div><button class="real-people-primary" data-rp-measure type="button" disabled>自分側の一手を決めた →</button></section>
    <section data-rp-step="after" hidden><div class="real-people-summary" data-rp-summary></div><div class="real-people-meter"><div><span>いま「相手を変えたい」圧</span><strong><b data-rp-after-v>8</b>/10</strong></div><input data-rp-after type="range" min="0" max="10" value="8"></div><small>下がっていなくてもOK。相手が変わったことにはしない。</small><button class="real-people-primary" data-rp-finish type="button">Before / Afterを見る</button></section>
    <section data-rp-step="done" hidden><h3 data-rp-done-title>相手ではなく、レバーを1つ動かす。</h3><div class="real-people-output"><div><small>FRICTION / 困っていること</small><p data-rp-behavior-out></p></div><div><small>MY LEVER</small><strong data-rp-lever-out></strong></div><div><small>NEXT MOVE</small><strong data-rp-action-out></strong></div></div><div class="real-people-delta" data-rp-delta></div><div class="real-people-history" data-rp-history hidden></div><button class="real-people-secondary" data-rp-again type="button">別の一人でもう1回</button></section></div>`;document.body.appendChild(modal);
    $('[data-rp-close]',modal).onclick=close;$('[data-rp-behavior]',modal).oninput=validateStart;$('[data-rp-before]',modal).oninput=e=>{before=Number(e.target.value);$('[data-rp-before-v]',modal).textContent=e.target.value};$$('[data-rp-safety]',modal).forEach(b=>b.onclick=()=>selectSafety(b));$('[data-rp-next]',modal).onclick=openLever;$$('[data-rp-lever]',modal).forEach(b=>b.onclick=()=>selectLever(b));$$('[data-rp-safe-action]',modal).forEach(b=>b.onclick=()=>selectSafeAction(b));$('[data-rp-action]',modal).oninput=validateLever;$('[data-rp-protect]',modal).oninput=validateLever;$('[data-rp-measure]',modal).onclick=measure;$('[data-rp-after]',modal).oninput=e=>$('[data-rp-after-v]',modal).textContent=e.target.value;$('[data-rp-finish]',modal).onclick=finish;$('[data-rp-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function show(n){$$('[data-rp-step]',modal).forEach(s=>s.hidden=s.dataset.rpStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-rp-behavior]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-people-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-people-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();safety=false;lever='request';safetyAction='stop';before=8;['behavior','action','protect'].forEach(id=>$(`[data-rp-${id}]`,modal).value='');$('[data-rp-before]',modal).value='8';$('[data-rp-after]',modal).value='8';$('[data-rp-before-v]',modal).textContent='8';$('[data-rp-after-v]',modal).textContent='8';$$('[data-rp-safety]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rpSafety==='normal'));$$('[data-rp-lever]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rpLever==='request'));$$('[data-rp-safe-action]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rpSafeAction==='stop'));$('[data-rp-next]',modal).disabled=true;$('[data-rp-measure]',modal).disabled=true;show('input')}
  function validateStart(){$('[data-rp-next]',modal).disabled=$('[data-rp-behavior]',modal).value.trim().length<2}
  function selectSafety(b){safety=b.dataset.rpSafety==='safety';$$('[data-rp-safety]',modal).forEach(x=>x.classList.toggle('selected',x===b))}
  function openLever(){$('[data-rp-normal]',modal).hidden=safety;$('[data-rp-danger]',modal).hidden=!safety;validateLever();show('lever')}
  function selectLever(b){lever=b.dataset.rpLever;$$('[data-rp-lever]',modal).forEach(x=>x.classList.toggle('selected',x===b));$('[data-rp-prompt]',modal).textContent=LEVERS[lever].prompt}
  function selectSafeAction(b){safetyAction=b.dataset.rpSafeAction;$$('[data-rp-safe-action]',modal).forEach(x=>x.classList.toggle('selected',x===b))}
  function validateLever(){const value=(safety?$('[data-rp-protect]',modal):$('[data-rp-action]',modal)).value.trim();$('[data-rp-measure]',modal).disabled=value.length<2}
  function measure(){const after=$('[data-rp-after]',modal);after.value=String(before);$('[data-rp-after-v]',modal).textContent=String(before);const action=(safety?$('[data-rp-protect]',modal):$('[data-rp-action]',modal)).value.trim(),label=safety?SAFETY[safetyAction]:LEVERS[lever].name;$('[data-rp-summary]',modal).innerHTML=`<small>${safety?'PROTECT':'MY LEVER'}</small><strong>${esc(label)}</strong><span>${esc(action)}</span>`;show('after')}
  function finish(){const after=Number($('[data-rp-after]',modal).value),delta=before-after,behavior=$('[data-rp-behavior]',modal).value.trim(),action=(safety?$('[data-rp-protect]',modal):$('[data-rp-action]',modal)).value.trim(),label=safety?SAFETY[safetyAction]:LEVERS[lever].name;$('[data-rp-behavior-out]',modal).textContent=behavior;$('[data-rp-lever-out]',modal).textContent=label;$('[data-rp-action-out]',modal).textContent=action;$('[data-rp-done-title]',modal).textContent=safety?'相手を変えるより、まず自分と周囲を守る。':delta>0?'相手を変えたい圧が、少し自分側へ戻った。':delta===0?'圧は同じ。でも自分側の一手は決まった。':'まだ圧は強い。相手を説得する前に、レバーを小さく試す。';$('[data-rp-delta]',modal).textContent=`相手を変えたい圧 ${before} → ${after}`;save({delta,safety,lever:safety?`safety-${safetyAction}`:lever});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'dont-change-people',delta,safety,lever}}));window.LevelUpTelemetry?.complete?.('real-people')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-rp-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const shifted=runs.filter(r=>Number(r.delta)>0).length;el.hidden=false;el.textContent=`現実ケース ${runs.length}件。${shifted}件で「変えたい圧」が下がりました。`}catch{}}
  ensureLauncher();
})();