(()=>{
const app=document.getElementById('app'),reset=document.getElementById('resetBtn'),STORE='levelup-100nin-rank-v1';
const DIMS={decision:{label:'決断力',copy:'情報が完璧でなくても、基準を作って結論へ進む傾向。'},action:{label:'行動速度',copy:'重いことでも、最初の一手を小さくして着手する傾向。'},resilience:{label:'メンタル耐久',copy:'失敗や否定のあと、必要なことへ戻る速さ。'},flexibility:{label:'切替力',copy:'予定や方法が崩れたとき、目的を保ってやり方を変える傾向。'},agency:{label:'主体性',copy:'曖昧な場でも、自分から次の形を作りにいく傾向。'}};
const Q=[
['選択肢が3つ。正解はまだ分からない。どうする？',[['まず仮決めして、必要なら後で変える',{decision:3,action:2,flexibility:2}],['比較条件を3つ決めてから選ぶ',{decision:2,action:1}],['詳しい人の意見を聞いてから決める',{decision:1,agency:1}],['もう少し情報が増えるまで保留する',{decision:0}]]],
['面倒な仕事。締切は3日後。最初にやるのは？',[['30秒だけ実物に触る',{action:3,decision:2}],['5分で段取りだけ作る',{action:2,decision:2}],['やる時間を先に決める',{action:1,decision:1}],['まだ余裕があるので明日に回す',{action:0}]]],
['かなり準備した提案が、あっさり断られた直後。どうなる？',[['理由を1つ拾って、次案を考え始める',{resilience:3,flexibility:2,action:2}],['今日は離れて、明日見直す',{resilience:2,flexibility:3}],['誰かに話して気持ちを整理する',{resilience:2,agency:1}],['しばらく触れたくなくなる',{resilience:0}]]],
['予定が急に2時間ずれた。最初の反応は？',[['空いた時間の使い方をその場で変える',{flexibility:3,decision:2}],['一度、予定表を組み直す',{flexibility:2,decision:2}],['とりあえず休んでから考える',{flexibility:1,resilience:1}],['予定通りでなくなり、かなり調子が崩れる',{flexibility:0}]]],
['会議で誰も結論を出さない。あなたは？',[['論点を整理して仮案を出す',{agency:3,decision:3}],['選択肢を作って、みんなに選んでもらう',{agency:2,decision:2}],['個別に意見を聞いてからまとめる',{agency:1,decision:1}],['進行役が決めるのを待つ',{agency:0}]]],
['高めの買い物。必要そうだけど迷う。どう決める？',[['判断条件を3つ決め、今日中に結論を出す',{decision:3}],['24時間だけ置いて、明日結論を出す',{decision:2,resilience:1}],['評判や比較をできるだけ調べ続ける',{decision:1}],['決めきれず、セール終了まで保留する',{decision:0}]]],
['2分で返せる返信。でも少し気が重い。どうする？',[['一文だけ今返す',{action:3,agency:2}],['下書きだけ今作る',{action:2}],['返信する時間を予定に入れる',{action:1,decision:1}],['気になりつつ、いったん閉じる',{action:0}]]],
['人前でミスを指摘された。その後の自分に近いのは？',[['直す点だけメモして、その場を続ける',{resilience:3,flexibility:2}],['一瞬へこむが、終わればだいたい戻る',{resilience:2}],['理由を説明して、誤解がないか確認する',{resilience:1,agency:1}],['頭から離れず、その後の調子も落ちる',{resilience:0}]]],
['いつものやり方が通用しない。次は？',[['目的は変えず、方法を大きく変える',{flexibility:3,decision:2}],['条件を1つだけ変えて試す',{flexibility:2,action:2}],['いつもの方法を、もう少し続けてみる',{flexibility:1,resilience:2}],['うまくいっている人の方法へ丸ごと乗り換える',{flexibility:2,agency:0}]]],
['「いい感じにまとめて」と曖昧な依頼が来た。どうする？',[['ゴールを確認してから進める',{agency:3,decision:2}],['たたき台を作って「この方向？」と聞く',{agency:3,action:3}],['周りのやり方を見て合わせる',{agency:1,flexibility:1}],['詳細な指示が来るまで待つ',{agency:0}]]],
['残り15分。終わっていないことが3つある。どう使う？',[['一番重要な1つを終わらせる',{decision:3,action:3}],['3つとも少しずつ進める',{action:2,flexibility:1}],['優先順位を決める時間に使う',{decision:2,agency:2}],['15分では足りないので明日に回す',{action:0}]]],
['失敗する可能性が30%ある新しい挑戦。どうする？',[['小さく試して、反応を見てから広げる',{action:3,resilience:3,flexibility:3,decision:2}],['成功確率を上げる準備を追加してからやる',{decision:2,resilience:2}],['経験者と一緒ならやる',{agency:1,resilience:2}],['失敗の影響が大きいなら今回はやめる',{decision:1}]]]
];
let index=0,answers=[],locked=false;
const maxPer=Q.map(q=>Object.fromEntries(Object.keys(DIMS).map(k=>[k,Math.max(...q[1].map(a=>a[1][k]||0))])));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scores(limit=answers.length){const s=Object.fromEntries(Object.keys(DIMS).map(k=>[k,0])),m=Object.fromEntries(Object.keys(DIMS).map(k=>[k,0]));for(let i=0;i<limit;i++){const a=Q[i][1][answers[i]];if(a)Object.entries(a[1]).forEach(([k,v])=>s[k]+=v);Object.keys(DIMS).forEach(k=>m[k]+=maxPer[i][k])}return Object.fromEntries(Object.keys(DIMS).map(k=>[k,m[k]?s[k]/m[k]:.5]))}
const rank=n=>Math.max(5,Math.min(82,Math.round(82-Math.pow(Math.max(0,Math.min(1,n)),.94)*76)));
function overall(n){const w={decision:1.08,action:1.15,resilience:1.02,flexibility:1,agency:.9};let a=0,b=0;Object.keys(DIMS).forEach(k=>{a+=n[k]*w[k];b+=w[k]});return a/b}
function resultData(){const n=scores(Q.length),dims=Object.fromEntries(Object.keys(DIMS).map(k=>[k,{rank:rank(n[k])}])),overallRank=rank(overall(n)),top=Object.keys(DIMS).sort((a,b)=>dims[a].rank-dims[b].rank),pair=[top[0],top[1]].sort().join('+'),types={'action+decision':['即断即動型','迷いをゼロにしてから動くより、決めながら前へ進みやすいタイプ。'],'flexibility+resilience':['リカバリー型','崩れないことより、崩れた後に戻ることと切り替えることが強み。'],'agency+decision':['前に出る司令塔型','曖昧な場で待つより、仮案や判断軸を置いて場を前へ進めやすいタイプ。'],'action+resilience':['折れずに進む実行型','気持ちが揺れても、次の一手を作って前進へ戻りやすいタイプ。'],'action+flexibility':['切替高速型','詰まったら方法を変え、止まる時間を短くしやすいタイプ。'],'decision+resilience':['腹を決める持久型','結論を出したあと、多少の逆風があっても持ち直して続けやすいタイプ。'],'agency+flexibility':['流れを変える推進型','状況に合わせながら、自分から次の形を作るのが得意なタイプ。']},t=types[pair]||['バランス型','一つの強さだけで押すより、状況に応じて複数の力を使い分けるタイプ。'];return{overall:overallRank,dims,archetype:t[0],archetypeCopy:t[1]}}
function encode(r){return btoa(unescape(encodeURIComponent(JSON.stringify(r)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decode(s){try{const p='='.repeat((4-s.length%4)%4);return JSON.parse(decodeURIComponent(escape(atob((s+p).replace(/-/g,'+').replace(/_/g,'/')))))}catch{return null}}
function crowd(r){return Array.from({length:100},(_,i)=>`<i class="person ${i+1===r?'me':i+1<r?'ahead':''}"></i>`).join('')}
function crowdBlock(r,label){return `<div class="crowd-wrap"><div class="crowd-head"><span>1位 ← 上位</span><b>${label}：${r}位付近</b><span>100位</span></div><div class="crowd" aria-label="100人中${r}位付近">${crowd(r)}</div></div>`}
function home(){reset.hidden=true;let last=null;try{last=JSON.parse(localStorage.getItem(STORE)||'null')}catch{}app.innerHTML=`<section class="hero"><div class="kicker">ESTIMATED RANK</div><h1>100人いたら<br>何位？</h1><p class="lead">行動・考え方の12問だけで、<strong>決断力・行動速度・メンタル耐久・切替力・主体性</strong>を100人中の順位にします。</p><div class="pills"><span class="pill">12問</span><span class="pill">約90秒</span><span class="pill">入力なし</span><span class="pill">結果カード共有</span></div><button class="primary" id="startBtn">順位を測る</button><div class="disclaimer" id="homeDisclaimer"><b>「推定」です。</b><br>実際の100人を測った統計ではありません。回答パターンを一定ルールで順位へ換算します。</div>${last?.overall?`<div class="previous">前回の推定：<strong>100人中 ${last.overall}位相当</strong>。回答が変わった今、もう一度測れます。</div>`:''}</section>`;document.getElementById('startBtn').onclick=()=>{index=0;answers=[];question()}}
function question(){reset.hidden=false;const q=Q[index],r=answers.length?rank(overall(scores())):50;app.innerHTML=`<div class="progress-wrap"><div class="progress-head"><span>QUESTION ${index+1} / ${Q.length}</span><span>${Math.round(index/Q.length*100)}%</span></div><div class="progress"><i style="width:${index/Q.length*100}%"></i></div></div><div class="live-rank"><div><small>回答中の暫定順位</small><strong id="liveRankText">100人中 ${r}位付近</strong></div><div class="move">答えるたび動く</div></div><section class="question-card"><div class="qnum">BEHAVIOR ${String(index+1).padStart(2,'0')}</div><h2 class="question">${esc(q[0])}</h2><div class="choices">${q[1].map((a,i)=>`<button class="choice" data-choice="${i}">${esc(a[0])}</button>`).join('')}</div>${crowdBlock(r,'暫定')}</section>`;app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(+b.dataset.choice,b))}
function answer(c,b){if(locked)return;locked=true;answers.push(c);b.classList.add('selected');navigator.vibrate?.(18);const r=rank(overall(scores()));document.getElementById('liveRankText').textContent=`100人中 ${r}位付近`;app.querySelector('.crowd').innerHTML=crowd(r);setTimeout(()=>{index++;locked=false;if(index<Q.length)question();else{const d=resultData();try{localStorage.setItem(STORE,JSON.stringify(d))}catch{}showResult(d,false)}},220)}
function traits(r){return Object.entries(DIMS).map(([k,d])=>`<div class="trait"><div class="trait-top"><span class="trait-name">${d.label}</span><span class="trait-rank">推定上位 <b>${r.dims[k]?.rank??50}</b>%</span></div><div class="trait-bar"><i style="width:${Math.max(12,101-(r.dims[k]?.rank??50))}%"></i></div><div class="trait-copy">${d.copy}</div></div>`).join('')}
function urlFor(r){return `${location.origin}${location.pathname}?r=${encodeURIComponent(encode(r))}`}
function showResult(r,shared){reset.hidden=false;const url=urlFor(r);app.innerHTML=`<div class="result-shell">${shared?'<div class="shared-tag">共有された推定結果</div>':''}<section class="rank-card"><div class="eyebrow">100 PEOPLE · ESTIMATED</div><h2>${shared?'この人の総合ポジション':'あなたの総合ポジション'}</h2><div class="overall"><span class="number" id="overallRank">${r.overall}</span><span class="suffix">位 / 100人 相当</span></div><div class="estimated-badge" id="estimatedBadge">推定上位 ${r.overall}%</div><p class="card-note">行動・考え方の回答を一定ルールで換算した推定。実測統計の順位ではありません。</p></section><section class="archetype"><small>あなたの出方</small><h3>${esc(r.archetype||'バランス型')}</h3><p>${esc(r.archetypeCopy||'複数の力を使い分けるタイプ。')}</p></section><div class="traits">${traits(r)}</div>${crowdBlock(r.overall,'総合')}<div class="result-disclaimer" id="resultDisclaimer"><b>この順位は推定です。</b> 全国調査・標準化検査・実際の100人との比較ではありません。回答選択をこのアプリ内の採点ルールで0〜100の位置へ換算しています。能力の優劣を断定するものではありません。</div>${shared?'<div class="result-actions"><button class="primary" id="mineBtn">自分も100人中何位か測る</button><button class="secondary" id="homeBtn">LEVEL UPへ戻る</button></div>':`<div class="result-actions"><button class="primary" id="shareBtn" data-url="${esc(url)}">結果を共有</button><button class="secondary" id="copyBtn">リンクをコピー</button></div><button class="secondary" id="againBtn">もう一度測る</button>`}</div>`;if(shared){mineBtn.onclick=()=>{history.replaceState({},'',location.pathname);home()};homeBtn.onclick=()=>location.href='/'}else{shareBtn.onclick=async()=>{const text=`「100人いたら何位？」で、私は100人中${r.overall}位相当（推定上位${r.overall}%）でした。あなたは？`;try{if(navigator.share)await navigator.share({title:'100人いたら何位？',text,url});else throw 0}catch(e){if(e?.name==='AbortError')return;copy(`${text}\n${url}`)}};copyBtn.onclick=()=>copy(url);againBtn.onclick=home}}
async function copy(v){try{await navigator.clipboard.writeText(v);const t=document.createElement('div');t.className='toast';t.textContent='リンクをコピーしました';document.body.appendChild(t);setTimeout(()=>t.remove(),1500)}catch{prompt('コピーしてください',v)}}
reset.onclick=()=>{history.replaceState({},'',location.pathname);home()};const token=new URLSearchParams(location.search).get('r'),shared=token&&decode(token);if(shared?.overall&&shared?.dims)showResult(shared,true);else home();
})();
