(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-idea-lenses-real-v1';
  const FAMILIES=[
    {id:'divide',name:'分ける',q:'人・工程・時間・場所・商品に分けたら、どこだけ動かせる？'},
    {id:'scale',name:'サイズを変える',q:'10分の1に小さくする／10倍に大きく考えると何が変わる？'},
    {id:'substitute',name:'替える',q:'人・道具・手順・素材・チャネルのどれかを替えるなら？'},
    {id:'combine',name:'くっつける',q:'今ある2つを組み合わせると、新しい打ち手になる？'},
    {id:'adapt',name:'借りる',q:'別業界・競合・過去の成功・身近な仕組みから何を借りられる？'},
    {id:'eliminate',name:'なくす',q:'工程・判断・入力・待ち時間を1つ消すなら？'},
    {id:'reverse',name:'逆にする',q:'順番・立場・前提・目的を逆にすると、何が見える？'},
    {id:'repurpose',name:'別用途にする',q:'今ある資源を本来と違う用途に使うなら？'}
  ];
  let modal,chosen=[],ideas=[],step=0;
  const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);

  function ensureLauncher(){const again=$('#againBtn');if(!again||$('[data-real-idea-launch]'))return;const b=document.createElement('button');b.type='button';b.className='real-idea-launch';b.dataset.realIdeaLaunch='1';b.textContent='今の問題を5方向から動かす →';b.addEventListener('click',open);again.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-idea-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-idea-card" role="dialog" aria-modal="true" aria-labelledby="realIdeaTitle">
    <div class="real-idea-head"><div><small>REAL LIFE / 5 LENS SPRINT</small><h2 id="realIdeaTitle">今の問題を、<br>5方向から動かす。</h2></div><button type="button" data-ri-close aria-label="閉じる">×</button></div>
    <section data-ri-step="input"><p>良い案を出す前に、違う方向を5回開く。</p><label><span>いま詰まっている問題</span><textarea data-ri-problem maxlength="180" placeholder="例：新サービスの2回目利用が増えない。"></textarea></label><div class="real-idea-meter"><div><span>いまの「打ち手が出ない」詰まり</span><strong><b data-ri-before-v>7</b>/10</strong></div><input data-ri-before type="range" min="0" max="10" value="7"></div><button class="real-idea-primary" data-ri-start type="button" disabled>5レンズを引く →</button></section>
    <section data-ri-step="sprint" hidden><div class="real-idea-progress"><span data-ri-count>1 / 5</span><div><i data-ri-bar></i></div></div><div class="real-idea-lens"><small data-ri-family-id>DIVIDE</small><h3 data-ri-family>分ける</h3><p data-ri-question></p></div><label><span>この方向なら、どんな案が出る？</span><textarea data-ri-idea maxlength="180" placeholder="60点の案でいい。1つ書く。"></textarea></label><button class="real-idea-primary" data-ri-next type="button" disabled>次のレンズ →</button></section>
    <section data-ri-step="choose" hidden><p>5案のうち、現実で最初に試す1つを選ぶ。</p><div class="real-idea-list" data-ri-list></div><div class="real-idea-meter"><div><span>5方向を見た後の詰まり</span><strong><b data-ri-after-v>7</b>/10</strong></div><input data-ri-after type="range" min="0" max="10" value="7"></div><small>下がらなくてもOK。案の数ではなく、次の一手が増えたかを見る。</small><button class="real-idea-primary" data-ri-finish type="button" disabled>この1手を残す</button></section>
    <section data-ri-step="done" hidden><h3 data-ri-done-title>5方向開いて、1手に絞った。</h3><div class="real-idea-picked"><small>TRY FIRST</small><strong data-ri-picked></strong></div><div class="real-idea-all" data-ri-all></div><div class="real-idea-delta" data-ri-delta></div><div class="real-idea-history" data-ri-history hidden></div><button class="real-idea-secondary" data-ri-again type="button">別の問題でもう1回</button></section>
  </div>`;document.body.appendChild(modal);
    $('[data-ri-close]',modal).onclick=close;$('[data-ri-problem]',modal).oninput=()=>{$('[data-ri-start]',modal).disabled=$('[data-ri-problem]',modal).value.trim().length<2};$('[data-ri-before]',modal).oninput=e=>$('[data-ri-before-v]',modal).textContent=e.target.value;$('[data-ri-after]',modal).oninput=e=>$('[data-ri-after-v]',modal).textContent=e.target.value;$('[data-ri-start]',modal).onclick=startSprint;$('[data-ri-idea]',modal).oninput=()=>{$('[data-ri-next]',modal).disabled=$('[data-ri-idea]',modal).value.trim().length<2};$('[data-ri-next]',modal).onclick=nextLens;$('[data-ri-finish]',modal).onclick=finish;$('[data-ri-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function show(n){$$('[data-ri-step]',modal).forEach(s=>s.hidden=s.dataset.riStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-ri-problem]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-idea-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-idea-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();chosen=[];ideas=[];step=0;$('[data-ri-problem]',modal).value='';$('[data-ri-idea]',modal).value='';$('[data-ri-before]',modal).value='7';$('[data-ri-after]',modal).value='7';$('[data-ri-before-v]',modal).textContent='7';$('[data-ri-after-v]',modal).textContent='7';$('[data-ri-start]',modal).disabled=true;$('[data-ri-next]',modal).disabled=true;show('input')}
  function startSprint(){chosen=shuffle(FAMILIES).slice(0,5);ideas=[];step=0;renderLens();show('sprint');try{window.LevelUpTelemetry?.step?.('real-idea-sprint')}catch{}}
  function renderLens(){const f=chosen[step];$('[data-ri-count]',modal).textContent=`${step+1} / 5`;$('[data-ri-bar]',modal).style.width=`${(step+1)/5*100}%`;$('[data-ri-family-id]',modal).textContent=f.id.toUpperCase();$('[data-ri-family]',modal).textContent=f.name;$('[data-ri-question]',modal).textContent=f.q;$('[data-ri-idea]',modal).value='';$('[data-ri-next]',modal).disabled=true;$('[data-ri-next]',modal).textContent=step===4?'5案を見る →':'次のレンズ →';requestAnimationFrame(()=>$('[data-ri-idea]',modal).focus({preventScroll:true}))}
  function nextLens(){const v=$('[data-ri-idea]',modal).value.trim();if(v.length<2)return;ideas.push({family:chosen[step],text:v});try{window.LevelUpTelemetry?.action?.(`real-idea-${chosen[step].id}`)}catch{};if(step<4){step++;renderLens();return}renderChoose()}
  function renderChoose(){let picked=-1;$('[data-ri-list]',modal).innerHTML=ideas.map((x,i)=>`<button type="button" data-ri-pick="${i}"><small>${x.family.name}</small><strong>${esc(x.text)}</strong><span>試す</span></button>`).join('');$$('[data-ri-pick]',modal).forEach(b=>b.onclick=()=>{picked=Number(b.dataset.riPick);$$('[data-ri-pick]',modal).forEach(x=>x.classList.toggle('selected',x===b));$('[data-ri-finish]',modal).disabled=false;$('[data-ri-finish]',modal).dataset.pick=String(picked)});const before=$('[data-ri-before]',modal).value;$('[data-ri-after]',modal).value=before;$('[data-ri-after-v]',modal).textContent=before;$('[data-ri-finish]',modal).disabled=true;show('choose')}
  function finish(){const idx=Number($('[data-ri-finish]',modal).dataset.pick);if(!Number.isInteger(idx)||!ideas[idx])return;const before=Number($('[data-ri-before]',modal).value),after=Number($('[data-ri-after]',modal).value),delta=before-after,pick=ideas[idx];$('[data-ri-picked]',modal).textContent=pick.text;$('[data-ri-all]',modal).innerHTML=ideas.map(x=>`<div><small>${x.family.name}</small><span>${esc(x.text)}</span></div>`).join('');$('[data-ri-done-title]',modal).textContent=delta>0?'詰まりが少しほどけた。次は1手だけ試す。':delta===0?'詰まりは同じ。でも5方向の候補はできた。':'少し重くなった。全部やらず、選んだ1手だけ試す。';$('[data-ri-delta]',modal).textContent=`打ち手の詰まり ${before} → ${after}　／　5方向展開`;save({delta,families:chosen.map(x=>x.id),picked:pick.family.id});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'idea-lenses-40',delta,picked:pick.family.id}}));window.LevelUpTelemetry?.complete?.('real-idea')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-ri-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const lighter=runs.filter(r=>Number(r.delta)>0).length;el.hidden=false;el.textContent=`現実スプリント ${runs.length}回。${lighter}回で詰まりが下がりました。`; }catch{}}
  ensureLauncher();
})();
