export const SCENARIOS = [
  {
    id: 'friday',
    title: 'いつもの金曜日',
    subtitle: '予定は多い。今日も、いつも通りの一日が始まる。',
    startHour: 6,
    heartGoals: ['family_dinner', 'call_friend', 'apology', 'dream'],
    saidGoals: ['call_friend', 'apology'],
    actions: [
      { id:'sleep', icon:'🌙', title:'ちゃんと寝る', duration:7, group:'care', inertia:0, heart:2, desc:'明日のために、身体を休める。' },
      { id:'work_deep', icon:'💻', title:'大事な仕事を仕上げる', duration:4, group:'duty', inertia:0, heart:2, desc:'ずっと気になっていた仕事を片づける。' },
      { id:'work_extra', icon:'📊', title:'頼まれていない資料も作る', duration:3, group:'duty', inertia:2, heart:0, desc:'念のため。なくても困らないが、やると安心する。' },
      { id:'mail', icon:'📨', title:'メールを全部ゼロにする', duration:2, group:'habit', inertia:2, heart:0, desc:'未読を残さず、受信箱をきれいにする。' },
      { id:'sns', icon:'📱', title:'なんとなくSNSを見る', duration:2, group:'habit', inertia:4, heart:0, desc:'目的はない。気づくと時間が過ぎる。' },
      { id:'news', icon:'📰', title:'ニュースを追い続ける', duration:1.5, group:'habit', inertia:3, heart:0, desc:'知らないと不安で、何度も更新する。' },
      { id:'family_dinner', icon:'🍲', title:'家族とゆっくりご飯を食べる', duration:2, group:'heart', inertia:0, heart:5, desc:'最近、同じ家にいてもゆっくり話せていない。' },
      { id:'call_friend', icon:'☎️', title:'会いたかった人に電話する', duration:1, group:'heart', inertia:0, heart:5, desc:'「落ち着いたら連絡する」と言ったままの人がいる。' },
      { id:'apology', icon:'✉️', title:'ずっと引っかかっていたことを謝る', duration:0.5, group:'heart', inertia:0, heart:5, desc:'言い訳ではなく、一言だけ伝えたい。' },
      { id:'dream', icon:'🎸', title:'やりたかったことを始める', duration:2, group:'heart', inertia:0, heart:5, desc:'上手くなくていい。最初の一歩だけやる。' },
      { id:'walk', icon:'🌇', title:'一人で散歩する', duration:1, group:'care', inertia:0, heart:3, desc:'何も生産しない時間を、あえて持つ。' },
      { id:'video', icon:'▶️', title:'おすすめ動画を見続ける', duration:2.5, group:'habit', inertia:4, heart:0, desc:'次の一本だけ、のはずが止まらない。' },
      { id:'clean', icon:'🧹', title:'部屋を完璧に片づける', duration:2, group:'habit', inertia:1, heart:1, desc:'気持ちはいい。でも今日じゃなくてもいい。' },
      { id:'favorite_meal', icon:'🍜', title:'大好きなものを食べに行く', duration:1.5, group:'heart', inertia:0, heart:4, desc:'ずっと「そのうち」と思っていた店へ。' },
      { id:'help', icon:'🤝', title:'困っている人を手伝う', duration:1.5, group:'heart', inertia:0, heart:4, desc:'目の前の人に、今できることをする。' },
    ]
  },
  {
    id: 'holiday',
    title: '予定のない休日',
    subtitle: '急ぎの仕事はない。自由な一日ほど、選択がむずかしい。',
    startHour: 8,
    heartGoals: ['visit_parent', 'photo', 'create', 'partner'],
    saidGoals: ['visit_parent', 'partner'],
    actions: [
      { id:'sleep', icon:'🌙', title:'十分に寝る', duration:8, group:'care', inertia:0, heart:3, desc:'寝不足を取り戻す。' },
      { id:'shopping', icon:'🛍️', title:'買い物サイトを眺める', duration:2, group:'habit', inertia:3, heart:0, desc:'欲しい物は特に決まっていない。' },
      { id:'series', icon:'📺', title:'ドラマを一気見する', duration:4, group:'habit', inertia:3, heart:1, desc:'楽しみではある。でも止め時を失いやすい。' },
      { id:'visit_parent', icon:'🚃', title:'しばらく会っていない家族に会う', duration:4, group:'heart', inertia:0, heart:5, desc:'会おうと思えば会える距離。でも先延ばししていた。' },
      { id:'photo', icon:'🖼️', title:'昔の写真を一緒に見る', duration:1.5, group:'heart', inertia:0, heart:4, desc:'忘れていた話が、たくさん出てくる。' },
      { id:'create', icon:'🖌️', title:'作りたかったものを作る', duration:3, group:'heart', inertia:0, heart:5, desc:'完成しなくていい。手を動かす。' },
      { id:'partner', icon:'☕', title:'大切な人と何もせず話す', duration:2, group:'heart', inertia:0, heart:5, desc:'用事ではなく、ただ話す。' },
      { id:'gym', icon:'🏃', title:'身体を動かす', duration:1.5, group:'care', inertia:0, heart:3, desc:'身体が軽くなるくらいでやめる。' },
      { id:'chores', icon:'🧺', title:'家事を全部片づける', duration:3, group:'duty', inertia:1, heart:1, desc:'必要ではある。ただ、全部今日でなくてもいい。' },
      { id:'game', icon:'🎮', title:'好きなゲームで遊ぶ', duration:2, group:'care', inertia:0, heart:3, desc:'本当に遊びたいなら、それも大事な時間。' },
      { id:'sns', icon:'📱', title:'タイムラインを眺める', duration:2, group:'habit', inertia:4, heart:0, desc:'目的なく指を動かす。' },
      { id:'nap', icon:'🛋️', title:'昼寝する', duration:1, group:'care', inertia:0, heart:2, desc:'眠いなら眠る。' },
    ]
  },
  {
    id: 'courage',
    title: '言えないままの一日',
    subtitle: '失敗したくない。嫌われたくない。だから、今日も保留にしている。',
    startHour: 7,
    heartGoals: ['confess', 'quit', 'publish', 'thanks'],
    saidGoals: ['confess', 'quit', 'thanks'],
    actions: [
      { id:'sleep', icon:'🌙', title:'寝る', duration:7, group:'care', inertia:0, heart:2, desc:'今日を終えるためにも休息は必要。' },
      { id:'research', icon:'🔎', title:'もっと調べてから決める', duration:3, group:'habit', inertia:3, heart:0, desc:'情報は十分ある。でも決めるのが怖い。' },
      { id:'prepare', icon:'📚', title:'完璧な準備をする', duration:3, group:'habit', inertia:2, heart:1, desc:'失敗しない準備には終わりがない。' },
      { id:'confess', icon:'💬', title:'本当の気持ちを伝える', duration:1, group:'heart', inertia:0, heart:5, desc:'結果は選べない。でも言うことは選べる。' },
      { id:'quit', icon:'🚪', title:'やめたいことをやめると伝える', duration:1, group:'heart', inertia:0, heart:5, desc:'惰性だけで続けてきたことがある。' },
      { id:'publish', icon:'🚀', title:'作ったものを公開する', duration:1, group:'heart', inertia:0, heart:5, desc:'60点でも、世に出す。' },
      { id:'thanks', icon:'🙏', title:'感謝を言葉にする', duration:0.5, group:'heart', inertia:0, heart:5, desc:'思っているだけでは、伝わらない。' },
      { id:'overtime', icon:'🏢', title:'誰にも頼まれていない残業をする', duration:4, group:'duty', inertia:3, heart:0, desc:'帰る理由がないから残る。' },
      { id:'scroll', icon:'📱', title:'他人の人生を見る', duration:2, group:'habit', inertia:4, heart:0, desc:'自分の決断をしないまま、他人の投稿を見る。' },
      { id:'walk', icon:'🌃', title:'夜の街を歩く', duration:1, group:'care', inertia:0, heart:3, desc:'答えを出さずに、身体だけ動かす。' },
      { id:'friend', icon:'🍻', title:'友人と会う', duration:2, group:'heart', inertia:0, heart:4, desc:'用事がなくても会いたい人がいる。' },
    ]
  }
];
