const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const fmt=new Intl.NumberFormat('ja-JP');
const state={age:40,end:90,parentPerYear:12,choice:null};
const refs={ageRange:$('#ageRange'),ageValue:$('#ageValue'),spring:$('#springCount'),sat:$('#saturdayCount'),birthday:$('#birthdayCount'),summer:$('#summerCount'),yearEnd:$('#yearEndCount'),parent:$('#parentCount'),meter:$('#meterFill'),assumption:$('#assumptionCopy'),choiceSection:$('#choiceSection'),resultSection:$('#resultSection'),shareStatus:$('#shareStatus')};
function years(){return Math.max(0,state.end-state.age)}
function counts(){const y=years();return{spring:y,saturday:Math.round(y*365.2425/7),birthday:y,summer:y,yearEnd:y,parent:Math.round(y*state.parentPerYear)}}
function setRangePaint(){const min=+refs.ageRange.min,max=+refs.ageRange.max,p=((state.age-min)/(max-min))*100;refs.ageRange.style.background=`linear-gradient(90deg,var(--dark) ${p}%,#dfe4d0 ${p}%)`}
function bump(el){el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump')}
function render(){if(state.age>=state.end){state.end=Math.min(100,state.age<90?90:100);$$('#endAgeButtons button').forEach(b=>b.classList.toggle('active',+b.dataset.end===state.end))}const c=counts();refs.ageValue.textContent=state.age;refs.spring.textContent=fmt.format(c.spring);refs.sat.textContent=fmt.format(c.saturday);refs.birthday.textContent=fmt.format(c.birthday);refs.summer.textContent=fmt.format(c.summer);refs.yearEnd.textContent=fmt.format(c.yearEnd);refs.parent.textContent=fmt.format(c.parent);refs.assumption.textContent=`${state.end}歳まで生きると仮定して`;refs.meter.style.width=`${Math.max(0,Math.min(100,(years()/Math.max(1,state.end-10))*100))}%`;$('#choiceSpring').textContent=`あと${fmt.format(c.spring)}回`;$('#choiceSaturday').textContent=`あと${fmt.format(c.saturday)}回`;$('#choiceBirthday').textContent=`あと${fmt.format(c.birthday)}回`;$('#choiceParent').textContent=`あと${fmt.format(c.parent)}回`;setRangePaint();if(state.choice)renderResult();}
function getChoiceCount(source){return counts()[source]??0}
function choose(btn){state.choice={label:btn.dataset.choice,source:btn.dataset.source};renderResult();refs.resultSection.hidden=false;refs.choiceSection.hidden=true;localStorage.setItem('ato-nankai-last',JSON.stringify({choice:state.choice.label,date:new Date().toISOString(),age:state.age,end:state.end}));refs.resultSection.scrollIntoView({behavior:'smooth',block:'start'})}
function renderResult(){if(!state.choice)return;const c=counts();$('#resultAssumption').textContent=`${state.age}歳 → ${state.end}歳と仮定`;$('#resultChoice').textContent=state.choice.label;$('#resultCount').textContent=fmt.format(getChoiceCount(state.choice.source));$('#resultSpring').textContent=fmt.format(c.spring);$('#resultSaturday').textContent=fmt.format(c.saturday);$('#resultParent').textContent=fmt.format(c.parent)}
function shareText(){const c=counts();return`人生、あと何回？\n${state.age}歳 → ${state.end}歳と仮定\n春 あと約${fmt.format(c.spring)}回\n土曜日 あと約${fmt.format(c.saturday)}回\n大切な人に会う あと約${fmt.format(c.parent)}回\n\n今日、雑にしない1回：${state.choice?.label||'—'}\nhttps://levelup.hitobito.jp/apps/ato-nankai/`}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function canvasBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,'image/png',.95))}
async function makeShareFile(){const canvas=$('#shareCanvas'),ctx=canvas.getContext('2d'),c=counts();ctx.clearRect(0,0,1080,1350);ctx.fillStyle='#c9ff45';ctx.fillRect(0,0,1080,1350);ctx.fillStyle='#151713';ctx.font='900 54px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText('人生、あと何回？',76,110);ctx.font='700 26px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillStyle='#4e573b';ctx.fillText(`${state.age}歳 → ${state.end}歳までと仮定`,76,158);ctx.fillStyle='#151713';ctx.font='800 26px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText('今日、雑にしない1回',76,315);ctx.font='950 104px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText(state.choice?.label||'今日',76,430);ctx.font='900 36px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText(`あと 約${fmt.format(getChoiceCount(state.choice?.source))}回`,76,500);ctx.fillStyle='rgba(21,23,19,.09)';roundRect(ctx,76,590,928,320,34);ctx.fillStyle='#151713';ctx.font='800 25px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText('残り回数',120,655);ctx.font='950 48px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText(`春  ${fmt.format(c.spring)}`,120,742);ctx.fillText(`土曜日  ${fmt.format(c.saturday)}`,120,815);ctx.fillText(`会う時間  ${fmt.format(c.parent)}`,120,888);ctx.font='700 25px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillStyle='#4e573b';ctx.fillText('数を減らすためではなく、残っている1回を大切にする。',76,1065);ctx.fillStyle='#151713';ctx.font='900 27px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText('LEVEL UP',76,1245);ctx.font='700 22px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic",sans-serif';ctx.fillText('levelup.hitobito.jp',76,1285);const blob=await canvasBlob(canvas);return new File([blob],'ato-nankai.png',{type:'image/png'})}
async function share(){refs.shareStatus.textContent='';try{const file=await makeShareFile();if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({title:'人生、あと何回？',text:'今日、大切にする1回を決めました。',url:'https://levelup.hitobito.jp/apps/ato-nankai/',files:[file]});refs.shareStatus.textContent='シェア画面を開きました';return}if(navigator.share){await navigator.share({title:'人生、あと何回？',text:shareText(),url:'https://levelup.hitobito.jp/apps/ato-nankai/'});return}await navigator.clipboard.writeText(shareText());refs.shareStatus.textContent='結果をコピーしました';}catch(e){if(e?.name!=='AbortError'){refs.shareStatus.textContent='シェアできなかったため、コピーをお試しください'}}}
async function copy(){try{await navigator.clipboard.writeText(shareText());refs.shareStatus.textContent='結果をコピーしました';}catch{refs.shareStatus.textContent='コピーできませんでした'}}
function restorePrevious(){try{const v=JSON.parse(localStorage.getItem('ato-nankai-last')||'null');if(!v)return;$('#revisitBox').hidden=false;$('#previousChoice').textContent=v.choice;$('#previousDate').textContent=`${new Date(v.date).toLocaleDateString('ja-JP')} に選択`;}catch{}}
refs.ageRange.addEventListener('input',e=>{state.age=+e.target.value;bump(refs.spring);render()});$$('#endAgeButtons button').forEach(btn=>btn.addEventListener('click',()=>{state.end=+btn.dataset.end;$$('#endAgeButtons button').forEach(b=>b.classList.toggle('active',b===btn));render()}));$$('#parentFrequency button').forEach(btn=>btn.addEventListener('click',()=>{state.parentPerYear=+btn.dataset.perYear;$$('#parentFrequency button').forEach(b=>b.classList.toggle('active',b===btn));render()}));$$('#choiceGrid button').forEach(btn=>btn.addEventListener('click',()=>choose(btn)));$('#backBtn').addEventListener('click',()=>{refs.resultSection.hidden=true;refs.choiceSection.hidden=false;state.choice=null;refs.choiceSection.scrollIntoView({behavior:'smooth'})});$('#shareBtn').addEventListener('click',share);$('#copyBtn').addEventListener('click',copy);$('#resetBtn').addEventListener('click',()=>{state.age=40;state.end=90;state.parentPerYear=12;state.choice=null;refs.ageRange.value=40;$$('#endAgeButtons button').forEach(b=>b.classList.toggle('active',+b.dataset.end===90));$$('#parentFrequency button').forEach(b=>b.classList.toggle('active',+b.dataset.perYear===12));refs.resultSection.hidden=true;refs.choiceSection.hidden=false;render();scrollTo({top:0,behavior:'smooth'})});render();restorePrevious();
