(()=>{'use strict';
if(!window.THREE){document.getElementById('intro').style.display='none';document.getElementById('loaderError').style.display='flex';return}
const T=THREE,C=T.MathUtils.clamp,L=T.MathUtils.lerp,clock=new T.Clock();
const state={started:false,inWater:false,transition:false,reveal:false,peak:false,yaw:0,pitch:0,vel:new T.Vector3(),keys:{},touch:new T.Vector2(),t:0,phase:0,ready:false};
const $=id=>document.getElementById(id),ui={intro:$('intro'),start:$('start'),hud:$('hud'),ret:$('reticle'),prompt:$('prompt'),obj:$('objective'),depth:document.querySelector('#depth b'),chapter:$('chapter'),flash:$('flash'),action:$('action'),stick:$('stick'),nub:$('nub'),look:$('lookPad')};
const scene=new T.Scene();scene.background=new T.Color(0x02070b);scene.fog=new T.FogExp2(0x06131a,.024);
const camera=new T.PerspectiveCamera(68,innerWidth/innerHeight,.06,160);camera.position.set(0,1.72,18.5);camera.rotation.order='YXZ';
const r=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});r.setSize(innerWidth,innerHeight);r.setPixelRatio(Math.min(devicePixelRatio,1.7));r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.06;r.shadowMap.enabled=true;r.shadowMap.type=T.PCFSoftShadowMap;document.body.insertBefore(r.domElement,$('ui'));
function tex(n,fn){const c=document.createElement('canvas');c.width=c.height=n;const x=c.getContext('2d');fn(x,n);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t}
const stone=tex(256,(x,n)=>{x.fillStyle='#11191d';x.fillRect(0,0,n,n);for(let i=0;i<4000;i++){let v=12+Math.random()*28;x.fillStyle=`rgba(${v},${v+5},${v+8},${Math.random()*.2})`;x.fillRect(Math.random()*n,Math.random()*n,2,2)}});stone.repeat.set(6,10);
const armor=tex(256,(x,n)=>{let g=x.createRadialGradient(95,80,5,130,130,180);g.addColorStop(0,'#7b8376');g.addColorStop(.5,'#485047');g.addColorStop(1,'#171e1b');x.fillStyle=g;x.fillRect(0,0,n,n);for(let i=0;i<900;i++){x.fillStyle=Math.random()>.5?'#ffffff10':'#00000018';x.fillRect(Math.random()*n,Math.random()*n,1+Math.random()*2,1+Math.random()*2)}});
const floor=new T.MeshPhysicalMaterial({color:0x11191d,map:stone,roughness:.28,metalness:.38,clearcoat:.55}),wall=new T.MeshStandardMaterial({color:0x091115,roughness:.82,metalness:.15}),metal=new T.MeshStandardMaterial({color:0x202c31,roughness:.32,metalness:.76}),black=new T.MeshStandardMaterial({color:0x070d10,roughness:.42,metalness:.7});
function mesh(g,m,p,grp=scene){const o=new T.Mesh(g,m);o.position.set(...p);o.receiveShadow=true;grp.add(o);return o}function box(w,h,d,m,x,y,z,g=scene){return mesh(new T.BoxGeometry(w,h,d),m,[x,y,z],g)}
const hall=new T.Group();scene.add(hall);box(18,.22,39,floor,0,-.11,5,hall);box(18,.35,39,black,0,7.4,5,hall);box(.5,7.6,39,wall,-9,3.7,5,hall);box(.5,7.6,39,wall,9,3.7,5,hall);
for(let z=20;z>=-13;z-=3.6){box(17.2,.2,.32,metal,0,7,z,hall);box(.2,6.7,.32,metal,-8.45,3.4,z,hall);box(.2,6.7,.32,metal,8.45,3.4,z,hall)}
function sign(title,sub,accent='#79ddf2'){const c=document.createElement('canvas');c.width=640;c.height=180;let x=c.getContext('2d');x.fillStyle='#031016cc';x.fillRect(0,0,640,180);x.strokeStyle='#84dcf044';x.strokeRect(2,2,636,176);x.fillStyle=accent;x.font='500 50px Arial';x.fillText(title,30,78);x.fillStyle='#d5f4f999';x.font='26px Arial';x.fillText(sub,31,126);let t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;let s=new T.Sprite(new T.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.3,1.21,1);return s}
[['CAMBRIAN','541 MA'],['ORDOVICIAN','485 MA'],['JURASSIC','201 MA'],['CRETACEOUS','100 MA'],['CENOZOIC','23 MA']].forEach((e,i)=>{let side=i%2?1:-1,z=14-i*5.7;box(4.6,3.7,.28,black,side*7.25,2.05,z,hall);let s=sign(e[0],`${e[1]} · ARCHIVE LOCKED`,'#738d95');s.position.set(side*6.8,4.8,z);s.rotation.y=side<0?Math.PI/2:-Math.PI/2;hall.add(s)});
const strip=new T.MeshBasicMaterial({color:0x5fdff7,transparent:true,opacity:.72});for(let z=17;z>-11;z-=5.2){box(4.2,.035,.06,strip,-5.8,.05,z,hall);box(4.2,.035,.06,strip,5.8,.05,z,hall)}
const front=-12.6;box(16.1,6.7,.48,black,0,3.4,front-.35,hall);const glass=mesh(new T.PlaneGeometry(14.85,5.75),new T.MeshPhysicalMaterial({color:0x75dcec,transparent:true,opacity:.11,roughness:.05,transmission:.42,thickness:.7,side:T.DoubleSide,depthWrite:false}),[0,3.35,front+.03],hall);let ms=sign('DEVONIAN','382 MA · MACROVERTEBRATE OCEAN','#8eeaff');ms.position.set(0,6.65,-12.1);ms.scale.set(5.6,1.58,1);hall.add(ms);
const marker=mesh(new T.RingGeometry(.42,.47,64),new T.MeshBasicMaterial({color:0x74eaff,transparent:true,opacity:.35,side:T.DoubleSide}),[0,.02,-8.1],hall);marker.rotation.x=-Math.PI/2;
function visitor(x,z,h=1.7){let g=new T.Group(),m=new T.MeshStandardMaterial({color:0x0a1012,roughness:.9});mesh(new T.CapsuleGeometry(.18,.82,4,8),m,[0,h*.55,0],g);mesh(new T.SphereGeometry(.16,12,8),m,[0,h*1.02,0],g);g.position.set(x,0,z);hall.add(g);return g}visitor(-4.7,-7.4);visitor(4.2,-6.7,1.62);visitor(6.1,-9,1.78);
const tank=new T.Group();scene.add(tank);box(30,12,34,new T.MeshStandardMaterial({color:0x062c38,roughness:.72,transparent:true,opacity:.76,side:T.BackSide}),0,4,-30.5,tank);box(30,.3,34,new T.MeshStandardMaterial({color:0x172b2b,roughness:1}),0,-1.15,-30.5,tank);const surface=mesh(new T.PlaneGeometry(30,34),new T.MeshPhysicalMaterial({color:0x55c5d8,transparent:true,opacity:.16,roughness:.16,side:T.DoubleSide,depthWrite:false}),[0,9.7,-30.5],tank);surface.rotation.x=Math.PI/2;
for(let i=0;i<30;i++){let sc=.4+Math.random()*1.6,o=mesh(new T.DodecahedronGeometry(sc,0),new T.MeshStandardMaterial({color:i%3?0x263d3a:0x38463b,roughness:.95}),[(Math.random()-.5)*25,-.65+Math.random()*.25,-18-Math.random()*25],tank);o.scale.y=.5+Math.random()*.8;o.rotation.set(Math.random(),Math.random(),Math.random())}
for(let i=0;i<7;i++){let beam=mesh(new T.ConeGeometry(.9+Math.random()*.8,12,18,1,true),new T.MeshBasicMaterial({color:0x63d9ef,transparent:true,opacity:.022,side:T.DoubleSide,depthWrite:false}),[-10+i*3.4,4.5,-27-Math.random()*8],tank);beam.rotation.z=(Math.random()-.5)*.18}
const plankGeo=new T.BufferGeometry(),pa=new Float32Array(1500*3);for(let i=0;i<pa.length;i+=3){pa[i]=(Math.random()-.5)*28;pa[i+1]=-1+Math.random()*11;pa[i+2]=-14-Math.random()*33}plankGeo.setAttribute('position',new T.BufferAttribute(pa,3));const plank=new T.Points(plankGeo,new T.PointsMaterial({color:0x9befff,size:.025,transparent:true,opacity:.48,depthWrite:false}));tank.add(plank);
function fishModel(scale=.35,col=0x7fa4a5){let g=new T.Group(),m=new T.MeshStandardMaterial({color:col,roughness:.5,metalness:.12});let body=mesh(new T.SphereGeometry(1,14,8),m,[0,0,0],g);body.scale.set(1.8,.55,.5);let tail=mesh(new T.ConeGeometry(.55,1.15,3),m,[-1.9,0,0],g);tail.rotation.z=-Math.PI/2;g.scale.setScalar(scale);return g}
const schools=[];[[24,-23,3,.33],[17,-31,5,.27],[12,-38,2,.44]].forEach((cfg,s)=>{let a=[];for(let i=0;i<cfg[0];i++){let f=fishModel(cfg[3],s===2?0x9c8464:0x73979a);f.position.set((Math.random()-.5)*13,cfg[2]+(Math.random()-.5)*3,cfg[1]+(Math.random()-.5)*5);f.userData={base:f.position.clone(),phase:Math.random()*6.28,speed:.25+Math.random()*.22};tank.add(f);a.push(f)}schools.push(a)});
function dunkleosteus(scale=1){let g=new T.Group(),skin=new T.MeshStandardMaterial({color:0x485149,map:armor,roughness:.58,metalness:.12}),plate=new T.MeshStandardMaterial({color:0x5e665c,map:armor,roughness:.48}),jawMat=new T.MeshStandardMaterial({color:0xc2bba0,roughness:.5});let body=mesh(new T.SphereGeometry(1,28,18),skin,[0,0,0],g);body.scale.set(4.8,1.28,1.35);let shoulder=mesh(new T.SphereGeometry(1,24,16),plate,[3.2,.05,0],g);shoulder.scale.set(2.2,1.55,1.48);let head=mesh(new T.BoxGeometry(2.7,1.9,2.35),plate,[5.05,.18,0],g);head.rotation.z=-.04;let snout=mesh(new T.BoxGeometry(1.2,1.25,2.1),plate,[6.65,.08,0],g);snout.rotation.z=.06;const lower=new T.Group();lower.position.set(6.15,-.45,0);g.add(lower);mesh(new T.BoxGeometry(2.35,.38,1.95),plate,[.2,0,0],lower);let blade=mesh(new T.ConeGeometry(.45,1.7,3),jawMat,[.42,.26,.68],lower);blade.rotation.z=-Math.PI/2;let blade2=blade.clone();blade2.position.z=-.68;lower.add(blade2);for(let z of [-.72,.72]){mesh(new T.SphereGeometry(.14,12,8),new T.MeshBasicMaterial({color:0xd9f4d3}),[6.05,.58,z],g);mesh(new T.SphereGeometry(.065,10,6),new T.MeshBasicMaterial({color:0x050505}),[6.14,.59,z],g)}let tail=mesh(new T.ConeGeometry(1.0,5.6,14),skin,[-6.1,0,0],g);tail.rotation.z=-Math.PI/2;let fin=mesh(new T.ConeGeometry(1.5,2.3,3),skin,[-8.7,0,0],g);fin.rotation.z=-Math.PI/2;g.userData={lower,tail,fin};g.scale.setScalar(scale);return g}
const dunk=dunkleosteus(.86);dunk.position.set(-19,2.5,-25);tank.add(dunk);const shadow=dunkleosteus(.72);shadow.position.set(14,5,-40);shadow.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.color?.multiplyScalar(.22)}});tank.add(shadow);
scene.add(new T.HemisphereLight(0x5ab6ca,0x071014,.8));const key=new T.DirectionalLight(0xbcefff,1.1);key.position.set(-5,9,8);scene.add(key);const spot=new T.SpotLight(0x56dff8,28,55,.58,.7,1);spot.position.set(-4,8,-8);spot.target.position.set(0,2,-28);scene.add(spot,spot.target);const rim=new T.PointLight(0x3ce1ff,13,26,2);rim.position.set(0,5,-16);scene.add(rim);for(let z=17;z>-9;z-=5.5){let p=new T.PointLight(0x4cb8ce,1.8,9,2);p.position.set(z%2?5:-5,5.7,z);scene.add(p)}
let audio=null;function initAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)();let gain=audio.createGain();gain.gain.value=.075;gain.connect(audio.destination);let osc=audio.createOscillator();osc.type='sine';osc.frequency.value=44;osc.connect(gain);osc.start();let n=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate),a=n.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*.12;let src=audio.createBufferSource();src.buffer=n;src.loop=true;let ng=audio.createGain();ng.gain.value=.12;src.connect(ng);ng.connect(gain);src.start()}
function ping(freq=420,vol=.04,d=.35){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}function impact(){ping(58,.16,1.4);ping(91,.08,.9)}
addEventListener('keydown',e=>{state.keys[e.code]=true;if(e.code==='KeyE'&&state.ready)startDive()});addEventListener('keyup',e=>state.keys[e.code]=false);r.domElement.addEventListener('click',()=>{if(state.started&&!state.inWater&&!state.transition&&matchMedia('(pointer:fine)').matches)r.domElement.requestPointerLock?.()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==r.domElement||state.transition)return;state.yaw-=e.movementX*.0022;state.pitch=C(state.pitch-e.movementY*.002,-1.3,1.3)});
let sid=null,so={x:0,y:0};ui.stick.addEventListener('pointerdown',e=>{sid=e.pointerId;ui.stick.setPointerCapture(sid);so={x:e.clientX,y:e.clientY}});ui.stick.addEventListener('pointermove',e=>{if(e.pointerId!==sid)return;let dx=e.clientX-so.x,dy=e.clientY-so.y,l=Math.max(1,Math.hypot(dx,dy)),q=Math.min(1,37/l),x=dx*q,y=dy*q;ui.nub.style.transform=`translate(${x}px,${y}px)`;state.touch.set(x/37,y/37)});function sr(e){if(e.pointerId!==sid)return;sid=null;state.touch.set(0,0);ui.nub.style.transform='translate(0,0)'}ui.stick.addEventListener('pointerup',sr);ui.stick.addEventListener('pointercancel',sr);let lid=null,last=new T.Vector2();ui.look.addEventListener('pointerdown',e=>{lid=e.pointerId;ui.look.setPointerCapture(lid);last.set(e.clientX,e.clientY)});ui.look.addEventListener('pointermove',e=>{if(e.pointerId!==lid||state.transition)return;state.yaw-=(e.clientX-last.x)*.004;state.pitch=C(state.pitch-(e.clientY-last.y)*.0036,-1.3,1.3);last.set(e.clientX,e.clientY)});ui.look.addEventListener('pointerup',e=>{if(e.pointerId===lid)lid=null});ui.action.addEventListener('click',e=>{e.stopPropagation();if(state.ready)startDive()});
ui.start.addEventListener('click',()=>{initAudio();state.started=true;ui.intro.classList.add('hide');ui.hud.classList.add('on');setTimeout(()=>chapter('EARTH OCEAN ARCHIVE','DEVONIAN WING','382,000,000 YEARS BEFORE PRESENT'),500);setTimeout(()=>matchMedia('(pointer:fine)').matches&&r.domElement.requestPointerLock?.(),900)});
const fw=new T.Vector3(),rt=new T.Vector3();function player(dt){if(!state.started||state.transition)return;camera.rotation.y=state.yaw;camera.rotation.x=state.pitch;let f=(state.keys.KeyW?1:0)-(state.keys.KeyS?1:0)-state.touch.y,q=(state.keys.KeyD?1:0)-(state.keys.KeyA?1:0)+state.touch.x,run=state.keys.ShiftLeft||state.keys.ShiftRight,speed=state.inWater?(run?4.5:2.6):(run?6.1:3.55);fw.set(Math.sin(state.yaw),0,-Math.cos(state.yaw));rt.set(Math.cos(state.yaw),0,Math.sin(state.yaw));let w=new T.Vector3().addScaledVector(fw,f).addScaledVector(rt,q);if(w.lengthSq())w.normalize().multiplyScalar(speed);if(state.inWater){w.y=(state.keys.Space?1:0)-(state.keys.ShiftLeft?1:0)*2;state.vel.lerp(w,1-Math.pow(.0015,dt));camera.position.addScaledVector(state.vel,dt);camera.position.x=C(camera.position.x,-13,13);camera.position.y=C(camera.position.y,-.1,8.5);camera.position.z=C(camera.position.z,-45,-14.1);ui.depth.textContent=`${Math.max(0,3.8-camera.position.y).toFixed(1)} m`}else{state.vel.lerp(w,1-Math.pow(.001,dt));camera.position.x+=state.vel.x*dt;camera.position.z+=state.vel.z*dt;camera.position.x=C(camera.position.x,-7.7,7.7);camera.position.z=C(camera.position.z,-10.35,20.4);camera.position.y=1.72}}
function animateFish(t){schools.forEach((a,s)=>a.forEach((f,i)=>{let d=f.userData,p=d.phase+t*d.speed,amp=s?3.4:2.7;f.position.x=d.base.x+Math.sin(p+i*.3)*amp;f.position.y=d.base.y+Math.sin(p*1.3+i)*.45;f.position.z=d.base.z+Math.cos(p*.8+i*.15)*1.4;f.rotation.y=Math.atan2(Math.cos(p)*amp*d.speed,Math.sin(p*.8)*1.1)-Math.PI/2}));plank.rotation.y=t*.009;surface.material.opacity=.15+Math.sin(t*.45)*.025}
function predator(t,dt){if(!state.inWater&&camera.position.z<1.5&&!state.reveal){state.reveal=true;state.phase=0;ping(160,.06,1.2);ui.obj.innerHTML='<strong>Something is moving in the dark</strong>水槽から目を離さず、展示窓へ近づく。'}if(state.reveal&&!state.inWater){state.phase=Math.min(1,state.phase+dt*.13);let q=state.phase,e=q<.72?1-Math.pow(1-q/.72,2):1;dunk.position.set(L(-19,-1.2,e),2.5+Math.sin(t*.38)*.32,L(-25,-16.6,e));dunk.rotation.y=L(-.1,-.32,e);if(q>.56&&!state.peak){state.peak=true;impact();ui.obj.innerHTML='<strong>DUNKLEOSTEUS · ARTHRODIRE</strong>装甲魚類の巨大捕食者。さらに近づけば時代そのものへ入れる。'}}else if(state.inWater){let u=t*.13;dunk.position.set(Math.sin(u)*9,2.8+Math.sin(t*.29)*1.2,-27+Math.cos(u)*8);dunk.rotation.y=Math.atan2(Math.cos(u)*9,Math.sin(u)*8)-Math.PI/2}let j=dunk.userData.lower;j.rotation.z=-.05-Math.max(0,Math.sin(t*.7))*.09;dunk.userData.tail.rotation.z=-Math.PI/2+Math.sin(t*1.15)*.075;dunk.userData.fin.rotation.z=-Math.PI/2+Math.sin(t*1.15+.65)*.16;shadow.position.x=12+Math.sin(t*.08)*5}
function interact(){if(state.inWater){state.ready=false;ui.prompt.classList.remove('show');ui.ret.classList.remove('hot');ui.action.classList.remove('show');return}let d=Math.hypot(camera.position.x,camera.position.z+8.15),ready=d<2.15&&state.peak;if(ready!==state.ready){state.ready=ready;ui.prompt.classList.toggle('show',ready);ui.ret.classList.toggle('hot',ready);ui.action.classList.toggle('show',ready);if(ready)ping(520,.035,.34)}marker.material.opacity=.24+Math.sin(state.t*2.8)*.12}
function chapter(a,b,c){let e=ui.chapter;e.querySelector('.small').textContent=a;e.querySelector('.big').textContent=b;e.querySelector('.sub').textContent=c;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
function startDive(){if(state.transition||state.inWater)return;state.transition=true;state.ready=false;ui.prompt.classList.remove('show');ui.action.classList.remove('show');document.exitPointerLock?.();let p=camera.position.clone(),y=state.yaw,pi=state.pitch,start=performance.now();impact();function go(now){let u=C((now-start)/3200,0,1),e=u*u*(3-2*u),f=Math.max(0,1-Math.abs(u-.72)*7);camera.position.lerpVectors(p,new T.Vector3(0,3,-16.8),e);state.yaw=L(y,0,e);state.pitch=L(pi,-.03,e);camera.rotation.set(state.pitch,state.yaw,0);ui.flash.style.opacity=String(f*.72);r.toneMappingExposure=1.06+f*.7;if(u<1)requestAnimationFrame(go);else{ui.flash.style.opacity='0';r.toneMappingExposure=.94;state.inWater=true;state.transition=false;scene.fog.density=.046;scene.background.set(0x03181f);camera.position.set(0,3,-17.2);state.vel.set(0,0,0);ui.obj.innerHTML='<strong>You are inside the archive</strong>泳いで観察する。WASD 移動 · SPACE 上昇 · SHIFT 下降。';chapter('TEMPORAL ENTRY COMPLETE','DEVONIAN SEA','382,000,000 YEARS BEFORE PRESENT');setTimeout(()=>matchMedia('(pointer:fine)').matches&&r.domElement.requestPointerLock?.(),500)}}requestAnimationFrame(go)}
function loop(){requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.04);state.t+=dt;player(dt);animateFish(state.t);predator(state.t,dt);interact();spot.intensity=27+Math.sin(state.t*.7)*2.5;rim.intensity=12+Math.sin(state.t*1.9)*1.5;glass.material.opacity=.105+Math.sin(state.t*.32)*.012;r.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();r.setSize(innerWidth,innerHeight);r.setPixelRatio(Math.min(devicePixelRatio,1.7))});loop();
})();
