const scenarios=[
 {k:'PROJECT 01',t:'新サービスの企画、まだ穴がある。',s:'会議まで残り1日。完璧な資料にするには、あと3日ほしい。',c:[['60点版を見せる','仮説を3つに絞り、反応をもらう。','ship',14,16,-2],['徹夜で100点を狙う','見栄えまで整えるが、検証はできない。','perfect',5,1,14],['まだ出さない','情報不足を理由に次回へ送る。','wait',0,0,8]]},
 {k:'PROJECT 02',t:'試作品のボタンが少し不格好。',s:'主要機能は動く。ユーザーの感想を聞ける状態にはなっている。',c:[['5人に触ってもらう','不格好なまま、迷う場所を観察する。','ship',15,18,-2],['デザインを全面修正','反応を見る前に色と余白を作り込む。','perfect',4,2,13],['恥ずかしいので隠す','完成するまで存在を知らせない。','wait',0,0,9]]},
 {k:'PROJECT 03',t:'最初の投稿に自信がない。',s:'内容は伝わる。ただし、もっと良い言い回しがありそうだ。',c:[['今の文章で公開','反応の弱い箇所を次で直す。','ship',12,14,-1],['20回推敲する','誰にも見せず、言葉だけを磨き続ける。','perfect',3,1,12],['下書きに戻す','失敗しない代わりに何も起こらない。','wait',0,0,8]]},
 {k:'PROJECT 04',t:'お客さんから厳しい指摘が来た。',s:'試作品を早く出したからこそ、致命的な勘違いが今わかった。',c:[['指摘を反映して再公開','失敗を修正材料に変えて2周目へ進む。','ship',18,20,-4],['言い訳を考える','正しさを守るが、製品は変わらない。','perfect',1,0,8],['企画ごと捨てる','1回の反応を最終判定にする。','wait',-5,0,6]]},
 {k:'PROJECT 05',t:'橋は60%完成。今日中に渡る必要がある。',s:'最低限の補強なら間に合う。装飾と耐久試験を全部やる時間はない。',c:[['仮設橋として開通','人数を制限し、使いながら補強する。','ship',16,15,-2],['完璧な橋まで閉鎖','安全だが、今日の目的地には届かない。','perfect',2,2,13],['川の前で計画会議','橋を使わず設計だけ更新する。','wait',0,1,9]]},
 {k:'PROJECT 06',t:'小さな不具合を発見した。',s:'全体停止が必要な問題ではない。影響範囲も切り分けられている。',c:[['注意書き付きで継続','問題を公開し、次の更新で直す。','ship',13,13,-1],['全機能を作り直す','関係ない部分まで完全に再設計する。','perfect',1,2,15],['気づかなかったことにする','失敗を隠し、学びも失う。','wait',-3,-2,7]]},
 {k:'PROJECT 07',t:'改善案が3つ集まった。',s:'すべて同時には試せない。1つなら今日中に検証できる。',c:[['1案だけA/Bテスト','一番大きな仮説から先に確かめる。','ship',15,17,-2],['3案を完全実装','比較できないまま時間だけ使う。','perfect',4,3,12],['意見が揃うまで待つ','決めないことで失敗を避ける。','wait',0,0,8]]},
 {k:'FINAL',t:'締切5分前。公開ボタンがある。',s:'完璧ではない。でも、前の7回の失敗から直したものはすべて入っている。',c:[['公開する','現実の反応が、次の開発を始める。','ship',22,24,-5],['最終確認をもう一周','安心は増えるが、締切は過ぎる。','perfect',2,1,18],['公開を延期する','傷つかない代わりに、作品も届かない。','wait',0,0,10]]}
];
let i=0,progress=0,learning=0,perfection=0,timer=null,deadline=0,locked=false;
const $=s=>document.querySelector(s);
function start(){i=0;progress=0;learning=0;perfection=0;locked=false;$('#ending').hidden=true;show()}
function show(){if(i>=scenarios.length)return end();locked=false;const x=scenarios[i];$('#round').textContent=scenarios.length-i;$('#progress').textContent=Math.max(0,progress)+'%';$('#learning').textContent=learning;$('#perfection').textContent=perfection;$('#kicker').textContent=x.k;$('#title').textContent=x.t;$('#scene').textContent=x.s;$('#feedback').className='feedback';$('#feedback').textContent='';$('#choices').innerHTML=x.c.map((c,n)=>`<button class="choice ${c[2]==='ship'?'ship':''}" data-choice="${n}"><b>${c[0]}</b><span>${c[1]}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));deadline=performance.now()+6000;clearInterval(timer);timer=setInterval(tick,40);tick()}
function tick(){const left=Math.max(0,(deadline-performance.now())/6000);$('#timerBar').style.transform=`scaleX(${left})`;if(left<=0){clearInterval(timer);choose(2,true)}}
function choose(n,timeout=false){if(locked)return;locked=true;clearInterval(timer);const c=scenarios[i].c[n];progress+=c[3];learning+=c[4];perfection=Math.max(0,perfection+c[5]);const f=$('#feedback');f.textContent=timeout?'時間切れ。決めないことも「出さない」という選択になる。':c[2]==='ship'?'出した。反応が来た。次に直す場所が見えた。':c[2]==='perfect'?'きれいになった。でも、現実からの情報はほとんど増えなかった。':'失敗は避けた。同時に、前進と学びも止まった。';f.className='feedback show '+(c[2]==='ship'&&!timeout?'':'bad');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);setTimeout(()=>{i++;show()},1150)}
function end(){clearInterval(timer);const score=Math.max(0,Math.round(progress+learning-perfection));const rank=score>=210?'失敗の達人':score>=150?'改善の実践者':score>=90?'60点で出せる人':'完璧沼から練習中';$('#ending').innerHTML=`<div class="result"><small>SHIP & LEARN RESULT</small><h2>${rank}</h2><p>失敗した回数ではなく、失敗から何回学び直したかが、完成度を作りました。</p><div class="score-grid"><div><span>前進</span><b>${Math.max(0,progress)}%</b></div><div><span>学び</span><b>${learning}</b></div><div><span>完璧沼</span><b>${perfection}</b></div></div><button id="again">もう一度、60点で出す</button></div>`;$('#ending').hidden=false;$('#again').onclick=start}
$('#restart').onclick=start;start();
