(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-fail-forward-real-v1';
  const MODES={one:'1人に見せる',five:'5人で試す',limited:'限定で出す',live:'本番に出す'};
  let modal,mode='one',highRisk=false,before=7;
  const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));

  function ensureLauncher(){const ending=$('#ending');if(!ending||$('[data-real-ship-launch]',ending)||ending.hidden)return;const again=$('#again',ending);if(!again)return;const b=document.createElement('button');b.type='button';b.dataset.realShipLaunch='1';b.className='real-ship-launch';b.textContent='今の未完成を、60点で出す設計 →';b.addEventListener('click',open);again.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-ship-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-ship-card" role="dialog" aria-modal="true" aria-labelledby="realShipTitle"><div class="real-ship-head"><div><small>REAL LIFE / SHIP SAFELY</small><h2 id="realShipTitle">完璧にする前に、<br>安全な60点版を出す。</h2></div><button type="button" data-rs-close aria-label="閉じる">×</button></div>
    <section data-rs-step="input"><p>「雑に本番公開」ではない。学べる最小サイズまで落とす。</p><label><span>いま止まっている未完成のもの</span><textarea data-rs-project maxlength="180" placeholder="例：提案資料。内容はあるが、まだ見栄えが荒い。"></textarea></label><div class="real-ship-risk"><span>失敗した時のリスク</span><div><button type="button" data-rs-risk="normal" class="selected">やり直せる</button><button type="button" data-rs-risk="high">安全・法務・個人情報・大きな金銭</button></div></div><div class="real-ship-meter"><div><span>いま「出す」のが怖い強さ</span><strong><b data-rs-before-v>7</b>/10</strong></div><input data-rs-before type="range" min="0" max="10" value="7"></div><button class="real-ship-primary" data-rs-next type="button" disabled>60点の境界を決める →</button></section>
    <section data-rs-step="line" hidden><label><span>最低限、ここだけは守る</span><textarea data-rs-must maxlength="160" placeholder="例：数字の根拠と結論は確認済みにする。"></textarea></label><label><span>今回は後回しにしていいもの</span><textarea data-rs-later maxlength="160" placeholder="例：装飾、言い回しの細部、完璧な図表"></textarea></label><div class="real-ship-modes"><span>どのサイズで現実に出す？</span>${Object.entries(MODES).map(([id,v],i)=>`<button type="button" data-rs-mode="${id}" class="${i===0?'selected':''}">${v}</button>`).join('')}</div><div class="real-ship-warning" data-rs-warning hidden>高リスク案件は、60点で本番公開しない。まずレビュー・テストへ。</div><label><span>今から10分でやる最初の1手</span><input data-rs-action maxlength="120" placeholder="例：資料を○○さん1人に送る"></label><button class="real-ship-primary" data-rs-measure type="button" disabled>出す直前まで設計できた →</button></section>
    <section data-rs-step="after" hidden><div class="real-ship-summary" data-rs-summary></div><div class="real-ship-meter"><div><span>いま「出す」のが怖い強さ</span><strong><b data-rs-after-v>7</b>/10</strong></div><input data-rs-after type="range" min="0" max="10" value="7"></div><small>下がっていなくてもOK。無理に勇気が出たことにしない。</small><button class="real-ship-primary" data-rs-finish type="button">Before / Afterを見る</button></section>
    <section data-rs-step="done" hidden><h3 data-rs-done-title>完璧さではなく、次の学びが作れた。</h3><div class="real-ship-output"><div><small>60点版</small><p data-rs-project-out></p></div><div><small>MUST / 守る</small><strong data-rs-must-out></strong></div><div><small>SHIP SIZE</small><strong data-rs-mode-out></strong></div><div><small>FIRST MOVE</small><strong data-rs-action-out></strong></div></div><div class="real-ship-delta" data-rs-delta></div><div class="real-ship-history" data-rs-history hidden></div><button class="real-ship-secondary" data-rs-again type="button">別の未完成でもう1回</button></section></div>`;document.body.appendChild(modal);
    $('[data-rs-close]',modal).onclick=close;$('[data-rs-project]',modal).oninput=validateStart;$('[data-rs-before]',modal).oninput=e=>{before=Number(e.target.value);$('[data-rs-before-v]',modal).textContent=e.target.value};$$('[data-rs-risk]',modal).forEach(b=>b.onclick=()=>selectRisk(b));$('[data-rs-next]',modal).onclick=()=>show('line');$$('[data-rs-mode]',modal).forEach(b=>b.onclick=()=>selectMode(b));['must','action'].forEach(id=>$(`[data-rs-${id}]`,modal).addEventListener('input',validateLine));$('[data-rs-measure]',modal).onclick=measure;$('[data-rs-after]',modal).oninput=e=>$('[data-rs-after-v]',modal).textContent=e.target.value;$('[data-rs-finish]',modal).onclick=finish;$('[data-rs-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function show(n){$$('[data-rs-step]',modal).forEach(s=>s.hidden=s.dataset.rsStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-rs-project]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-ship-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-ship-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();mode='one';highRisk=false;before=7;['project','must','later','action'].forEach(id=>$(`[data-rs-${id}]`,modal).value='');$('[data-rs-before]',modal).value='7';$('[data-rs-after]',modal).value='7';$('[data-rs-before-v]',modal).textContent='7';$('[data-rs-after-v]',modal).textContent='7';$$('[data-rs-risk]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rsRisk==='normal'));$$('[data-rs-mode]',modal).forEach(b=>{b.disabled=false;b.classList.toggle('selected',b.dataset.rsMode==='one')});$('[data-rs-warning]',modal).hidden=true;$('[data-rs-next]',modal).disabled=true;$('[data-rs-measure]',modal).disabled=true;show('input')}
  function validateStart(){$('[data-rs-next]',modal).disabled=$('[data-rs-project]',modal).value.trim().length<2}
  function validateLine(){$('[data-rs-measure]',modal).disabled=$('[data-rs-must]',modal).value.trim().length<2||$('[data-rs-action]',modal).value.trim().length<2}
  function selectRisk(b){highRisk=b.dataset.rsRisk==='high';$$('[data-rs-risk]',modal).forEach(x=>x.classList.toggle('selected',x===b));const live=$('[data-rs-mode="live"]',modal);live.disabled=highRisk;$('[data-rs-warning]',modal).hidden=!highRisk;if(highRisk&&mode==='live'){mode='one';$$('[data-rs-mode]',modal).forEach(x=>x.classList.toggle('selected',x.dataset.rsMode==='one'))}}
  function selectMode(b){if(b.disabled)return;mode=b.dataset.rsMode;$$('[data-rs-mode]',modal).forEach(x=>x.classList.toggle('selected',x===b))}
  function measure(){const after=$('[data-rs-after]',modal);after.value=String(before);$('[data-rs-after-v]',modal).textContent=String(before);const must=$('[data-rs-must]',modal).value.trim(),later=$('[data-rs-later]',modal).value.trim()||'細部は次の周回で直す';$('[data-rs-summary]',modal).innerHTML=`<small>60点の境界</small><strong>${esc(must)}</strong><span>後回し：${esc(later)}</span><b>${esc(MODES[mode])}</b>`;show('after')}
  function finish(){const after=Number($('[data-rs-after]',modal).value),delta=before-after,project=$('[data-rs-project]',modal).value.trim(),must=$('[data-rs-must]',modal).value.trim(),action=$('[data-rs-action]',modal).value.trim();$('[data-rs-project-out]',modal).textContent=project;$('[data-rs-must-out]',modal).textContent=must;$('[data-rs-mode-out]',modal).textContent=MODES[mode]+(highRisk?'（本番前レビュー）':'');$('[data-rs-action-out]',modal).textContent=action;$('[data-rs-done-title]',modal).textContent=delta>0?'出す怖さが少し下がった。次は反応を取りに行ける。':delta===0?'怖さは同じ。でも安全な出し方は決まった。':'少し怖くなった。なら本番ではなく、さらに小さく試す。';$('[data-rs-delta]',modal).textContent=`出す怖さ ${before} → ${after}`;save({delta,mode,highRisk});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'fail-forward',delta,mode,highRisk}}));window.LevelUpTelemetry?.complete?.('real-ship')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-rs-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const shipped=runs.filter(r=>Number(r.delta)>=0).length;el.hidden=false;el.textContent=`現実の未完成 ${runs.length}件を設計。${shipped}件で怖さを増やさず出し方を決めました。`}catch{}}
  const observer=new MutationObserver(ensureLauncher);observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});setTimeout(ensureLauncher,300);
})();