(()=>{
const app=document.querySelector('#app'),TEST=new URLSearchParams(location.search).has('test');
let st={screen:'home',mode:'standard',type:'',residue:'',note:'',move:'stand',task:'',step:'',hp:8,sound:false,timer:0,started:Date.now(),actionStarted:0,retries:0};
const types={brain:['🧠','頭パンパン','考えすぎた'],people:['👥','人疲れ','人と話しすぎた'],tense:['⚡','緊張が残ってる','まだ会議モード'],empty:['🪫','電池切れ','何もしたくない'],unknown:['…','わからない','とにかく疲れた']};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const dur=k=>TEST?(k==='launch'?300:220):st.mode==='emergency'?{move:20000,quiet:15000,launch:20000}[k]:(k==='launch'?30000:({brain:[35000,45000],people:[30000,50000],tense:[30000,55000],empty:[55000,25000],unknown:[40000,40000]}[st.type]||[40000,40000])[k==='move'?0:1]);
const top=(label,p=0)=>`<header class="top"><span class="phase">${label}</span><button class="sound" data-a="sound" aria-label="音の切替">${st.sound?'♪':'♩'}</button></header>${p?`<div class="progress"><i style="width:${p}%"></i></div>`:''}`;
const shell=(body,label='MEETING RESPAWN',p=0)=>`<main class="shell">${top(label,p)}${body}</main>`;
const avatar=(ready=false)=>`<div class="avatarWrap"><i class="halo"></i><div class="avatar ${ready?'ready':''}"><i class="head"><i class="face"></i></i><i class="body"></i></div></div>`;
const hp=(v=st.hp)=>`<div class="hp"><div class="hpTop"><span>RECOVERY</span><strong>${Math.round(v)} / 100</strong></div><div class="bar"><i style="width:${Math.max(4,v)}%"></i></div></div>`;
function clear(){if(st.timer){clearInterval(st.timer);st.timer=0}}function vib(v=20){try{navigator.vibrate?.(v)}catch{}}function beep(f=520){if(!st.sound)return;try{const A=AudioContext||webkitAudioContext,c=new A,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.06);o.stop(c.currentTime+.06)}catch{}}function toast(t){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),950)}
function home(){clear();st.screen='home';st.hp=8;app.innerHTML=shell(`<section class="screen"><div class="eyebrow">MEETING RESPAWN</div><h1 class="title">会議、終了。</h1><p class="lead">今すぐ元気にならなくていい。<br><b>次の仕事を1手始められたらクリア。</b></p>${avatar()}${hp(8)}<div class="actions"><button class="btn primary" data-a="start">復活する</button><button class="btn ghost" data-a="emergency">⚡ 90秒で戻る</button></div><p class="micro">診断しない。反省会もしない。会議モードを閉じて、次の30秒へ。</p></section>`)}
function reset(mode){clear();st={...st,screen:'type',mode,type:'',residue:'',note:'',move:'stand',task:'',step:'',hp:8,timer:0,started:Date.now(),actionStarted:0,retries:0};typeScreen()}
function typeScreen(){st.screen='type';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">CHECK 01</div><h1 class="title">どんな疲れ？</h1><p class="lead">深く考えなくていい。いちばん近いものを1タップ。</p><div class="choices">${Object.entries(types).map(([k,v])=>`<button class="choice" data-type="${k}"><span class="ico">${v[0]}</span><span><b>${v[1]}</b><small>${v[2]}</small></span><span class="go">›</span></button>`).join('')}</div></section>`,'状態を選ぶ',12)}
function closeScreen(){st.screen='close';const input=st.residue==='todo';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">CLOSE 02</div><h1 class="title">会議を閉じる。</h1><p class="lead">頭に残っているものは、いま処理しない。置いて、扉を閉める。</p><div id="door" class="doorBox"><div class="frame"></div><div class="door"></div><span class="note">あとでいい</span></div>${input?`<div class="card"><div class="field"><label for="note">忘れたくないことを1個だけ</label><input id="note" class="input" maxlength="60" placeholder="例：Aさんに資料を送る" value="${esc(st.note)}"><div class="count"><span id="noteN">${st.note.length}</span> / 60</div></div><div class="actions" style="margin-top:11px"><button class="btn primary" data-a="close">箱に置いて閉じる</button><button class="btn ghost" data-a="skipnote">書かずに閉じる</button></div></div>`:`<div class="choices"><button class="choice" data-res="todo"><span class="ico">✓</span><span><b>やることが残ってる</b><small>1個だけ外へ出す</small></span><span class="go">›</span></button><button class="choice" data-res="wait"><span class="ico">⌛</span><span><b>返事待ち</b><small>今は自分の番じゃない</small></span><span class="go">›</span></button><button class="choice" data-res="moya"><span class="ico">☁</span><span><b>モヤモヤだけ</b><small>答えを出さず閉じる</small></span><span class="go">›</span></button><button class="choice" data-res="none"><span class="ico">○</span><span><b>特にない</b><small>そのまま閉じる</small></span><span class="go">›</span></button></div>`}</section>`,'会議を閉じる',25)}
function closeDoor(){document.querySelector('#door')?.classList.add('closed');st.hp=24;beep(320);vib();setTimeout(()=>{toast(st.residue==='wait'?'返事が来るまで、あなたの番じゃない':st.residue==='moya'?'答えを出さなくていい':'頭の外へ置いた');moveScreen()},TEST?80:650)}
function moveScreen(){clear();st.screen='move';const sec=Math.ceil(dur('move')/1000);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">REBOOT 03</div><h1 class="title">身体を先に。</h1><p class="lead">考えるのはまだ後。<b>${sec}秒だけ</b>身体を動かす。</p>${avatar(true)}${hp(st.hp)}<div class="chips"><button class="chip ${st.move==='stand'?'on':''}" data-move="stand">立って少し歩く</button><button class="chip ${st.move==='sit'?'on':''}" data-move="sit">座って肩を動かす</button></div><button class="btn primary" data-a="movestart">${sec}秒だけ動く</button><button class="btn ghost" data-a="moveskip">もう戻れそう →</button></section>`,'身体を再起動',38)}
function timer(kind,done){clear();const d=dur(kind),start=performance.now(),ring=document.querySelector('.timer'),num=document.querySelector('[data-sec]'),bar=document.querySelector('.bar i'),from=st.hp,to=kind==='move'?42:kind==='quiet'?55:62;st.timer=setInterval(()=>{const e=performance.now()-start,p=Math.min(1,e/d);if(ring)ring.style.setProperty('--p',p);if(num)num.textContent=Math.max(0,Math.ceil((d-e)/1000));if(bar)bar.style.width=`${from+(to-from)*p}%`;if(p>=1){clear();st.hp=to;done()}},TEST?20:100)}
function moveRun(){st.screen='moveRun';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">REBOOT 03</div><h1 class="title">${st.move==='stand'?'歩く。伸びる。':'肩を回す。姿勢を変える。'}</h1><p class="lead">うまくやらなくていい。画面も見なくていい。</p><div class="timer"><div class="timerText"><strong data-sec>${Math.ceil(dur('move')/1000)}</strong><span>SECONDS</span></div></div>${hp()}<button class="btn ghost" data-a="moveskip">もう十分 →</button></section>`,'身体を再起動',44);timer('move',quietScreen)}
function quietScreen(){clear();st.screen='quiet';st.hp=Math.max(st.hp,42);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">COOL DOWN 04</div><h1 class="title">何もしない。</h1><p class="lead">次の仕事を考える前に、少しだけ会議の速度を落とす。</p><div class="pulse"></div><p class="lead"><b>${Math.ceil(dur('quiet')/1000)}秒、ぼーっとしていい。</b><br>呼吸を合わせても、合わせなくてもいい。</p>${hp()}<button class="btn primary" data-a="quietstart">静かにする</button><button class="btn ghost" data-a="quietskip">もう戻れそう →</button></section>`,'静かにする',52)}
function quietRun(){st.screen='quietRun';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">COOL DOWN 04</div><h1 class="title">そのままでいい。</h1><div class="timer"><div class="timerText"><strong data-sec>${Math.ceil(dur('quiet')/1000)}</strong><span>SECONDS</span></div></div><p class="lead">会議はもう終わった。いま答えを出さなくていい。</p>${hp()}<button class="btn ghost" data-a="quietskip">次へ →</button></section>`,'静かにする',58);timer('quiet',taskScreen)}
function taskScreen(){clear();st.screen='task';st.hp=Math.max(st.hp,55);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">NEXT 05</div><h1 class="title">次は、1個だけ。</h1><p class="lead">全部の仕事を思い出さない。<br><b>次に触る仕事だけ</b>決める。</p><div class="card"><div class="field"><label for="task">次にやる仕事</label><input id="task" class="input" maxlength="80" placeholder="例：V1の資料" value="${esc(st.task)}"><div class="count"><span id="taskN">${st.task.length}</span> / 80</div></div><div class="actions" style="margin-top:11px"><button class="btn primary" data-a="tasknext" ${st.task.trim()?'':'disabled'}>最初の30秒にする</button><button class="btn ghost" data-a="finish">今日はもう仕事を終える</button></div></div></section>`,'次の仕事を1つ',68)}
function stepScreen(){st.screen='step';const opts=[['open','↗','ファイル・ページを開く','開くだけで成功'],['line','Aa','1行だけ書く','完成させない'],['check','⌕','必要な箇所を1つ見る','1個見たら成功'],['custom','＋','自分で30秒の一手を書く','自分に合う一手']];app.innerHTML=shell(`<section class="screen"><div class="eyebrow">SHRINK 06</div><h1 class="title">まだ、やらない。</h1><p class="lead"><b>${esc(st.task)}</b> を終わらせない。最初の30秒だけ選ぶ。</p><div class="choices">${opts.map(o=>`<button class="choice" data-step="${o[0]}"><span class="ico">${o[1]}</span><span><b>${o[2]}</b><small>${o[3]}</small></span><span class="go">›</span></button>`).join('')}</div></section>`,'30秒まで小さく',78)}
function customStep(){st.screen='custom';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">SHRINK 06</div><h1 class="title">30秒なら何する？</h1><p class="lead">「終わらせる」ではなく、触り始めるだけ。</p><div class="card"><div class="field"><label for="step">最初の一手</label><input id="step" class="input" maxlength="70" placeholder="例：資料ファイルを開く" value="${esc(st.step)}"></div><div class="actions" style="margin-top:11px"><button class="btn primary" data-a="customnext" ${st.step.trim()?'':'disabled'}>これで発進</button></div></div></section>`,'30秒まで小さく',80)}
function launchScreen(){clear();st.screen='launch';st.hp=Math.max(st.hp,58);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">LAUNCH 07</div><h1 class="title">完全回復は、いらない。</h1><p class="lead">動けるHPまで戻った。ここからはアプリじゃなく仕事を見る。</p><div class="pill"><b>${esc(st.step)}</b></div><div class="launch"><div class="go"><strong>GO</strong><span>30秒だけ</span></div></div><button class="btn primary" data-a="launch">30秒だけやる</button><p class="micro">押したら、アプリは見なくていい。</p></section>`,'発進',88)}
function launchRun(){st.screen='launchRun';st.actionStarted=st.actionStarted||Date.now();app.innerHTML=shell(`<section class="screen"><div class="eyebrow">ACTION AVAILABLE</div><h1 class="title">画面を見なくていい。</h1><p class="lead">いまやるのは <b>${esc(st.step)}</b> だけ。</p><div class="launch run"><div class="go"><strong data-sec>${Math.ceil(dur('launch')/1000)}</strong><span>仕事を始める</span></div></div><p class="lead">できたところまででいい。</p></section>`,'30秒だけ開始',94);beep(680);vib([20,30,20]);timer('launch',checkScreen)}
function checkScreen(){clear();st.screen='check';st.hp=Math.max(st.hp,62);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">CHECK</div><h1 class="title">始められた？</h1><p class="lead">完成してなくていい。仕事に触れ始めたかだけ。</p>${avatar(true)}${hp()}<div class="actions"><button class="btn primary" data-a="success">始めた</button><button class="btn secondary" data-a="retry">まだ</button></div></section>`,'開始できた？',97)}
function retry(){st.retries++;st.step=st.step.includes('開く')?'そのファイル名を見るだけ':st.step.includes('書')?'カーソルを置くだけ':st.step.includes('見る')?'対象のページを開くだけ':'必要な画面を開くだけ';toast('もっと小さくした');launchScreen()}
function save(){const sec=Math.max(1,Math.round((Date.now()-st.started)/1000));let d={count:0,total:0,retries:0};try{d=JSON.parse(localStorage.getItem('meeting-respawn-stats')||'null')||d}catch{}d.count=Number(d.count)||0;d.total=Number(d.total)||0;d.retries=Number(d.retries)||0;d.count++;d.total+=sec;d.retries+=st.retries;try{localStorage.setItem('meeting-respawn-stats',JSON.stringify(d))}catch{}return d}
function resultScreen(){st.screen='result';st.hp=64;const d=save(),avg=Math.round(d.total/d.count);beep(900);vib([20,30,60]);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">RESPAWN COMPLETE</div><div class="result"><div class="check">✓</div></div><h1 class="title">復帰完了。</h1><p class="lead">100%まで回復しなくていい。<br><b>次の一手を始められた。それで勝ち。</b></p><div class="stats"><div class="stat"><strong>${d.count}</strong><span>復活回数</span></div><div class="stat"><strong>${st.retries}</strong><span>今回の縮め直し</span></div><div class="stat"><strong>${avg<60?avg+'秒':Math.floor(avg/60)+':'+String(avg%60).padStart(2,'0')}</strong><span>平均復帰</span></div></div><div class="actions"><button class="btn primary" data-a="done">仕事へ戻る</button><button class="btn ghost" data-a="again">もう一度使う</button></div></section>`,'RESPAWN COMPLETE',100)}
function finishScreen(){st.screen='finish';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">SHUTDOWN</div><h1 class="title">今日は、閉じる。</h1><p class="lead">復帰しない日もある。明日の最初の一手だけ置いて終了する。</p><div class="card"><div class="field"><label for="step">明日の最初の30秒</label><input id="step" class="input" maxlength="70" placeholder="例：V1資料を開く"></div><div class="actions" style="margin-top:11px"><button class="btn primary" data-a="shutdown">WORKDAY COMPLETE</button></div></div></section>`,'今日は終了',86)}
app.addEventListener('input',e=>{if(e.target.id==='note'){st.note=e.target.value;document.querySelector('#noteN').textContent=st.note.length}if(e.target.id==='task'){st.task=e.target.value;document.querySelector('#taskN').textContent=st.task.length;document.querySelector('[data-a=tasknext]').disabled=!st.task.trim()}if(e.target.id==='step'){st.step=e.target.value;const b=document.querySelector('[data-a=customnext]');if(b)b.disabled=!st.step.trim()}});
app.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a,t=e.target.closest('[data-type]')?.dataset.type,r=e.target.closest('[data-res]')?.dataset.res,m=e.target.closest('[data-move]')?.dataset.move,s=e.target.closest('[data-step]')?.dataset.step;if(t){st.type=t;beep();closeScreen();return}if(r){st.residue=r;if(r==='todo')closeScreen();else closeDoor();return}if(m){st.move=m;moveScreen();return}if(s){if(s==='custom'){st.step='';customStep()}else{st.step=s==='open'?'ファイル・ページを開く':s==='line'?'1行だけ書く':'必要な箇所を1つ見る';launchScreen()}return}if(!a)return;switch(a){case'sound':st.sound=!st.sound;toast(st.sound?'音 ON':'音 OFF');document.querySelector('[data-a=sound]').textContent=st.sound?'♪':'♩';break;case'start':reset('standard');break;case'emergency':reset('emergency');break;case'close':st.note=document.querySelector('#note')?.value.trim()||'';closeDoor();break;case'skipnote':st.note='';closeDoor();break;case'movestart':moveRun();break;case'moveskip':st.hp=42;quietScreen();break;case'quietstart':quietRun();break;case'quietskip':st.hp=55;taskScreen();break;case'tasknext':st.task=document.querySelector('#task')?.value.trim()||'';if(st.task)stepScreen();break;case'finish':finishScreen();break;case'customnext':st.step=document.querySelector('#step')?.value.trim()||'';if(st.step)launchScreen();break;case'launch':launchRun();break;case'success':resultScreen();break;case'retry':retry();break;case'done':location.href='/';break;case'again':home();break;case'shutdown':toast('今日は終了。仕事を閉じた');setTimeout(()=>location.href='/',TEST?120:800)}});
window.addEventListener('beforeunload',clear);home();
})();
