(()=>{
const app=document.querySelector('#app');
const TEST=new URLSearchParams(location.search).has('test');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const residuePresets=['返事しなきゃ','あれどうしよう','言われたことが残る','うまく話せなかった','なんかモヤモヤ','ただ疲れた'];
const returnPoints={previous:['↩','さっき開いていたもの','元の画面に戻るだけ','さっきの画面を開く'],list:['☰','タスクリスト','決めずに眺めるだけ','タスクリストを開くだけ'],memo:['□','メモ・議事録','確認するだけでいい','メモを開くだけ'],easy:['○','いちばん簡単な作業','重要度は考えない','簡単な作業の画面を開くだけ']};
let st={screen:'home',sound:false,timer:0,dump:[],free:'',restSeconds:60,restCycles:0,fog:'',returnPoint:'',started:Date.now()};
const top=(label,p=0)=>`<header class="top"><span class="phase">${label}</span><button class="sound" data-a="sound" aria-label="音の切替">${st.sound?'♪':'♩'}</button></header>${p?`<div class="progress"><i style="width:${p}%"></i></div>`:''}`;
const shell=(body,label='MEETING RESPAWN',p=0)=>`<main class="shell">${top(label,p)}${body}</main>`;
function clearTimer(){if(st.timer){clearInterval(st.timer);st.timer=0}}
function vib(v=20){try{navigator.vibrate?.(v)}catch{}}
function beep(f=520){if(!st.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,c=new A,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.07);o.stop(c.currentTime+.07)}catch{}}
function toast(t){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1100)}
function duration(){return TEST?500:st.restSeconds*1000}
function reset(){clearTimer();st={screen:'dump',sound:st.sound,timer:0,dump:[],free:'',restSeconds:60,restCycles:0,fog:'',returnPoint:'',started:Date.now()};dumpScreen()}
function home(){clearTimer();st.screen='home';app.innerHTML=shell(`<section class="screen heroScreen"><div class="eyebrow">MEETING RESPAWN</div><h1 class="title">会議、終了。</h1><p class="lead">今は、次を考えなくていい。<br><b>頭の中に残っている会議を、先に下ろそう。</b></p><div class="brainScene" aria-hidden="true"><div class="brainGlow"></div><div class="brainCore">☁</div><span class="spark s1"></span><span class="spark s2"></span><span class="spark s3"></span><span class="spark s4"></span></div><div class="actions"><button class="btn primary" data-a="start">会議モードを閉じる</button></div><p class="micro">反省しない。整理しない。次の打ち手も、まだ決めない。</p></section>`)}
function dumpScreen(){clearTimer();st.screen='dump';const picked=new Set(st.dump);app.innerHTML=shell(`<section class="screen"><div class="eyebrow">UNLOAD 01</div><h1 class="title">頭の残響を、置く。</h1><p class="lead">意味不明でいい。解決もしない。<br><b>頭に残っているものを外へ出すだけ。</b></p><div class="dumpZone"><div class="dumpCloud">${st.dump.length||st.free.trim()?'<span>置いたものは<br>いま考えない</span>':'<span>ここに<br>置いていく</span>'}</div>${st.dump.map((x,i)=>`<i class="thought t${i%5}">${esc(x)}</i>`).join('')}</div><div class="presetGrid">${residuePresets.map(x=>`<button class="preset ${picked.has(x)?'on':''}" data-preset="${esc(x)}">${picked.has(x)?'✓ ':''}${esc(x)}</button>`).join('')}</div><div class="field compact"><label for="free">ほかに残っていること（書かなくてもOK）</label><textarea id="free" class="input textarea" maxlength="160" placeholder="例：なんか嫌だった。あとで返事する。よく分からない。">${esc(st.free)}</textarea><div class="count"><span id="freeN">${st.free.length}</span> / 160</div></div><div class="actions"><button class="btn primary" data-a="dumpdone">ここに置いて、閉じる</button><button class="btn ghost" data-a="dumpskip">書かずに閉じる</button></div></section>`,'頭から外へ',18)}
function sealScreen(){clearTimer();st.screen='seal';beep(340);vib();app.innerHTML=shell(`<section class="screen"><div class="eyebrow">CLOSE 02</div><h1 class="title">置いた。<br>いまは処理しない。</h1><p class="lead">忘れたわけじゃない。<br><b>会議の外に出しただけ。</b></p><div class="sealScene" aria-hidden="true"><div class="sealBox"><div class="sealLid"></div><div class="sealLabel">あとでいい</div></div><div class="mist m1"></div><div class="mist m2"></div><div class="mist m3"></div></div><p class="micro">次の仕事は、まだ考えなくていい。</p></section>`,'会議を閉じる',30);setTimeout(restScreen,TEST?120:900)}
function restScreen(){clearTimer();st.screen='rest';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">COOL DOWN 03</div><h1 class="title">仕事の前に、休む。</h1><p class="lead">ここでは何も決めない。<br><b>画面から目を離していい。</b></p><div class="restHints"><span>水を飲む</span><span>立つ</span><span>遠くを見る</span><span>何もしない</span></div><div class="calmOrb" aria-hidden="true"><i></i></div><div class="restChoice"><button class="chip ${st.restSeconds===60?'on':''}" data-rest="60">1分休む</button><button class="chip ${st.restSeconds===120?'on':''}" data-rest="120">2分休む</button></div><button class="btn primary" data-a="reststart">${st.restSeconds===120?'2分':'1分'}、休憩する</button><button class="btn ghost" data-a="restskip">もう少し静かになった →</button></section>`,'休憩する',44)}
function restRun(){clearTimer();st.screen='restRun';st.restCycles++;const d=duration(),start=performance.now();app.innerHTML=shell(`<section class="screen"><div class="eyebrow">COOL DOWN 03</div><h1 class="title">何もしなくていい。</h1><p class="lead">次の打ち手は考えない。<br>会議の速度が抜けるのを待つ。</p><div class="timer"><div class="timerText"><strong data-sec>${Math.ceil(d/1000)}</strong><span>REST</span></div></div><div class="restNow"><span>スマホを伏せてもOK</span><b>水を飲む / 遠くを見る / ぼーっとする</b></div><button class="btn ghost" data-a="restskip">もう十分 →</button></section>`,'休憩中',55);st.timer=setInterval(()=>{const e=performance.now()-start,p=Math.min(1,e/d),ring=document.querySelector('.timer'),num=document.querySelector('[data-sec]');if(ring)ring.style.setProperty('--p',p);if(num)num.textContent=Math.max(0,Math.ceil((d-e)/1000));if(p>=1){clearTimer();fogScreen()}},TEST?25:100)}
function fogScreen(){clearTimer();st.screen='fog';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">CHECK 04</div><h1 class="title">頭の霧、どう？</h1><p class="lead">仕事の判断じゃない。<br><b>いまの自分の戻り具合だけ見る。</b></p><div class="fogMeter" aria-hidden="true"><div class="fogLayer f1"></div><div class="fogLayer f2"></div><div class="fogPerson">●</div></div><div class="choices"><button class="choice" data-fog="heavy"><span class="ico">☁</span><span><b>まだモヤモヤ</b><small>仕事側には戻らない</small></span><span class="go">›</span></button><button class="choice" data-fog="some"><span class="ico">◐</span><span><b>少し戻った</b><small>戻り口だけ探せそう</small></span><span class="go">›</span></button><button class="choice" data-fog="clear"><span class="ico">○</span><span><b>戻った</b><small>次ではなく、再開地点へ</small></span><span class="go">›</span></button></div></section>`,'回復度だけ確認',68)}
function moreRest(){st.fog='heavy';st.restSeconds=60;app.innerHTML=shell(`<section class="screen"><div class="eyebrow">STAY 04</div><h1 class="title">まだ戻らなくていい。</h1><p class="lead">モヤモヤしているのに、<br><b>次を決める必要はない。</b></p><div class="calmOrb small" aria-hidden="true"><i></i></div><div class="actions"><button class="btn primary" data-a="restagain">もう1分休む</button><button class="btn secondary" data-a="finishrest">今日はここで終了</button></div><p class="micro">頭が少し静かになったなら、それだけでも成功。</p></section>`,'まだ休む',70)}
function returnScreen(){clearTimer();st.screen='return';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">RETURN 05</div><h1 class="title">次じゃなく、戻り口。</h1><p class="lead">何を成し遂げるかは決めない。<br><b>仕事世界のどこへ戻るかだけ。</b></p><div class="choices">${Object.entries(returnPoints).map(([k,v])=>`<button class="choice" data-return="${k}"><span class="ico">${v[0]}</span><span><b>${v[1]}</b><small>${v[2]}</small></span><span class="go">›</span></button>`).join('')}</div><button class="btn ghost" data-a="notyet">やっぱり、まだ休む</button></section>`,'戻り口だけ選ぶ',80)}
function readyScreen(){clearTimer();st.screen='ready';const p=returnPoints[st.returnPoint]||returnPoints.previous;app.innerHTML=shell(`<section class="screen"><div class="eyebrow">RESPAWN 06</div><h1 class="title">打ち手は、いらない。</h1><p class="lead">いま決めたのは仕事じゃない。<br><b>ただ戻る場所を見つけただけ。</b></p><div class="returnCard"><span>${p[0]}</span><div><small>戻り口</small><strong>${p[1]}</strong><em>${p[3]}</em></div></div><div class="launch soft"><div class="go"><strong>OPEN</strong><span>それだけでOK</span></div></div><div class="actions"><button class="btn primary" data-a="complete">${p[3]}</button><button class="btn ghost" data-a="notyet">まだ休む</button></div></section>`,'小さく戻る',92)}
function save(outcome='returned'){const sec=Math.max(1,Math.round((Date.now()-st.started)/1000));let d={count:0,total:0,restCycles:0,restOnly:0};try{d=JSON.parse(localStorage.getItem('meeting-respawn-stats-v2')||'null')||d}catch{}d.count=(Number(d.count)||0)+1;d.total=(Number(d.total)||0)+sec;d.restCycles=(Number(d.restCycles)||0)+st.restCycles;if(outcome==='rest')d.restOnly=(Number(d.restOnly)||0)+1;try{localStorage.setItem('meeting-respawn-stats-v2',JSON.stringify(d))}catch{}return d}
function resultScreen(outcome='returned'){clearTimer();st.screen='result';const d=save(outcome),avg=Math.round(d.total/d.count);beep(outcome==='returned'?760:520);vib([20,30,20]);const returned=outcome==='returned';app.innerHTML=shell(`<section class="screen"><div class="eyebrow">${returned?'RESPAWN COMPLETE':'RECOVERY COMPLETE'}</div><div class="result ${returned?'':'restResult'}"><div class="check">${returned?'✓':'…'}</div></div><h1 class="title">${returned?'戻る場所が、見つかった。':'今日は、ここまででいい。'}</h1><p class="lead">${returned?'次の打ち手まで決めなくていい。<br><b>会議モードを抜けて、仕事へ戻る入口を見つけた。</b>':'次を決められなくても失敗じゃない。<br><b>頭を少し静かにできた。それで終了。</b>'}</p><div class="stats"><div class="stat"><strong>${d.count}</strong><span>リスポーン回数</span></div><div class="stat"><strong>${st.restCycles}</strong><span>今回の休憩</span></div><div class="stat"><strong>${avg<60?avg+'秒':Math.floor(avg/60)+':'+String(avg%60).padStart(2,'0')}</strong><span>平均時間</span></div></div><div class="actions"><button class="btn primary" data-a="done">LEVEL UPへ戻る</button><button class="btn ghost" data-a="again">もう一度使う</button></div></section>`,'完了',100)}
app.addEventListener('input',e=>{if(e.target.id==='free'){st.free=e.target.value;const n=document.querySelector('#freeN');if(n)n.textContent=st.free.length}});
app.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;const preset=e.target.closest('[data-preset]')?.dataset.preset;const rest=e.target.closest('[data-rest]')?.dataset.rest;const fog=e.target.closest('[data-fog]')?.dataset.fog;const ret=e.target.closest('[data-return]')?.dataset.return;if(preset){const i=st.dump.indexOf(preset);if(i>=0)st.dump.splice(i,1);else st.dump.push(preset);dumpScreen();return}if(rest){st.restSeconds=Number(rest);restScreen();return}if(fog){st.fog=fog;if(fog==='heavy')moreRest();else returnScreen();return}if(ret){st.returnPoint=ret;readyScreen();return}if(!a)return;switch(a){case'sound':st.sound=!st.sound;toast(st.sound?'音 ON':'音 OFF');document.querySelector('[data-a=sound]').textContent=st.sound?'♪':'♩';break;case'start':reset();break;case'dumpdone':st.free=document.querySelector('#free')?.value||st.free;sealScreen();break;case'dumpskip':st.dump=[];st.free='';sealScreen();break;case'reststart':restRun();break;case'restskip':fogScreen();break;case'restagain':st.restSeconds=60;restRun();break;case'notyet':st.restSeconds=60;restScreen();break;case'finishrest':resultScreen('rest');break;case'complete':resultScreen('returned');break;case'done':location.href='/';break;case'again':home();break;}}
);
window.addEventListener('beforeunload',clearTimer);home();
})();