(()=>{
const app=document.getElementById('app');
const reset=document.getElementById('resetBtn');
const STORE='levelup-day-switch-v1';
let state={phase:'home',carry:'',tomorrow:'',release:''};
const releaseOptions=['予定より進まなかった','未完了が残った','今日はもう疲れた'];

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function readHistory(){try{const raw=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(raw)?raw.slice(0,14):[];}catch{return[];}}
function dayKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function streak(){const days=new Set(readHistory().map(x=>x.day));let n=0;const d=new Date();for(;;){const key=dayKey(d);if(!days.has(key))break;n++;d.setDate(d.getDate()-1);}return n;}
function save(){const history=readHistory().filter(x=>x.day!==dayKey());history.unshift({day:dayKey(),at:new Date().toISOString(),tomorrow:state.tomorrow});localStorage.setItem(STORE,JSON.stringify(history.slice(0,14)));}

function home(){state={phase:'home',carry:'',tomorrow:'',release:''};reset.hidden=true;const history=readHistory();const s=streak();app.innerHTML=`<section class="hero"><div class="eyebrow">DAY SWITCH</div><h1>今日は、ここで閉じる。<span>進まなかった一日を、そのまま明日まで持っていかない。</span></h1><p class="lead">未完了を<strong>1つだけ預ける</strong>。今日への評価を止める。最後に<strong>明日の最初の10分</strong>を決めて、夜へ切り替えます。</p><div class="facts"><span>約90秒</span><span>夕方〜夜の終了儀式</span>${s?`<span class="streak">${s}日連続で閉じた</span>`:''}</div><button type="button" class="primary" id="startBtn">今日を閉じる</button>${history[0]?.tomorrow?`<div class="history">前回決めた最初の10分：${esc(history[0].tomorrow)}</div>`:''}</section>`;document.getElementById('startBtn').onclick=()=>renderCarry();}

function renderCarry(){state.phase='carry';reset.hidden=false;app.innerHTML=`<section class="stage"><div class="stage-head"><div><div class="eyebrow">PARK</div><h2>未完了を、1つだけ預ける。</h2></div><div class="step">1 / 3</div></div><p class="stage-copy">全部を整理しなくて大丈夫。今夜、頭の中で持ち続けたくない仕事を1つだけ外に置きます。</p><label class="field"><span>明日に預けるもの</span><input id="carryInput" maxlength="80" autocomplete="off" placeholder="例：提案資料の続きを作る" value="${esc(state.carry)}"></label><div class="hint">ここで予定表は作りません。1つだけで進みます。</div><button type="button" class="primary" id="carryNext" disabled>次へ</button></section>`;const input=document.getElementById('carryInput');const next=document.getElementById('carryNext');input.oninput=()=>{state.carry=input.value.trim();next.disabled=!state.carry};if(state.carry)next.disabled=false;next.onclick=()=>renderRelease();input.focus();}

function renderRelease(){state.phase='release';app.innerHTML=`<section class="stage"><div class="stage-head"><div><div class="eyebrow">RELEASE</div><h2>今日の判定を、ここで止める。</h2></div><div class="step">2 / 3</div></div><p class="stage-copy">起きたことは消しません。でも「今日はダメだった」の採点は夜まで延長しない。近いものを1つ選びます。</p><div class="release-wrap">${releaseOptions.map(x=>`<button type="button" class="release-chip${state.release===x?' is-on':''}" data-release="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="summary"><small>TODAY</small><h3>未完了は、明日に預けた。</h3><dl><div><dt>預けたもの</dt><dd>${esc(state.carry)}</dd></div><div><dt>今夜はしないこと</dt><dd>今日一日の評価を続けること</dd></div></dl></div><button type="button" class="primary" id="releaseNext" ${state.release?'':'disabled'}>明日の1手を決める</button></section>`;document.querySelectorAll('[data-release]').forEach(btn=>btn.onclick=()=>{state.release=btn.dataset.release;renderRelease()});const next=document.getElementById('releaseNext');if(!next.disabled)next.onclick=()=>renderTomorrow();}

function renderTomorrow(){state.phase='tomorrow';app.innerHTML=`<section class="stage"><div class="stage-head"><div><div class="eyebrow">LAUNCH</div><h2>明日の最初の10分だけ。</h2></div><div class="step">3 / 3</div></div><p class="stage-copy">明日を立て直す計画は不要です。始業後に最初にやる、10分以内の小さい動作だけ決めます。</p><label class="field"><span>明日の最初の10分</span><input id="tomorrowInput" maxlength="80" autocomplete="off" placeholder="例：資料を開いて1ページ目だけ直す" value="${esc(state.tomorrow)}"></label><div class="hint">「資料を完成させる」ではなく、「開く・1行書く・1件確認する」くらいまで小さく。</div><button type="button" class="primary" id="finishBtn" disabled>今日を閉じる</button></section>`;const input=document.getElementById('tomorrowInput');const btn=document.getElementById('finishBtn');input.oninput=()=>{state.tomorrow=input.value.trim();btn.disabled=!state.tomorrow};if(state.tomorrow)btn.disabled=false;btn.onclick=finish;input.focus();}

function finish(){if(!state.tomorrow)return;save();state.phase='done';reset.hidden=true;app.innerHTML=`<section class="done"><div class="stamp">TODAY CLOSED</div><div class="switch-line"></div><h2>明日は、ここから。</h2><p>今日の続きではなく、明日の最初の1手だけ残しました。今夜はもう、仕事を進める日ではありません。</p><div class="tomorrow"><small>FIRST 10 MINUTES</small><strong>${esc(state.tomorrow)}</strong></div><button type="button" class="primary" id="closeBtn">夜へ切り替える</button></section>`;document.getElementById('closeBtn').onclick=home;}
reset.onclick=home;home();
})();
