(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-viewpoint-real-v1';
  const LENSES=[
    {id:'remain',name:'残ったもの',q:'失ったものの横に、まだ残っている事実・資源・選択肢は？'},
    {id:'compare',name:'比較の幅',q:'小さく言い換えず、より広い範囲で現在地を測ると？'},
    {id:'time',name:'時間を伸ばす',q:'1週間後・1年後から見ると、この出来事の意味はどう変わる？'},
    {id:'learn',name:'学び',q:'次回に再利用できる情報・チェック項目を1つ持ち帰るなら？'},
    {id:'chance',name:'機会',q:'この出来事で新しく空いた時間・役割・選択肢はある？'},
    {id:'constraint',name:'制約を使う',q:'この制約をルールにして、小さく・速く進めるなら？'},
    {id:'story',name:'ネタ',q:'無理に笑わず、将来「経験」として語れる部分はある？'},
    {id:'next',name:'次の一手',q:'過去の評価を止めて、次回変えられる行動を1つ作るなら？'},
    {id:'other',name:'相手側',q:'自分への攻撃と決めつけず、相手の事情・役割・目的から見ると？'},
    {id:'present',name:'今あるもの',q:'「ないもの」から注意を外し、今すぐ使えるものを見ると？'}
  ];
  let modal,picks=[],views=[],chosen=-1;
  const esc=v=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);

  function ensureLauncher(){const retry=$('#retry-game');if(!retry||$('[data-real-view-launch]'))return;const b=document.createElement('button');b.type='button';b.className='primary-button real-view-launch';b.dataset.realViewLaunch='1';b.textContent='今の出来事を、3つの見方でほどく →';b.addEventListener('click',open);retry.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-view-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-view-card" role="dialog" aria-modal="true" aria-labelledby="realViewTitle">
    <div class="real-view-head"><div><small>REAL LIFE / THREE VIEWS</small><h2 id="realViewTitle">事実は変えず、<br>意味を3つに増やす。</h2></div><button type="button" data-rv-close aria-label="閉じる">×</button></div>
    <section data-rv-step="input"><p>嫌だった事実を消さない。そのうえで、最初の解釈だけに固定しない。</p><label><span>いま引っかかっている出来事</span><textarea data-rv-event maxlength="180" placeholder="例：会議で提案が通らなかった。"></textarea></label><label><span>最初に浮かんだ意味・評価（任意）</span><input data-rv-first maxlength="100" placeholder="例：自分の提案力が低い"></label><div class="real-view-meter"><div><span>最初の見方に固定されている感じ</span><strong><b data-rv-before-v>7</b>/10</strong></div><input data-rv-before type="range" min="0" max="10" value="7"></div><button class="real-view-primary" data-rv-start type="button" disabled>3つの型を引く →</button></section>
    <section data-rv-step="views" hidden><div class="real-view-event"><small>FACT</small><strong data-rv-event-out></strong></div><div class="real-view-progress"><span data-rv-count>1 / 3</span><div><i data-rv-bar></i></div></div><div class="real-view-lens"><small data-rv-lens-id>NEXT</small><h3 data-rv-lens-name>次の一手</h3><p data-rv-question></p></div><label><span>この型なら、どんな別の見方ができる？</span><textarea data-rv-text maxlength="180" placeholder="事実を否定せず、別の意味を1つ。"></textarea></label><button class="real-view-primary" data-rv-next type="button" disabled>次の見方 →</button></section>
    <section data-rv-step="choose" hidden><p>3つとも正解にしなくていい。今いちばん役に立つ見方を1つ選ぶか、事実だけに戻る。</p><div class="real-view-list" data-rv-list></div><button class="real-view-neutral" data-rv-neutral type="button">どれも採用せず、事実だけに戻る</button><div class="real-view-meter"><div><span>いま、最初の見方に固定されている感じ</span><strong><b data-rv-after-v>7</b>/10</strong></div><input data-rv-after type="range" min="0" max="10" value="7"></div><small>下がらなくてもOK。見方を増やした後の数字をそのまま。</small><button class="real-view-primary" data-rv-finish type="button" disabled>この見方で終了</button></section>
    <section data-rv-step="done" hidden><h3 data-rv-done-title>意味を1つに固定しなくていい。</h3><div class="real-view-result"><div><small>FACT</small><p data-rv-fact></p></div><div class="first"><small>FIRST MEANING</small><p data-rv-first-out></p></div><div class="picked"><small>CHOSEN VIEW</small><strong data-rv-picked></strong></div></div><div class="real-view-all" data-rv-all></div><div class="real-view-delta" data-rv-delta></div><div class="real-view-history" data-rv-history hidden></div><button class="real-view-secondary" data-rv-again type="button">別の出来事でもう1回</button></section>
  </div>`;document.body.appendChild(modal);
    $('[data-rv-close]',modal).onclick=close;$('[data-rv-event]',modal).oninput=()=>{$('[data-rv-start]',modal).disabled=$('[data-rv-event]',modal).value.trim().length<2};$('[data-rv-before]',modal).oninput=e=>$('[data-rv-before-v]',modal).textContent=e.target.value;$('[data-rv-after]',modal).oninput=e=>$('[data-rv-after-v]',modal).textContent=e.target.value;$('[data-rv-start]',modal).onclick=startViews;$('[data-rv-text]',modal).oninput=()=>{$('[data-rv-next]',modal).disabled=$('[data-rv-text]',modal).value.trim().length<2};$('[data-rv-next]',modal).onclick=nextView;$('[data-rv-neutral]',modal).onclick=()=>selectChoice(-1);$('[data-rv-finish]',modal).onclick=finish;$('[data-rv-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function show(n){$$('[data-rv-step]',modal).forEach(s=>s.hidden=s.dataset.rvStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-rv-event]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-view-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-view-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();picks=[];views=[];chosen=-1;$('[data-rv-event]',modal).value='';$('[data-rv-first]',modal).value='';$('[data-rv-text]',modal).value='';$('[data-rv-before]',modal).value='7';$('[data-rv-after]',modal).value='7';$('[data-rv-before-v]',modal).textContent='7';$('[data-rv-after-v]',modal).textContent='7';$('[data-rv-start]',modal).disabled=true;$('[data-rv-next]',modal).disabled=true;$('[data-rv-finish]',modal).disabled=true;show('input')}
  function startViews(){picks=shuffle(LENSES).slice(0,3);views=[];$('[data-rv-event-out]',modal).textContent=$('[data-rv-event]',modal).value.trim();renderView();show('views');try{window.LevelUpTelemetry?.step?.('real-view-three')}catch{}}
  function renderView(){const i=views.length,l=picks[i];$('[data-rv-count]',modal).textContent=`${i+1} / 3`;$('[data-rv-bar]',modal).style.width=`${(i+1)/3*100}%`;$('[data-rv-lens-id]',modal).textContent=l.id.toUpperCase();$('[data-rv-lens-name]',modal).textContent=l.name;$('[data-rv-question]',modal).textContent=l.q;$('[data-rv-text]',modal).value='';$('[data-rv-next]',modal).disabled=true;$('[data-rv-next]',modal).textContent=i===2?'3つを並べる →':'次の見方 →';requestAnimationFrame(()=>$('[data-rv-text]',modal).focus({preventScroll:true}))}
  function nextView(){const i=views.length,v=$('[data-rv-text]',modal).value.trim();if(v.length<2)return;views.push({lens:picks[i],text:v});try{window.LevelUpTelemetry?.action?.(`real-view-${picks[i].id}`)}catch{};if(views.length<3){renderView();return}renderChoose()}
  function renderChoose(){chosen=-2;$('[data-rv-list]',modal).innerHTML=views.map((v,i)=>`<button type="button" data-rv-pick="${i}"><small>${v.lens.name}</small><strong>${esc(v.text)}</strong><span>採用</span></button>`).join('');$$('[data-rv-pick]',modal).forEach(b=>b.onclick=()=>selectChoice(Number(b.dataset.rvPick)));$('[data-rv-neutral]',modal).classList.remove('selected');const before=$('[data-rv-before]',modal).value;$('[data-rv-after]',modal).value=before;$('[data-rv-after-v]',modal).textContent=before;$('[data-rv-finish]',modal).disabled=true;show('choose')}
  function selectChoice(idx){chosen=idx;$$('[data-rv-pick]',modal).forEach(b=>b.classList.toggle('selected',Number(b.dataset.rvPick)===idx));$('[data-rv-neutral]',modal).classList.toggle('selected',idx===-1);$('[data-rv-finish]',modal).disabled=false;$('[data-rv-finish]',modal).textContent=idx===-1?'事実だけに戻って終了':'この見方で終了'}
  function finish(){if(chosen===-2)return;const event=$('[data-rv-event]',modal).value.trim(),first=$('[data-rv-first]',modal).value.trim()||'（言葉になる前の最初の評価）',before=Number($('[data-rv-before]',modal).value),after=Number($('[data-rv-after]',modal).value),delta=before-after,picked=chosen===-1?'事実だけに戻る':views[chosen].text;$('[data-rv-fact]',modal).textContent=event;$('[data-rv-first-out]',modal).textContent=first;$('[data-rv-picked]',modal).textContent=picked;$('[data-rv-all]',modal).innerHTML=views.map(v=>`<div><small>${v.lens.name}</small><span>${esc(v.text)}</span></div>`).join('');$('[data-rv-done-title]',modal).textContent=delta>0?'最初の意味への固定が、少しゆるんだ。':delta===0?'感覚は同じ。でも意味を3つ並べられた。':'少し重くなった。無理に意味を選ばなくていい。';$('[data-rv-delta]',modal).textContent=`意味の固定 ${before} → ${after}　／　3 VIEW`;save({delta,lenses:picks.map(x=>x.id),picked:chosen===-1?'fact':views[chosen].lens.id});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'viewpoint-exam',delta,picked:chosen===-1?'fact':views[chosen].lens.id}}));window.LevelUpTelemetry?.complete?.('real-view')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-rv-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const loosened=runs.filter(r=>Number(r.delta)>0).length;el.hidden=false;el.textContent=`現実の出来事 ${runs.length}件。${loosened}件で意味の固定が下がりました。`}catch{}}
  ensureLauncher();
})();
