(()=>{const $=q=>document.querySelector(q),screens=[...document.querySelectorAll('.screen')],show=id=>screens.forEach(s=>s.classList.toggle('on',s.id===id)),clamp=n=>Math.max(0,Math.min(100,n));
const Q=[
['今週末の仕事が重い。平日も埋まり、準備時間がほぼない。','やり残しも複数。休まないと持たない。',[['全部やる','毎晩延長して全部完成',-2,-3,'休息まで失った。'],['防衛線','必須準備だけ60分。残りは延期連絡',3,3,'守るものを限定し、残りを今日から逃がせた。'],['全部捨てる','何も連絡せず全部放置',-3,2,'壊れる仕事まで放置した。'],['考え続ける','頭の中で何度も並べ替える',-1,-2,'判断せず余力だけ減った。']]],
['明日朝の会議資料が未完成。別件の改善案も進めたい。','改善案は重要だが、明日の会議には不要。',[['両方完成','寝る時間を削って両方100点',-1,-3,'重要と緊急を同じ強さで抱えた。'],['守る＋捨てる','会議に必要な3ページだけ。改善案は明日',3,3,'明日の破綻だけ防いだ。'],['改善優先','楽しい改善案から始める',-3,-1,'近い破綻を後回しにした。'],['会議延期','条件確認せず会議ごと断る',0,1,'逃がす前に条件確認が必要。']]],
['返信待ちが3人。自分の作業も2件止まっている。','全部丁寧に返すと今日が返信だけで終わる。',[['即対応','3人全員へ長文返信',0,-2,'丁寧さが今日の本体を食べた。'],['逃がす','1人へ期限だけ返し、2人は明日と連絡',3,3,'対人WIPを残さず量を減らした。'],['無視','全部未読で自分の作業だけ',-2,2,'待たせるWIPが残った。'],['全部会議','3件とも打ち合わせ化',-1,-3,'未来の負荷を増やした。']]],
['「操作方法も調べて、売上案も出して」と頼まれた。','時間と報酬を考えると両方はやりたくない。',[['全部引受','期待に応えて両方やる',0,-3,'自分の境界が壊れた。'],['縮める＋逃がす','判断に必要な調査だけ。操作代行は別対応',3,3,'必要範囲だけ守れた。'],['全部断る','理由なく両方断る',-1,2,'必要な役割まで捨てた。'],['先延ばし','返事をしない',-2,-1,'対人WIPを増やした。']]],
['4時間しかないのに、6時間ぶん予定を入れていた。','予定どおりにできないことが確定。',[['圧縮','全部を2/3時間で雑に終える',0,-2,'量を減らしていない。'],['選び直す','今日の1件を守り、1件は30分版、残りは移す',3,3,'守る・縮める・逃がすを使えた。'],['延長','夜を2時間増やす',1,-3,'余力が消えた。'],['諦める','全部明日へ',-3,2,'今日壊れるものまで移した。']]],
['重要仕事が予想の3倍かかると分かった。','完成を目指すと他の約束に食い込む。',[['完遂','始めたから今日完成',0,-3,'他の防衛線を壊した。'],['最低限','今日必要な成果だけ切り出す',3,3,'完成ではなく必要条件へ縮めた。'],['中止','全部なかったことにする',-2,1,'必要な成果も失った。'],['分析','見積もりミスを1時間反省',-1,-2,'今日の時間が先に減った。']]],
['休みたい。でも止めると「全部崩れる」感じがする。','実際には締切が違う仕事が混ざっている。',[['休まない','不安がなくなるまで続ける',0,-3,'不安を終了条件にすると終わらない。'],['防衛条件','明日壊れる1件だけ20分。終わったら閉じる',3,3,'休息を防衛線の内側に入れた。'],['全部休む','締切確認せず一切見ない',-2,2,'壊れるものを未確認。'],['一覧化','100項目に分解してから休む',-1,-3,'整理が新しい仕事になった。']]],
['60点で提出できる資料を、まだ直し続けている。','別の必須仕事が残っている。',[['磨く','100点まで直す',0,-3,'完成主義が次の破綻を呼んだ。'],['出す','60点で提出して必須仕事へ',3,3,'十分な仕事を終えた。'],['破棄','最初から作り直す',-2,-3,'負荷を増やした。'],['保留','提出せずあとで考える',-1,-1,'終えられる仕事をWIPにした。']]]];
let i=0,score=0,safe=50,energy=50,lock=false;function meters(){safe=clamp(safe);energy=clamp(energy);$('#safeN').textContent=safe;$('#energyN').textContent=energy;$('#safeB').style.width=safe+'%';$('#energyB').style.width=energy+'%'}function render(){lock=false;let q=Q[i];$('#round').textContent=`${i+1}/${Q.length}`;$('#progress').style.width=(i/Q.length*100)+'%';$('#score').textContent=score+'pt';$('#title').textContent=q[0];$('#detail').textContent=q[1];$('#fb').className='feedback';$('#choices').innerHTML='';q[2].forEach((o,n)=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<span>PLAN ${n+1}</span><b>${o[1]}</b>`;b.onclick=()=>choose(n);$('#choices').appendChild(b)});meters()}function choose(n){if(lock)return;lock=true;let o=Q[i][2][n],good=o[2]>0&&o[3]>0;score+=good?1:0;safe+=o[2]*8;energy+=o[3]*8;meters();[...$('#choices').children].forEach((x,k)=>{x.disabled=true;if(k===n)x.classList.add(good?'good':'bad')});$('#fb').className='feedback on';$('#fbm').textContent=good?'✓':'×';$('#fbt').textContent=good?o[0]+'。その線でいい。':o[0]+'。まだ抱えすぎか、捨てすぎ。';$('#fbp').textContent=o[4]}
function done(){let r=Math.round(score/Q.length*100);$('#rate').textContent=r;$('#ring').style.setProperty('--rate',r);$('#rs').textContent=safe;$('#re').textContent=energy;$('#resultTitle').textContent=r>=75?'防衛ライン、作れた。':r>=50?'「全部」から離れ始めた。':'守るものを、もっと絞ろう。';$('#resultText').textContent=r>=75?'壊れるものだけ守って、余力を残す判断ができている。':'次は「今日やらないと本当に壊れる？」を先に見る。';show('result')}$('#next').onclick=()=>{if(++i>=Q.length)done();else render()};$('#start').onclick=()=>{i=score=0;safe=energy=50;render();show('game')};$('#again').onclick=()=>$('#start').click();
const KEY='levelup-zenbu-yaranai-v1';let tasks=[];const defs=()=>[{text:'',kind:'守る',min:''},{text:'',kind:'縮める',min:''},{text:'',kind:'逃がす',min:''}];function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');tasks=Array.isArray(x)&&x.length?x.slice(0,5):defs()}catch{tasks=defs()}}function save(){try{localStorage.setItem(KEY,JSON.stringify(tasks))}catch{}}function openReal(){load();renderTasks();show('real')}function renderTasks(){$('#tasks').innerHTML='';tasks.forEach((t,n)=>{let d=document.createElement('div');d.className='task';let inp=document.createElement('input');inp.placeholder=`仕事 ${n+1}：例）明日の会議資料`;inp.value=t.text;inp.oninput=()=>{t.text=inp.value;save()};d.append(inp);let cs=document.createElement('div');cs.className='chips';['守る','縮める','逃がす','捨てる'].forEach(k=>{let b=document.createElement('button');b.className='chip'+(t.kind===k?' on':'');b.textContent=k;b.onclick=()=>{t.kind=k;if(k==='捨てる')t.min='';save();renderTasks()};cs.append(b)});d.append(cs);if(t.kind!=='捨てる'){let m=document.createElement('div');m.className='mini';let x=document.createElement('input');x.placeholder=t.kind==='守る'?'今日守る最低限は？':t.kind==='縮める'?'どこまで小さくする？':'どこへ逃がす？';x.value=t.min;x.oninput=()=>{t.min=x.value;save()};m.append(x);d.append(m)}$('#tasks').append(d)})}$('#add').onclick=()=>{if(tasks.length<5){tasks.push({text:'',kind:'捨てる',min:''});renderTasks()}};$('#make').onclick=()=>{let a=tasks.filter(t=>t.text.trim());if(!a.length)return;$('#defense').innerHTML='';let labels={守る:'今日守る',縮める:'最低限へ縮める',逃がす:'今日から逃がす',捨てる:'今日はやらない'};a.forEach(t=>{let d=document.createElement('div');let note=t.kind==='捨てる'?'意図的に今日の対象外にする。':t.min||'最低限で止める。';d.innerHTML=`<b>${labels[t.kind]}</b><strong>${esc(t.text)}</strong><span>${esc(note)}</span>`;$('#defense').append(d)});let w=a.filter(t=>t.kind==='守る'||t.kind==='縮める').length;$('#finish').innerHTML=w?`<strong>${w}件だけ守ったら終了。</strong><br>それ以上は「今日の仕事」ではない。`:'<strong>今日は守る仕事なし。</strong><br>連絡・延期まで済ませたら閉じる。';show('summary')};$('#edit').onclick=()=>show('real');$('#save').onclick=()=>{save();$('#save').textContent='終了ラインを保存した ✓';setTimeout(()=>show('intro'),700)};$('#realStart').onclick=openReal;$('#toReal').onclick=openReal;$('#reset').onclick=()=>show('intro');function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}})();
