(()=>{
const app=document.querySelector('#app');
const TEST=new URLSearchParams(location.search).has('test');
const LEVELS=[
  ['反応','まず動く'],['気づき','止まって気づく'],['因果','なぜを追う'],['前提','そもそもを疑う'],
  ['鏡','自分の癖を見る'],['構造','仕組みを見る'],['切替','必要な段へ移る']
];
const SKILLS={1:['⚡','即応','考えるより先に安全・行動が必要な場面。'],2:['⏸','5秒空ける','反射の直前に小さな間をつくる。'],3:['↳','WHY ×3','原因を一つに決めつけず、因果をたどる。'],4:['？','そもそも？','置いている前提が本当か確認する。'],5:['◉','鏡','自分の感情・期待・バイアスを見る。'],6:['⌘','構造を見る','人ではなく、流れ・仕組み・関係を見る。'],7:['↕','降りる / 上がる','考え続けず、状況に合う思考へ切り替える。']};
const BANK=[
 {cat:'緊急',stress:3,q:'火災報知器。煙のにおいもする。最初は？',target:1,ex:'安全が最優先。検証より先に退避する場面では、①の即応が適切。',c:[[1,'まず安全な場所へ避難する'],[4,'誤報の可能性を検証する'],[6,'施設の防災体制を分析する']]},
 {cat:'対人',stress:3,q:'腹の立つメッセージが届いた。今すぐ返したい。',target:2,ex:'内容を考える前に反応を止める。まず間をつくるだけで選択肢が増える。',c:[[1,'その勢いで言い返す'],[2,'5秒だけ置いて、反応している自分に気づく'],[5,'なぜ自分は怒りやすい人間なのか考え込む']]},
 {cat:'仕事',stress:1,q:'売上が20%落ちた。最初の分析として強いのは？',target:3,ex:'まず流入・CVR・客単価など、結果を分解して因果の入口を探す。',c:[[1,'広告費を増やす'],[3,'流入・CVR・客単価のどこが落ちたか分ける'],[5,'自分が数字を怖がっていないか考える']]},
 {cat:'情報',stress:1,q:'「最近の若手はすぐ辞める」と言われた。',target:4,ex:'印象を事実として扱わず、「本当に増えている？」と前提を確かめる。',c:[[1,'最近の若手は根性がないと思う'],[3,'辞める理由を3つ考える'],[4,'そもそも退職率は本当に上がっているか確認する']]},
 {cat:'対人',stress:2,q:'ある人の提案だけ、なぜか毎回イラッとする。',target:5,ex:'相手を分析する前に、自分の期待や防御反応が判断へ混ざっていないかを見る。',c:[[1,'その人とは合わないと決める'],[5,'自分は何に反応している？と見る'],[6,'チームの意思決定構造を作り直す']]},
 {cat:'仕事',stress:2,q:'同じ入力ミスが、担当を替えても繰り返される。',target:6,ex:'人が替わっても起きるなら、個人より入力・確認フローの構造を見る価値が高い。',c:[[1,'担当者を注意する'],[3,'今回のミス原因だけを聞く'],[6,'入力から確認までの仕組みを見直す']]},
 {cat:'会議',stress:2,q:'30分議論したが、考える材料はもう十分ある。',target:7,ex:'高い段に居続けることが目的ではない。ここは分析を終えて実行へ降りる。',c:[[3,'さらに原因を掘る'],[6,'関係者構造をもう一度整理する'],[7,'思考を止め、決めた一手の実行へ切り替える']]},
 {cat:'緊急',stress:3,q:'本番サイトが落ちた。原因はまだ不明。',target:1,ex:'まず影響を止める・復旧する。詳細な根本原因分析はその後でいい。',c:[[1,'既知の復旧手順をまず実行する'],[4,'障害という前提自体を疑う'],[6,'組織の運用設計を議論する']]},
 {cat:'SNS',stress:2,q:'刺激的な見出しを見て「ひどい」と感じた。',target:2,ex:'拡散や断定の前に「今、自分は反応した」と気づく段を挟む。',c:[[1,'すぐ共有して批判する'],[2,'まず自分が煽られている可能性に気づく'],[6,'SNS産業全体の構造を分析する']]},
 {cat:'仕事',stress:1,q:'問い合わせが急に増えた。何から見る？',target:3,ex:'日時・商品・流入元・内容などを分け、増加と同時に変わった要因を探す。',c:[[1,'担当者を増員する'],[3,'いつ・どの商品・どの内容が増えたか分解する'],[4,'問い合わせは悪いこと、という前提を疑う']]},
 {cat:'会議',stress:1,q:'「この機能はユーザーが欲しがっている」と全員が話している。',target:4,ex:'共有前提ほど見落とされる。「誰が、どんな根拠で？」を確認する。',c:[[3,'実装工数を見積もる'],[4,'そもそもユーザーが欲しい根拠は何か確認する'],[6,'開発組織全体を再設計する']]},
 {cat:'家庭',stress:2,q:'約束どおり進まず「またか」と感じた。',target:5,ex:'相手を裁く前に、自分の期待値や「こうあるべき」が強くなっていないかを見る。',c:[[1,'約束を守るよう強く言う'],[5,'自分の期待と現実を分けて見る'],[6,'家庭のルールを全面改定する']]},
 {cat:'組織',stress:1,q:'毎月、締切直前だけチーム全体が残業になる。',target:6,ex:'毎月繰り返すなら個人の頑張りより、依存関係・承認・締切設計を見る。',c:[[1,'今月も気合いで乗り切る'],[3,'今月遅れた人を特定する'],[6,'前工程・承認・締切の構造を見る']]},
 {cat:'判断',stress:2,q:'分析を重ねすぎて、決断期限まで10分。',target:7,ex:'「もっと考える」が常に賢いわけではない。期限に合わせて決断モードへ切り替える。',c:[[4,'前提をもう一度全部洗う'],[6,'さらに全体構造を図にする'],[7,'十分な情報で決め、実行へ降りる']]},
 {cat:'対人',stress:3,q:'会議中、突然きつい言い方をされた。',target:2,ex:'その場で勝ち負けを決めず、まず自分の反応に気づく小さな間が有効。',c:[[1,'即座に言い返す'],[2,'一呼吸おいて、今反応していると気づく'],[4,'相手の発言の前提をその場で論破する']]},
 {cat:'学習',stress:1,q:'勉強しているのに問題が解けない。',target:3,ex:'「才能がない」と結論づけず、どの工程で詰まるか因果を分解する。',c:[[1,'向いていないと諦める'],[3,'理解・記憶・取り出しのどこで詰まるか見る'],[5,'自信のなさだけを掘り続ける']]},
 {cat:'買い物',stress:1,q:'「ランキング1位」だから良い商品だと思った。',target:4,ex:'ランキングの条件や母集団を確認し、「1位＝自分に最適」という前提を外す。',c:[[1,'1位なら買う'],[4,'何のランキングで、条件は何か確認する'],[6,'EC市場全体の競争構造を研究する']]},
 {cat:'仕事',stress:2,q:'自分の案が却下され、急に相手の案が悪く見える。',target:5,ex:'却下された感情が評価に混ざっていないかを見る。自分を外から観察する練習。',c:[[1,'相手の案の欠点を探す'],[5,'悔しさが判断を歪めていないか見る'],[6,'評価制度の構造まで話を広げる']]},
 {cat:'組織',stress:1,q:'優秀な人を採っても、半年で次々辞めていく。',target:6,ex:'個人の相性ではなく、採用後の配属・権限・評価・支援のつながりを見る。',c:[[1,'もっと優秀な人を採る'],[3,'辞めた人の理由を一人ずつ聞く'],[6,'配属・権限・評価・支援の構造を見る']]},
 {cat:'判断',stress:3,q:'子どもが道路へ飛び出しそう。頭には色々な考えが浮かぶ。',target:7,ex:'思考力は上に居続けることではない。状況を見て①の即応へ降りる切替そのものが重要。',c:[[5,'自分が焦る理由を見る'],[6,'道路環境の構造を考える'],[7,'考えるのをやめ、①の即応へ切り替えて止める']]}
];
let st={screen:'home',round:0,score:0,streak:0,best:0,answered:false,timer:0,started:0,questions:[],miss:{},stressCorrect:0,stressTotal:0,choiceTier:0};
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function clearTimer(){if(st.timer){clearTimeout(st.timer);st.timer=0}}
function vib(v=18){try{navigator.vibrate?.(v)}catch{}}
function shell(body,p=0){return `<main class="shell"><header class="top"><span class="brand">THINKING STAIRS</span><span class="round">${st.screen==='play'||st.screen==='feedback'?`${Math.min(st.round+1,10)} / 10`:''}</span></header><div class="progress" style="--p:${p}%"><i style="width:${p}%"></i></div>${body}</main>`}
function home(){clearTimer();st.screen='home';app.innerHTML=shell(`<section class="screen hero"><div class="eyebrow">思考は、高さじゃない。</div><h1 class="title">思考の階段</h1><p class="lead">7段を覚えるゲームではない。<br><b>その場に合う段へ、上がる。降りる。</b></p><div class="heroMark"><div class="stairsHero" aria-hidden="true">${'<span></span>'.repeat(7)}</div></div><div class="heroRule"><div><strong>10問</strong><small>短い状況判断</small></div><div><strong>3択</strong><small>反射で選ぶ</small></div><div><strong>↕</strong><small>上がるだけじゃない</small></div></div><button class="btn primary" data-a="start">階段を走る</button><p class="micro">目標：怒り・焦り・思い込みの中でも、必要な思考へ切り替える。</p></section>`)}
function start(){clearTimer();const selected=shuffle(BANK).slice(0,10);st={screen:'play',round:0,score:0,streak:0,best:0,answered:false,timer:0,started:Date.now(),questions:selected,miss:{},stressCorrect:0,stressTotal:0,choiceTier:0};play()}
function ladder(active=0,target=0){return `<div class="ladder">${LEVELS.map((x,i)=>{const n=i+1;return `<div class="step ${active===n?'active':''} ${target===n?'target':''}"><b>${n}</b><span>${escapeHtml(x[0])}</span></div>`}).join('')}</div>`}
function play(){clearTimer();st.screen='play';st.answered=false;const q=st.questions[st.round];const sec=TEST?99:(q.stress===3?6:7);const choices=shuffle(q.c);app.innerHTML=shell(`<section class="screen"><div class="hud"><span class="tag">${escapeHtml(q.cat)}</span><span class="stress ${q.stress===3?'hot':''}">負荷 ${'●'.repeat(q.stress)}${'○'.repeat(3-q.stress)}</span></div><h1 class="question">${escapeHtml(q.q)}</h1><div class="hint">いちばん今の状況に合う思考を選ぶ</div><div class="timer ${q.stress===3?'hot':''}" style="--seconds:${sec}s"><i></i></div><div class="gameArea">${ladder()}<div class="choiceWrap">${choices.map(c=>`<button class="choice" data-tier="${c[0]}"><span class="tier">${c[0]}</span><span class="choiceText">${escapeHtml(c[1])}</span></button>`).join('')}</div></div></section>`,st.round*10);if(!TEST)st.timer=setTimeout(()=>answer(0),sec*1000)}
function answer(tier){if(st.answered)return;st.answered=true;clearTimer();const q=st.questions[st.round];const correct=tier===q.target;st.choiceTier=tier;if(q.stress===3){st.stressTotal++;if(correct)st.stressCorrect++}if(correct){st.score+=10;st.streak++;st.best=Math.max(st.best,st.streak);vib([18,20,18])}else{st.streak=0;st.miss[q.target]=(st.miss[q.target]||0)+1;vib(35)}feedback(correct)}
function feedback(correct){st.screen='feedback';const q=st.questions[st.round];const skill=SKILLS[q.target];const targetChoice=q.c.find(c=>c[0]===q.target);app.innerHTML=shell(`<section class="screen"><div class="hud"><span class="tag">${escapeHtml(q.cat)}</span><span class="stress ${q.stress===3?'hot':''}">正解は ${q.target}段目</span></div><div class="gameArea">${ladder(st.choiceTier,q.target)}<div class="feedback"><div class="verdict ${correct?'':'bad'}"><div class="verdictMark">${correct?'✓':'↕'}</div><div><small>${correct?'GOOD SWITCH':'SWITCH HERE'}</small><strong>${correct?'その段で合ってる':'今回は別の段'}</strong></div></div><div class="answerLine"><b>${q.target}段目 ${escapeHtml(LEVELS[q.target-1][0])}</b><br>${escapeHtml(targetChoice[1])}</div><p class="explain">${escapeHtml(q.ex)}</p><div class="skill"><div class="skillIcon">${skill[0]}</div><div><span>今回の技</span><b>${escapeHtml(skill[1])}</b></div></div><div class="actions"><button class="btn primary" data-a="next">${st.round===9?'結果を見る':'次の状況へ'}</button></div></div></div></section>`,(st.round+1)*10)}
function next(){if(st.round>=9)return result();st.round++;play()}
function result(){clearTimer();st.screen='result';const pct=st.score;const stress=st.stressTotal?Math.round(st.stressCorrect/st.stressTotal*100):0;let weak=Number(Object.entries(st.miss).sort((a,b)=>b[1]-a[1])[0]?.[0]||0);if(!weak)weak=7;const skill=SKILLS[weak];let rank=pct>=90?'切替自在':pct>=70?'かなり柔軟':pct>=50?'階段を意識できている':'ここから反射化';let history={plays:0,best:0};try{history=JSON.parse(localStorage.getItem('thinking-stairs-stats-v1')||'null')||history}catch{}history.plays=(history.plays||0)+1;history.best=Math.max(history.best||0,pct);try{localStorage.setItem('thinking-stairs-stats-v1',JSON.stringify(history))}catch{}app.innerHTML=shell(`<section class="screen"><div class="eyebrow">10 SWITCHES COMPLETE</div><h1 class="title">思考の高さより、<br>切り替え。</h1><div class="resultHero"><div class="scoreRing" style="--score:${pct}"><div><strong>${pct}</strong><span>FIT SCORE</span></div></div><div class="resultCopy"><small>今回の状態</small><h2>${rank}</h2></div></div><div class="stats"><div class="stat"><strong>${st.best}</strong><span>BEST STREAK</span></div><div class="stat"><strong>${stress}%</strong><span>高負荷時</span></div><div class="stat"><strong>${history.best}</strong><span>自己BEST</span></div></div><div class="drill"><small>NEXT DRILL</small><strong>${skill[0]} ${escapeHtml(skill[1])}</strong><p>${escapeHtml(skill[2])}</p></div><div class="actions"><button class="btn primary" data-a="again">もう10問</button><button class="btn ghost" data-a="home">最初に戻る</button></div><p class="micro">上の段ほど偉いわけではない。必要なら①へ降りる。それも思考力。</p></section>`,100)}
app.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;const a=btn.dataset.a;if(a==='start'||a==='again')start();else if(a==='home')home();else if(a==='next')next();else if(btn.dataset.tier!==undefined)answer(Number(btn.dataset.tier))});
home();
})();
