import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const url=process.env.SUCCESS_MIND_URL||'http://127.0.0.1:4173/apps/success-mind/?test=1';
const artifacts=path.resolve('apps/success-mind/.artifacts');fs.mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(String(e)));
const fail=m=>{throw new Error(m)};const active=id=>page.locator(`#${id}.active`).isVisible();
async function choose(i){const p=page.locator('#choices .path');if(await p.count()!==2)fail('not two paths');await p.nth(i).click();await page.waitForTimeout(300)}
async function all(i){for(let n=0;n<12;n++)await choose(i);await page.waitForSelector('#resultScreen.active',{timeout:6000})}
try{
 await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>localStorage.clear());await page.reload({waitUntil:'networkidle'});
 if(!await active('startScreen'))fail('start missing');
 const first=await page.locator('#startScreen').innerText();if(!first.includes('成功マインド')||!first.includes('実収入の予測ではなく'))fail('first 10 seconds unclear');
 const sb=await page.locator('#startBtn').boundingBox();if(!sb||sb.height<48)fail('start target too small');await page.screenshot({path:path.join(artifacts,'01-start.png'),fullPage:true});
 await page.locator('#startBtn').click();await choose(1);await choose(1);if(await page.locator('#progressText').innerText()!=='03 / 12')fail('progress');await page.locator('#backBtn').click();if(await page.locator('#progressText').innerText()!=='02 / 12')fail('back');
 await page.reload({waitUntil:'networkidle'});await page.locator('#startBtn').click();await all(0);
 const low=await page.locator('#moneyValue').innerText();if(low!=='1億3,100万円'||await page.locator('#scoreValue').innerText()!=='10/100')fail('low result');
 if(await page.locator('#weakLabel').innerText()!=='最大のブレーキ')fail('low weakness');await page.locator('#upgradeActions button').nth(1).click();if(!(await page.locator('#upgradeMoney').innerText()).includes('+7,000万円'))fail('upgrade');
 await page.reload({waitUntil:'networkidle'});if(!await page.locator('#lastResultBtn').isVisible())fail('persistence');await page.locator('#lastResultBtn').click();if(await page.locator('#moneyValue').innerText()!==low)fail('revisit');
 await page.locator('#againBtn').click();await all(1);if(await page.locator('#moneyValue').innerText()!=='5億2,000万円'||await page.locator('#scoreValue').innerText()!=='100/100')fail('high result');
 if(await page.locator('#weakLabel').innerText()!=='弱点なし'||await page.locator('#topWeakness').innerText()!=='6項目すべて高水準')fail('fake weakness');await page.locator('#upgradeActions button').nth(1).click();if(!(await page.locator('#upgradeMoney').innerText()).includes('換算上限'))fail('cap');
 const hrefs=await page.locator('.source-links a').evaluateAll(ns=>ns.map(n=>n.href));if(!hrefs.some(x=>x.includes('iza.org/publications/dp/8235'))||!hrefs.some(x=>x.includes('jil.go.jp/kokunai/statistics/qa/a04.html')))fail('sources');
 await page.screenshot({path:path.join(artifacts,'02-result.png'),fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)>1)fail('390 overflow');
 await page.setViewportSize({width:360,height:800});await page.reload({waitUntil:'networkidle'});if(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)>1)fail('360 overflow');await page.locator('#startBtn').click();const boxes=await page.locator('#choices .path').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return[r.width,r.height]}));if(boxes.some(([w,h])=>w<300||h<72))fail('mobile targets');if(errors.length)fail(errors.join('\n'));
 const quality=`# 成功マインド診断 — Quality Report\n\n## Test environment\n- Browser/device: Playwright Chromium\n- Viewport: 390x844 and 360x800\n- Build/commit: ${process.env.GITHUB_SHA||'local'}\n- Production URL (if production verification is required): pre-production browser run\n\n## First-time clarity\n- Status: PASS\n- Observed evidence: First view showed the locked lifetime-earnings amount, title, one start action, 12-decision framing, and the non-prediction disclaimer.\n\n## Main interaction\n- Status: PASS\n- Observed evidence: All 12 scenes rendered exactly two future paths; both low and high trajectories completed.\n\n## Wrong / failure path\n- Status: NOT APPLICABLE\n- Observed evidence: Diagnostic has no right/wrong state; the all-low path was tested as the weak trajectory.\n\n## Correct / success path\n- Status: PASS\n- Observed evidence: High path produced 5億2,000万円 and 100/100 without inventing a weakness.\n\n## Back / exit\n- Status: PASS\n- Observed evidence: Back from question 3 restored question 2; LEVEL UP home link remains in the shell.\n\n## Reload\n- Status: PASS\n- Observed evidence: Reload returned to a usable start and preserved the completed low result in localStorage.\n\n## Revisit\n- Status: PASS\n- Observed evidence: Previous-result button reopened the saved 1億3,100万円 result after reload.\n\n## Mobile readability and tap targets\n- Status: PASS\n- Observed evidence: No horizontal overflow at 390 or 360px; start and path targets met minimum sizes.\n\n## Production verification\n- Status: NOT REQUIRED\n- Observed evidence: This gate is pre-production; live Firebase verification is a separate deployment requirement.\n\n## Final scores\nClarity: 9/10\nUsefulness: 8/10\nInteraction quality: 8/10\nUniqueness: 9/10\nRepeat value: 8/10\n\n## Final question\nIf I genuinely had this problem, would I open this app again?\n\nAnswer: YES\nReason: The amount hook is fast, and the six-axis weakest-capital result gives a concrete reason to rerun after changing decisions.\n\n## Remaining issues\n- Production deployment and live verification are separate from this pre-production gate.\n`;
 fs.writeFileSync('apps/success-mind/QUALITY.md',quality);fs.writeFileSync(path.join(artifacts,'summary.json'),JSON.stringify({url,low,errors},null,2));console.log('SUCCESS MIND BROWSER PASS');
}finally{await browser.close()}
