import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';

const url = process.env.LIFE_RPG_URL || 'http://127.0.0.1:4173/apps/life-rpg-status/';
const artifacts = path.resolve('apps/life-rpg-status/.artifacts');
await fs.mkdir(artifacts,{recursive:true});
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
const page = await context.newPage();
const must = async (condition,message)=>{if(!condition)throw new Error(message)};
try {
  await page.goto(url,{waitUntil:'networkidle'});
  await must(await page.locator('h1').first().textContent().then(t=>t?.includes('人生RPG')),'intro title missing');
  await must(await page.getByRole('button',{name:'自分のステータスを見る'}).isVisible(),'start CTA missing');
  await page.screenshot({path:path.join(artifacts,'01-intro.png'),fullPage:true});
  await page.getByRole('button',{name:'自分のステータスを見る'}).click();
  await must((await page.locator('#progressText').textContent())?.includes('01 / 12'),'Q1 did not start');
  await page.locator('.answer[data-value="4"]').click();
  await must((await page.locator('#progressText').textContent())?.includes('02 / 12'),'Q2 did not advance');
  await page.getByRole('button',{name:'← 1問戻る'}).click();
  await must((await page.locator('#progressText').textContent())?.includes('01 / 12'),'back did not return to Q1');
  await page.locator('.answer[data-value="3"]').click();
  for(let i=1;i<5;i++) await page.locator('.answer[data-value="3"]').click();
  await must((await page.locator('#progressText').textContent())?.includes('06 / 12'),'did not reach Q6');
  await page.reload({waitUntil:'networkidle'});
  await must((await page.locator('#progressText').textContent())?.includes('06 / 12'),'reload did not restore Q6');
  for(let i=5;i<12;i++) await page.locator('.answer[data-value="3"]').click();
  await must(await page.locator('#resultScreen').evaluate(el=>el.classList.contains('active')),'result screen not active');
  const job=(await page.locator('#job').textContent())?.trim();
  const ability=(await page.locator('#ability').textContent())?.trim();
  const lv=(await page.locator('#level').textContent())?.trim();
  await must(job && job!=='---','job missing');
  await must(ability && ability!=='---','ability missing');
  await must(lv?.startsWith('LV.'),'level missing');
  await must(await page.locator('#stats .bar').count()===5,'five stat bars missing');
  await must(await page.locator('#radar .shape').count()===1,'radar chart missing');
  await page.screenshot({path:path.join(artifacts,'02-result.png'),fullPage:true});
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'カードを画像でシェア'}).click();
  const download=await downloadPromise;
  await must(download.suggestedFilename()==='life-rpg-status.png','share PNG filename mismatch');
  const downloadPath=await download.path();
  const stat=await fs.stat(downloadPath);
  await must(stat.size>10000,'share PNG too small');
  await page.reload({waitUntil:'networkidle'});
  await must(await page.locator('#resultScreen').evaluate(el=>el.classList.contains('active')),'result did not survive reload');
  await page.getByRole('button',{name:'もう一度診断'}).click();
  await must((await page.locator('#progressText').textContent())?.includes('01 / 12'),'retry did not restart');
  await page.getByRole('button',{name:'最初から'}).click();
  await must(await page.getByRole('button',{name:'自分のステータスを見る'}).isVisible(),'reset did not return intro');
  await must(await page.locator('#lastResult').isVisible(),'previous result was not shown on revisit');
  const metrics=await page.evaluate(()=>({w:document.documentElement.scrollWidth,vw:window.innerWidth,answerRects:[...document.querySelectorAll('.answer')].map(el=>({w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height}))}));
  await must(metrics.w<=metrics.vw,'horizontal overflow on mobile');
  await must(metrics.answerRects.every(r=>r.h>=44&&r.w>=44),'tap target below 44px');
  console.log(JSON.stringify({status:'PASS',job,ability,lv,pngBytes:stat.size,mobile:metrics},null,2));
} finally {
  await browser.close();
}
