'use strict';
window.PROBLEM_SOLVING_CASES = [
    {
      id: 'deadline',
      kicker: 'CASE 01 / DEADLINE',
      title: '仕様変更で、納期が危ない',
      situation: '公開まで5日。未完了は8件。昨日、取引先から仕様変更が2件入り、担当者の1人は明日休み。「全部間に合わせないと信用を失う」と焦っている。',
      classify: [
        { text: '未完了タスクが8件ある', kind: 'solvable', why: '順番・担当・範囲を変えられる対象です。' },
        { text: '取引先が自分たちをどう評価するか', kind: 'unsolvable', why: '評価そのものは直接は操作できません。こちらの対応は選べます。' },
        { text: '公開まで5日ある', kind: 'solvable', why: '残り時間は変えにくくても、5日の使い方は設計できます。' },
        { text: '「全部間に合わないと終わりだ」という予測', kind: 'unsolvable', why: '予測を事実扱いせず、まず確認できる条件へ戻します。' },
      ],
      focus: [
        { text: '取引先に悪く思われないこと', score: 55, why: '相手の評価は結果であって、最初に操作する対象にはしにくい。' },
        { text: '8件のうち、公開に必須なものを確定すること', score: 100, why: '重要度と範囲を先に確定すると、残り5日の打ち手が見えます。' },
        { text: 'チーム全員の不安をなくすこと', score: 65, why: '不安への配慮は必要でも、まず作業の焦点を作る方が具体的です。' },
      ],
      define: [
        { text: '納期がやばい', score: 45, why: '広すぎて、何を変えればよいか分かりません。' },
        { text: '公開必須8件のうち、5日で完了できる範囲と担当が未確定', score: 100, why: '対象・期限・欠けている判断が1文で見えます。' },
        { text: '取引先の仕様変更が多すぎる', score: 60, why: '原因の一部ですが、相手を責めるだけでは次の一手になりません。' },
      ],
      ideas: [
        { id: 'd1', family: '範囲', lever: 'SCOPE', text: '公開必須 / 後回しを15分で分ける', impact: 5, feasibility: 5, load: 1 },
        { id: 'd2', family: '範囲', lever: 'SCOPE', text: '機能を全部残したまま、品質だけ落とす', impact: 2, feasibility: 3, load: 4 },
        { id: 'd3', family: '人', lever: 'PEOPLE', text: '休みの担当者のタスクを今日中に引き継ぐ', impact: 4, feasibility: 4, load: 2 },
        { id: 'd4', family: '人', lever: 'PEOPLE', text: '取引先に優先順位を確認し、後回し候補を合意する', impact: 5, feasibility: 4, load: 2 },
        { id: 'd5', family: '仕組み', lever: 'PROCESS', text: '残り5日は新規仕様を別キューへ置くルールにする', impact: 4, feasibility: 4, load: 2 },
        { id: 'd6', family: '仕組み', lever: 'PROCESS', text: '毎朝、未完了件数だけを共有する', impact: 2, feasibility: 5, load: 1 },
      ],
      plan: [
        { order: 1, text: '今から15分：8件を「公開必須 / 後回し候補」に分ける' },
        { order: 2, text: '今日中：取引先へ優先順位と後回し候補を確認する' },
        { order: 3, text: '確認後：担当を引き直し、5日分の順番を確定する' },
      ],
      outcome: '必須は8件ではなく5件と判明。2件は次回、1件は代替で合意できた。ところが必須5件のうち1件だけ、想定より工数が大きい。',
      review: [
        { text: '最初の計画が失敗だったと判断して、全部やり直す', score: 50, why: '一部の詰まりで計画全体を捨てる必要はありません。' },
        { text: '効いたことを残し、工数が大きい1件だけ再分解する', score: 100, why: 'レビューは「全部成功 / 全部失敗」ではなく、効いた部分を残して調整します。' },
        { text: '予定どおり進むまで、会議を増やして監視する', score: 60, why: '監視を増やす前に、詰まっている1件の具体的な障害を見ます。' },
      ],
      rule: '問題が大きいときは、全部を解く前に「今、動かせる1個」へ狭める。',
    },
    {
      id: 'sales',
      kicker: 'CASE 02 / SALES',
      title: '売上が落ちた。広告のせい？',
      situation: '今月の売上は前月比−18%。広告費はほぼ同じ。セッション数は−2%だが、購入率が3.8%から3.0%へ低下した。社内では「広告クリエイティブが弱い」という声が強い。',
      classify: [
        { text: '売上が前月比18%下がっている', kind: 'solvable', why: '結果そのものではなく、構成要因を分けて打ち手を探せます。' },
        { text: '購入率が3.8%から3.0%へ下がっている', kind: 'solvable', why: '変化が起きた場所を特定する手掛かりです。' },
        { text: '「広告クリエイティブが原因だ」という社内の意見', kind: 'unsolvable', why: '意見は仮説です。事実と分けて検証対象にします。' },
        { text: '先月とまったく同じ市場環境に戻すこと', kind: 'unsolvable', why: '外部環境を元に戻すより、今の数字で確認できる範囲を見ます。' },
      ],
      focus: [
        { text: '広告の見た目を今すぐ全部変える', score: 60, why: '原因を確定する前の全面変更は、学習できる情報も失います。' },
        { text: '購入率が落ちた場所を商品 / カート / 流入別に特定する', score: 100, why: '売上を構成する要素のうち、変化が大きい場所から絞れます。' },
        { text: '来月は売上を必ず戻す', score: 55, why: '目標だけでは、今日の問題定義になりません。' },
      ],
      define: [
        { text: '売上が悪い', score: 45, why: '広すぎます。売上のどの部分が変わったかまで下ろします。' },
        { text: 'セッションはほぼ同じだが、購入率が0.8pt落ちた理由が未特定', score: 100, why: '変化点と未解明の部分が具体的です。' },
        { text: '広告担当のクリエイティブ力が足りない', score: 45, why: '人の能力を原因と決めつける前に、データで変化点を確認します。' },
      ],
      ideas: [
        { id: 's1', family: '情報', lever: 'DATA', text: '商品別CVRを前月と比較し、落ち幅の大きい商品を出す', impact: 5, feasibility: 5, load: 1 },
        { id: 's2', family: '情報', lever: 'DATA', text: '流入元別CVRを比較し、広告以外も含めて見る', impact: 4, feasibility: 4, load: 2 },
        { id: 's3', family: '体験', lever: 'UX', text: 'スマホで購入まで通し、カートや在庫表示の変化を確認する', impact: 5, feasibility: 4, load: 2 },
        { id: 's4', family: '体験', lever: 'UX', text: 'LPの色だけを変えて反応を見る', impact: 2, feasibility: 4, load: 2 },
        { id: 's5', family: '人', lever: 'VOICE', text: '直近の問い合わせ・低評価レビューを20件読む', impact: 4, feasibility: 5, load: 2 },
        { id: 's6', family: '人', lever: 'VOICE', text: '会議で原因を多数決する', impact: 1, feasibility: 5, load: 2 },
      ],
      plan: [
        { order: 1, text: '30分：商品別・流入別のCVR差分を出す' },
        { order: 2, text: '差分上位の購入導線をスマホで再現する' },
        { order: 3, text: '原因候補を1つだけ修正し、影響を見る' },
      ],
      outcome: '購入率低下の7割が、主力2商品のスマホ購入導線に集中。直前に配送予定日の表示位置が変わっていた。',
      review: [
        { text: '広告クリエイティブも念のため全部変える', score: 55, why: '原因候補が絞れたなら、同時に多くを変えない方が判断しやすい。' },
        { text: '配送予定日の表示を戻し、主力2商品のCVR変化を追う', score: 100, why: '原因仮説と観測指標がつながっています。' },
        { text: '売上が戻るまで毎日会議する', score: 55, why: '会議回数より、仮説と検証の対応を明確にします。' },
      ],
      rule: '大きな結果が悪いときは、「どこで変わったか」を先に探す。',
    },
    {
      id: 'conflict',
      kicker: 'CASE 03 / TEAM',
      title: '同僚とのやり取りが噛み合わない',
      situation: '共同案件で同僚の返信が遅く、昨日の会議では「その進め方だと厳しい」と言われた。自分は「嫌われているのかも」と感じ、確認を後回しにしている。締切は3日後。',
      classify: [
        { text: '昨日「その進め方だと厳しい」と言われた', kind: 'solvable', why: '発言の意味や必要な修正点を確認できます。' },
        { text: '同僚が自分を嫌っているかどうか', kind: 'unsolvable', why: '相手の内心は直接は確定できません。行動と必要事項を扱います。' },
        { text: '締切が3日後', kind: 'solvable', why: '期限は近いですが、残り3日の連携方法は変えられます。' },
        { text: '過去の会議での表情を完全に正しく解釈すること', kind: 'unsolvable', why: '解釈を掘り続けるより、今確認できることへ戻します。' },
      ],
      focus: [
        { text: '嫌われているか確かめる', score: 55, why: '関係評価より、案件を進めるために必要な確認へ寄せます。' },
        { text: '今日中に、止まっている判断点を1つ確認する', score: 100, why: '締切に効き、自分から動かせる焦点です。' },
        { text: '今後二度と気まずくならない関係を作る', score: 50, why: '広すぎて、今日の一手に落ちません。' },
      ],
      define: [
        { text: '人間関係が悪い', score: 45, why: '範囲が広く、案件のどこが止まっているか見えません。' },
        { text: '締切3日前なのに、担当分担の最終確認が1点未合意', score: 100, why: '期限・対象・未決事項が具体的です。' },
        { text: '同僚の性格が合わない', score: 45, why: '性格ではなく、仕事上の合意点を扱います。' },
      ],
      ideas: [
        { id: 'c1', family: '伝え方', lever: 'MESSAGE', text: '未合意の1点だけ、Yes/Noで答えやすく聞く', impact: 5, feasibility: 5, load: 1 },
        { id: 'c2', family: '伝え方', lever: 'MESSAGE', text: '長文で自分の意図を全部説明する', impact: 2, feasibility: 4, load: 3 },
        { id: 'c3', family: '場', lever: 'CHANNEL', text: '5分だけ通話して判断点を決める', impact: 5, feasibility: 4, load: 2 },
        { id: 'c4', family: '場', lever: 'CHANNEL', text: '次の定例まで待つ', impact: 1, feasibility: 5, load: 1 },
        { id: 'c5', family: '役割', lever: 'ROLE', text: '決める人 / 作る人を一度書き出す', impact: 4, feasibility: 5, load: 1 },
        { id: 'c6', family: '役割', lever: 'ROLE', text: '上司に相手の性格を直してもらう', impact: 1, feasibility: 2, load: 4 },
      ],
      plan: [
        { order: 1, text: '今：止まっている判断点を1文にする' },
        { order: 2, text: '10分以内：Yes/No＋補足1行で確認を送る' },
        { order: 3, text: '返信が今日中になければ、5分通話を提案する' },
      ],
      outcome: '同僚は「嫌っている」のではなく、担当境界が曖昧で返答に迷っていたと判明。役割を1行で決めたら作業が再開した。',
      review: [
        { text: '自分の読み違いを責める', score: 55, why: '反省より、何が詰まりを解いたかを残します。' },
        { text: '次回から、感情の推測より未合意の仕事を先に特定する', score: 100, why: '今回効いた判断ルールを再利用できます。' },
        { text: '返信速度を細かく監視する', score: 50, why: '監視より、合意点と役割を明確にする方が再発防止につながります。' },
      ],
      rule: '人の気持ちを解こうとする前に、仕事上の未合意を1個見つける。',
    },
    {
      id: 'complaints',
      kicker: 'CASE 04 / CUSTOMER',
      title: '配送ミスの問い合わせが急増',
      situation: '倉庫切替後、誤配送率が1.2%から4.8%へ上昇。問い合わせは通常の2倍。現場は「新倉庫がダメ」と言い、倉庫側は「注文データの問題」と主張している。',
      classify: [
        { text: '倉庫切替後、誤配送率が4.8%へ上がった', kind: 'solvable', why: '発生箇所を分解し、工程ごとに確認できます。' },
        { text: 'どちらの部署が悪いかを先に決めること', kind: 'unsolvable', why: '責任判定を先にすると、原因特定が遅れやすい。まず工程を見ます。' },
        { text: '問い合わせが通常の2倍ある', kind: 'solvable', why: '発生量と内容を分類し、優先順位を付けられます。' },
        { text: '今週起きた誤配送をゼロ件だったことにする', kind: 'unsolvable', why: '過去は変えられません。再発と現在の顧客対応を扱います。' },
      ],
      focus: [
        { text: '新倉庫を元に戻す', score: 60, why: '大きな変更の前に、どの工程で誤りが増えたかを確認します。' },
        { text: '誤配送が「受注・出力・ピッキング・梱包」のどこで増えたか特定する', score: 100, why: '工程に分けると、責任論ではなく検証可能になります。' },
        { text: '問い合わせ担当の残業を減らす', score: 70, why: '重要ですが、誤配送の発生源を止める焦点も必要です。' },
      ],
      define: [
        { text: '倉庫トラブル', score: 45, why: '広すぎます。どの工程で何が起きているかまで下げます。' },
        { text: '倉庫切替後、SKU取り違えがどの工程で起きているか未特定', score: 100, why: '変化時点・エラー種類・未特定箇所が見えます。' },
        { text: '現場の連携不足', score: 55, why: '抽象的です。まずエラーが生まれる場所を特定します。' },
      ],
      ideas: [
        { id: 'q1', family: '追跡', lever: 'TRACE', text: '誤配送20件を受注→梱包まで逆追跡する', impact: 5, feasibility: 4, load: 2 },
        { id: 'q2', family: '追跡', lever: 'TRACE', text: '全注文を人手で再確認する', impact: 3, feasibility: 2, load: 5 },
        { id: 'q3', family: '防止', lever: 'GUARD', text: '取り違え上位SKUだけ二重確認を入れる', impact: 4, feasibility: 5, load: 2 },
        { id: 'q4', family: '防止', lever: 'GUARD', text: '全SKUの棚を一度に作り直す', impact: 3, feasibility: 1, load: 5 },
        { id: 'q5', family: '顧客', lever: 'CARE', text: '誤配送テンプレを用意し、交換案内を即返せるようにする', impact: 4, feasibility: 5, load: 1 },
        { id: 'q6', family: '顧客', lever: 'CARE', text: '原因確定まで返信を保留する', impact: 1, feasibility: 5, load: 2 },
      ],
      plan: [
        { order: 1, text: '今日午前：誤配送20件を工程別に逆追跡する' },
        { order: 2, text: '午後：発生上位SKUにだけ暫定ガードを入れる' },
        { order: 3, text: '同時に：顧客向け交換案内を統一して即応する' },
      ],
      outcome: '誤配送20件中15件が、似た商品コード2組のピッキングで発生。棚位置が隣接していた。',
      review: [
        { text: '倉庫全体を設計し直す', score: 60, why: '原因が狭く特定できたなら、まずそこへ効く対策を試せます。' },
        { text: '対象SKUの棚を離し、誤配送率が下がるか1週間確認する', score: 100, why: '原因仮説・対策・観測が1本につながっています。' },
        { text: '現場に注意喚起メールを毎日送る', score: 55, why: '注意より、間違いにくい工程へ変える方を先に検討できます。' },
      ],
      rule: '部署ではなく工程に分けると、責任論が検証可能な問題に変わる。',
    },
    {
      id: 'meetings',
      kicker: 'CASE 05 / TIME',
      title: '会議だらけで、重要な仕事が進まない',
      situation: '今日は会議が6時間。今週締切の企画書はまだ骨子だけ。定例会議が4つあり、そのうち2つは自分が発言しないことも多い。「全部出ないと情報を逃す」と感じている。',
      classify: [
        { text: '今日は会議が6時間ある', kind: 'solvable', why: '参加方法・優先順位・代理・資料共有を見直せます。' },
        { text: 'すべての情報を自分だけで漏れなく把握すること', kind: 'unsolvable', why: '完全把握を前提にせず、必要情報の取り方を設計します。' },
        { text: '企画書が骨子段階', kind: 'solvable', why: '今日どこまで進めるかを具体化できます。' },
        { text: '会議の主催者全員が自分の事情を察すること', kind: 'unsolvable', why: '察してもらうより、参加条件や欠席を自分から調整します。' },
      ],
      focus: [
        { text: '会議を全部なくす', score: 55, why: '極端に削る前に、重要仕事の時間を守る具体策へ落とします。' },
        { text: '今日、企画書のための90分を確保する', score: 100, why: '締切に直結し、自分から守れる焦点です。' },
        { text: '会議文化を会社全体で変える', score: 50, why: '大きすぎます。まず今日の時間から扱います。' },
      ],
      define: [
        { text: '時間がない', score: 45, why: '何に何時間使われ、何が不足しているかを具体化します。' },
        { text: '6時間の会議で、企画書の集中時間90分が確保できていない', score: 100, why: '不足時間と対象タスクが明確です。' },
        { text: '会社の会議が多すぎる', score: 60, why: '一般論より、自分の予定で変えられる範囲へ寄せます。' },
      ],
      ideas: [
        { id: 'm1', family: '削る', lever: 'CUT', text: '発言しない定例2つを欠席し、議事録だけ見る', impact: 5, feasibility: 4, load: 1 },
        { id: 'm2', family: '削る', lever: 'CUT', text: '昼休みを削って企画書を書く', impact: 2, feasibility: 5, load: 4 },
        { id: 'm3', family: '守る', lever: 'BLOCK', text: '90分を先に予定表へ固定し、重ならない会議だけ残す', impact: 5, feasibility: 5, load: 1 },
        { id: 'm4', family: '守る', lever: 'BLOCK', text: '空いた時間ができたら企画書をやる', impact: 2, feasibility: 3, load: 1 },
        { id: 'm5', family: '任せる', lever: 'DELEGATE', text: '情報収集目的の会議は同僚に代理を頼む', impact: 4, feasibility: 4, load: 2 },
        { id: 'm6', family: '任せる', lever: 'DELEGATE', text: '企画書そのものを丸ごと他人へ投げる', impact: 2, feasibility: 2, load: 3 },
      ],
      plan: [
        { order: 1, text: '今：90分の集中枠を予定表に入れる' },
        { order: 2, text: '重なる定例2つへ、欠席＋議事録確認を伝える' },
        { order: 3, text: '90分で「骨子→見出し→冒頭1ページ」まで進める' },
      ],
      outcome: '90分で企画書の6割まで進んだ。欠席した会議の議事録確認は10分で済み、必要な決定は1件だけだった。',
      review: [
        { text: '今後すべての会議を断る', score: 55, why: '今回効いた条件を残し、必要な会議まで切らないようにします。' },
        { text: '「発言 / 決定がない会議は議事録で代替」を次週も試す', score: 100, why: '再利用できる参加基準に変えています。' },
        { text: '空き時間があればまた集中する', score: 60, why: '偶然の空き時間ではなく、重要仕事の枠を先に守ります。' },
      ],
      rule: '重要な仕事は、空いた時間に入れるのではなく先に時間を確保する。',
    },
    {
      id: 'newproduct',
      kicker: 'CASE 06 / NEW PRODUCT',
      title: '新商品の企画、意見が割れて決まらない',
      situation: '試作品はできたが、顧客インタビューはまだ0件。営業は「高機能が売れる」、開発は「価格を抑えるべき」、経営は「早く出したい」。会議を3回したが結論が出ない。',
      classify: [
        { text: '顧客インタビューが0件', kind: 'solvable', why: '今から情報を取りに行けます。' },
        { text: '社内の全員が同じ好みになること', kind: 'unsolvable', why: '好みを一致させるより、判断材料を共有します。' },
        { text: '試作品がある', kind: 'solvable', why: '見せて反応を確かめる資源として使えます。' },
        { text: '発売後の市場反応を100%予測すること', kind: 'unsolvable', why: '完全予測ではなく、小さく確かめる方法を選びます。' },
      ],
      focus: [
        { text: '社内で一番強い意見を決める', score: 55, why: '意見の強さではなく、判断に足りない情報を埋めます。' },
        { text: '次の判断に必要な顧客反応を最短で10件集める', score: 100, why: '不確実性を下げる具体的な一手です。' },
        { text: '発売後の売上を正確に予測する', score: 50, why: '精密予測より、今検証できる仮説を選びます。' },
      ],
      define: [
        { text: '企画がまとまらない', score: 50, why: 'なぜ決められないかまで具体化します。' },
        { text: '高機能と低価格のどちらを優先すべきか、顧客反応の材料がない', score: 100, why: '対立点と不足情報が明確です。' },
        { text: '会議の進め方が悪い', score: 55, why: '会議技法より、判断材料の欠落が中心問題です。' },
      ],
      ideas: [
        { id: 'n1', family: '聞く', lever: 'INTERVIEW', text: '既存顧客5人ずつに高機能 / 低価格の反応を聞く', impact: 5, feasibility: 4, load: 2 },
        { id: 'n2', family: '聞く', lever: 'INTERVIEW', text: '社内アンケートで人気案を決める', impact: 2, feasibility: 5, load: 1 },
        { id: 'n3', family: '見せる', lever: 'PROTOTYPE', text: '2案の簡易LPを見せ、どちらを選ぶか確かめる', impact: 5, feasibility: 4, load: 2 },
        { id: 'n4', family: '見せる', lever: 'PROTOTYPE', text: '完成品になるまで顧客には見せない', impact: 1, feasibility: 3, load: 4 },
        { id: 'n5', family: '小さく出す', lever: 'PILOT', text: '対象を限定して先行販売し、反応を取る', impact: 5, feasibility: 3, load: 3 },
        { id: 'n6', family: '小さく出す', lever: 'PILOT', text: '全国一斉発売して結果で決める', impact: 3, feasibility: 2, load: 5 },
      ],
      plan: [
        { order: 1, text: '今日：高機能 / 低価格の2案を1枚ずつ作る' },
        { order: 2, text: '3日以内：既存顧客10人へ見せて理由も聞く' },
        { order: 3, text: '反応を比較し、次に試す1案を決める' },
      ],
      outcome: '10人中7人が低価格案を選んだが、うち5人は「機能が不要」ではなく「使う場面が伝わらない」と回答した。',
      review: [
        { text: '7対3なので、すぐ低価格版に決定する', score: 70, why: '票だけでなく、選んだ理由に次の仮説があります。' },
        { text: '価値の伝え方を変えた高機能案をもう一度小さく試す', score: 100, why: '反応の理由から次の検証点を作っています。' },
        { text: '社内会議を追加して解釈を議論する', score: 60, why: '議論だけでなく、次の小さな検証へつなげます。' },
      ],
      rule: '意見が割れたら、誰が正しいかより「何を確かめれば決められるか」を探す。',
    },
  ];
