import {CONFIG,ENEMIES,UPGRADES} from './data.js';
import {createRenderer} from './render.js';
const $=id=>document.getElementById(id);const el={start:$('startScreen'),game:$('gameScreen'),startBtn:$('startButton'),best:$('bestLabel'),hp:$('gateHp'),bar:$('gateBarFill'),wave:$('waveNo'),kills:$('kills'),canvas:$('battle'),callout:$('callout'),banner:$('waveBanner'),oil:$('oilButton'),oilStatus:$('oilStatus'),cannon:$('cannonStatus'),reload:$('reloadFill'),up:$('upgradeOverlay'),cards:$('upgradeCards'),result:$('resultOverlay'),resultEye:$('resultEyebrow'),resultTitle:$('resultTitle'),resultWave:$('resultWave'),resultKills:$('resultKills'),lesson:$('lessonText'),retry:$('retryButton')};
const SCALE=new URLSearchParams(location.search).get('test')==='fast'?4:1;const laneX=(lane,w)=>w*(.2+lane*.3),gateY=h=>h-58;const R=createRenderer(el.canvas,laneX,gateY);let state,raf=0,last=performance.now(),simNow=last,audio=null,uid=0;
const best=()=>{try{return Number(localStorage.getItem('lastGateBestWave')||0)}catch{return 0}},saveBest=v=>{try{localStorage.setItem('lastGateBestWave',String(v))}catch{}};el.best.textContent=`BEST WAVE ${best()}`;
function tone(f=220,d=.08,t='sine',v=.04){try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=t;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}const buzz=p=>navigator.vibrate?.(p);
function init(){return{running:false,paused:false,wave:1,gate:CONFIG.baseGate,maxGate:CONFIG.baseGate,kills:0,enemies:[],spawnLeft:0,spawnTimer:0,spawnGap:950,waveStarted:false,cannonDamage:CONFIG.cannonDamage,reload:CONFIG.reload,blastRadius:CONFIG.blastRadius,lastShot:-99999,oilCooldown:CONFIG.oilCooldown,oilDps:32,lastOil:-99999,oilUntil:0,archerDps:5,archerClock:0,stunMs:0,upgradeLevels:{},shots:0,hits:0,biggestHit:0,damageTaken:0}}
function say(text,color='#fff'){el.callout.textContent=text;el.callout.style.color=color;el.callout.classList.remove('show');void el.callout.offsetWidth;el.callout.classList.add('show')}function banner(text){el.banner.textContent=text;el.banner.classList.remove('show');void el.banner.offsetWidth;el.banner.classList.add('show')}
function start(){state=init();state.running=true;simNow=performance.now();el.start.classList.add('hidden');el.result.classList.add('hidden');el.up.classList.add('hidden');el.game.classList.remove('hidden');R.resize();startWave(1);hud()}
function startWave(w){state.wave=w;state.waveStarted=true;state.spawnTimer=200;state.spawnLeft=10+w*3+(w===8?2:0);state.spawnGap=Math.max(430,930-w*55);banner(w===8?'FINAL WAVE — 破城槌接近':`WAVE ${w}`)}
function spawn(){const w=state.wave,r=Math.random();let type='raider';if(w>=7&&r>.78)type='brute';else if(w>=4&&r>.68)type='guard';else if(w>=2&&r>.8)type='guard';if(w===8&&state.spawnLeft===2)type='ram';const d=ENEMIES[type];state.enemies.push({id:++uid,type,lane:Math.floor(Math.random()*3),y:-35-Math.random()*30,hp:d.hp,maxHp:d.hp,attackClock:0,stunnedUntil:0,flash:0,burn:false,dead:false})}
function fire(x,y){if(!state?.running||state.paused)return;const ready=simNow-state.lastShot>=state.reload;R.blast(x,y,state.blastRadius,ready);if(!ready){tone(120,.04,'square',.018);say('装填中…','#d5dde7');return}state.lastShot=simNow;state.shots++;const {w}=R.size();let hit=0;for(const e of state.enemies){if(e.dead)continue;const ex=laneX(e.lane,w),d=Math.hypot(ex-x,e.y-y);if(d<=state.blastRadius+ENEMIES[e.type].r){const dmg=state.cannonDamage*Math.max(.72,1-d/(state.blastRadius*3))*(ENEMIES[e.type].shield?.78:1);e.hp-=dmg;e.flash=1;e.stunnedUntil=Math.max(e.stunnedUntil,simNow+state.stunMs);hit++;if(e.hp<=0){e.dead=true;state.kills++;R.burst(ex,e.y,ENEMIES[e.type].body,8)}else R.burst(ex,e.y,'#ffd082',4)}}state.hits+=hit;state.biggestHit=Math.max(state.biggestHit,hit);tone(hit>=4?95:125,.16,'sawtooth',.08);buzz(hit>=4?[20,20,35]:20);if(hit>=5)say(`一掃 ×${hit}`,'#ffd36b');else if(hit>=3)say(`まとめ撃ち ×${hit}`,'#ffe3a1');else if(hit===0)say('空振り','#a6b1bf');hud()}
function oil(){if(!state?.running||state.paused||simNow-state.lastOil<state.oilCooldown)return;state.lastOil=simNow;state.oilUntil=simNow+CONFIG.oilDuration;R.oil();say('油壺！','#ff9a52');tone(160,.08,'square',.06);buzz([20,25,20])}
function update(dt){if(!state?.running||state.paused)return;const {w,h}=R.size(),gy=gateY(h);if(state.spawnLeft>0){state.spawnTimer-=dt;if(state.spawnTimer<=0){spawn();state.spawnLeft--;state.spawnTimer=state.spawnGap*(.82+Math.random()*.36)}}state.archerClock+=dt;const arrow=state.archerClock>=250;if(arrow)state.archerClock=0;let nearest=null;for(const e of state.enemies)if(!e.dead&&(!nearest||e.y>nearest.y))nearest=e;for(const e of state.enemies){if(e.dead)continue;const d=ENEMIES[e.type];e.flash=Math.max(0,e.flash-dt/170);if(simNow<state.oilUntil&&e.y>gy-h*.31){e.burn=true;e.hp-=state.oilDps*dt/1000;if(e.hp<=0){e.dead=true;state.kills++;R.burst(laneX(e.lane,w),e.y,'#ff7c36',9);continue}}else e.burn=false;if(simNow<e.stunnedUntil)continue;if(e.y<gy-d.r-8)e.y+=d.speed*dt/1000;else{e.attackClock+=dt;if(e.attackClock>=d.attackMs){e.attackClock=0;state.gate-=d.damage;state.damageTaken+=d.damage;say(`門 -${d.damage}`,'#ff7568');R.burst(laneX(e.lane,w),gy,'#d1b18d',8);tone(70,.12,'square',.045);if(state.gate<=0){state.gate=0;end(false);break}}}}if(arrow&&nearest&&!nearest.dead){nearest.hp-=state.archerDps*.25;if(nearest.hp<=0){nearest.dead=true;state.kills++;R.burst(laneX(nearest.lane,w),nearest.y,'#d8d1bd',5)}}state.enemies=state.enemies.filter(e=>!e.dead||e.flash>0);if(state.spawnLeft===0&&state.enemies.every(e=>e.dead))clearWave();R.tick(dt);hud()}
function clearWave(){if(!state.running||!state.waveStarted)return;state.waveStarted=false;if(state.wave>=CONFIG.maxWave){end(true);return}state.paused=true;state.gate=Math.min(state.maxGate,state.gate+6);const pool=[...UPGRADES].sort(()=>Math.random()-.5).slice(0,3);el.cards.innerHTML='';for(const u of pool){const lv=state.upgradeLevels[u.id]||0,b=document.createElement('button');b.className='upgradeCard';b.innerHTML=`<span class="upgradeIcon">${u.icon}</span><span><strong>${u.title}</strong><small>${u.desc}</small></span><span class="upgradeLevel">Lv.${lv+1}</span>`;b.onclick=()=>{u.apply(state);state.upgradeLevels[u.id]=lv+1;el.up.classList.add('hidden');state.paused=false;startWave(state.wave+1);tone(520,.1)};el.cards.appendChild(b)}el.up.classList.remove('hidden')}
function end(win){if(!state?.running)return;state.running=false;state.paused=true;cancelAnimationFrame(raf);const b=Math.max(best(),state.wave);saveBest(b);el.best.textContent=`BEST WAVE ${b}`;el.resultEye.textContent=win?'FORTRESS HELD':'DEFENSE FAILED';el.resultTitle.textContent=win?'城門を守り切った':'城門、陥落';el.resultWave.textContent=`WAVE ${state.wave}`;el.resultKills.textContent=state.kills;el.lesson.textContent=win?`最大まとめ撃ち ${state.biggestHit}体。別の強化構成なら、もっと余裕を残せる。`:state.biggestHit<3?'敵が固まる前に撃ちすぎた。次は3体以上をまとめて狙う。':state.damageTaken>70?'城門前まで通した敵が多かった。油壺は門前に集まり始めた瞬間が強い。':'あと少し。火力だけでなく装填速度か門の耐久も混ぜると終盤が安定する。';el.result.classList.remove('hidden');tone(win?660:92,.28,win?'sine':'sawtooth',.055);buzz(win?[30,30,30]:[60,50,90])}
function hud(){if(!state)return;el.hp.textContent=Math.ceil(state.gate);el.wave.textContent=state.wave;el.kills.textContent=state.kills;const gp=Math.max(0,state.gate/state.maxGate*100);el.bar.style.width=`${gp}%`;el.bar.style.background=gp<30?'#e95f54':gp<60?'linear-gradient(90deg,#e95f54,#e5a63b)':'linear-gradient(90deg,#d44f49,#efb24a 52%,#67cf88)';const rp=Math.min(1,(simNow-state.lastShot)/state.reload);el.reload.style.width=`${rp*100}%`;el.cannon.textContent=rp>=1?'READY':`${Math.ceil((state.reload-(simNow-state.lastShot))/100)/10}s`;const op=Math.min(1,(simNow-state.lastOil)/state.oilCooldown),ready=op>=1;el.oil.disabled=!ready;el.oil.classList.toggle('ready',ready);el.oilStatus.textContent=ready?'READY':`${Math.ceil((state.oilCooldown-(simNow-state.lastOil))/1000)}s`}
function loop(now){const dt=Math.min(50,now-last);last=now;simNow+=dt*SCALE;update(dt*SCALE);R.draw(state,simNow);if(state?.running)raf=requestAnimationFrame(loop)}
el.canvas.addEventListener('pointerdown',e=>{if(!state?.running||state.paused)return;const r=el.canvas.getBoundingClientRect();fire(e.clientX-r.left,e.clientY-r.top)});el.oil.onclick=oil;el.startBtn.onclick=()=>{start();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)};el.retry.onclick=()=>{el.result.classList.add('hidden');start();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)};addEventListener('resize',R.resize);
window.__lastGate={getState:()=>state?JSON.parse(JSON.stringify({wave:state.wave,gate:state.gate,maxGate:state.maxGate,kills:state.kills,enemies:state.enemies.filter(e=>!e.dead).map(e=>({type:e.type,lane:e.lane,y:e.y,hp:e.hp,maxHp:e.maxHp})),spawnLeft:state.spawnLeft,paused:state.paused,running:state.running,biggestHit:state.biggestHit,shots:state.shots,damageTaken:state.damageTaken,upgradeLevels:state.upgradeLevels})):null,fire:(lane=1,y=.5)=>{const{w,h}=R.size();fire(laneX(lane,w),h*y)},oil};
