import {ENEMIES} from './data.js';
export function createRenderer(canvas,laneX,gateY){
  const ctx=canvas.getContext('2d'); const DPR=Math.min(devicePixelRatio||1,2); let particles=[],pulse=null;
  function size(){return{w:canvas.clientWidth,h:canvas.clientHeight}}
  function resize(){const r=canvas.getBoundingClientRect(),w=Math.max(320,r.width),h=Math.max(450,r.height);canvas.width=Math.floor(w*DPR);canvas.height=Math.floor(h*DPR);ctx.setTransform(DPR,0,0,DPR,0,0)}
  function add(x,y,color,n=6){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:-20-Math.random()*70,life:.3+Math.random()*.4,max:.7,color,r:1.5+Math.random()*3})}
  function blast(x,y,r,ready=true){pulse={x,y,t:performance.now(),ready};for(let i=0;i<24;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*90;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.35,max:.65,color:Math.random()>.35?'#f7bf57':'#d96038',r:2+Math.random()*4})}particles.push({x,y,vx:0,vy:0,life:.22,max:.22,color:'#fff0b8',r:r*.28})}
  function oil(){const {w,h}=size(),gy=gateY(h);for(let i=0;i<38;i++)particles.push({x:Math.random()*w,y:gy-Math.random()*h*.28,vx:(Math.random()-.5)*14,vy:-18-Math.random()*35,life:.6+Math.random()*.7,max:1.3,color:Math.random()>.4?'#ff7d32':'#ffc45d',r:2+Math.random()*4})}
  function tick(dt){for(const p of particles){p.life-=dt/1000;p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.vy+=24*dt/1000}particles=particles.filter(p=>p.life>0)}
  function gate(state,w,gy){const ratio=state.gate/state.maxGate;ctx.fillStyle='#272c31';ctx.fillRect(0,gy,w,58);for(let x=0;x<w;x+=44){ctx.fillStyle=x%88?'#44484a':'#393e41';ctx.fillRect(x,gy+2,40,20);ctx.fillRect(x+6,gy+26,40,17)}ctx.fillStyle='#14181b';ctx.fillRect(w*.39,gy+8,w*.22,50);ctx.fillStyle='#6d5540';for(let x=w*.405;x<w*.595;x+=11)ctx.fillRect(x,gy+10,7,48);if(ratio<.45){ctx.strokeStyle='#c6604c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(w*.3,gy+6);ctx.lineTo(w*.34,gy+22);ctx.lineTo(w*.31,gy+40);ctx.stroke()}}
  function enemy(e,w){const d=ENEMIES[e.type],x=laneX(e.lane,w),y=e.y;ctx.save();ctx.translate(x,y);if(e.flash>0)ctx.globalAlpha=.7+Math.sin(e.flash*20)*.3;if(e.burn){ctx.shadowColor='#ff6c29';ctx.shadowBlur=16}ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(0,d.r*.75,d.r*.9,d.r*.36,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=e.flash>0?'#fff1c7':d.body;ctx.beginPath();ctx.arc(0,0,d.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20252a';ctx.fillRect(-d.r*.45,-d.r*.95,d.r*.9,d.r*.45);if(d.shield){ctx.fillStyle='#9aa7b2';ctx.fillRect(-d.r-6,-d.r*.15,8,d.r*1.35)}if(e.type==='ram'){ctx.fillStyle='#3a3029';ctx.fillRect(-d.r*.85,-4,d.r*1.7,10);ctx.fillStyle='#b7a088';ctx.beginPath();ctx.moveTo(d.r*.8,-4);ctx.lineTo(d.r+12,1);ctx.lineTo(d.r*.8,6);ctx.fill()}if(e.hp<e.maxHp||e.type!=='raider'){ctx.fillStyle='#0009';ctx.fillRect(-d.r,-d.r-12,d.r*2,4);ctx.fillStyle=e.hp/e.maxHp<.35?'#e95e53':'#82d08e';ctx.fillRect(-d.r,-d.r-12,d.r*2*Math.max(0,e.hp/e.maxHp),4)}ctx.restore()}
  function draw(state,now){const {w,h}=size(),gy=gateY(h);ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#1f2c39');sky.addColorStop(.52,'#1a242c');sky.addColorStop(1,'#12181e');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#111820';for(let i=0;i<8;i++){const bx=(i*71+33)%w,bh=30+(i%3)*17;ctx.fillRect(bx,h*.12-bh,36,bh);ctx.fillRect(bx+12,h*.12-bh-12,12,12)}for(let lane=0;lane<3;lane++){const x=laneX(lane,w);ctx.beginPath();ctx.moveTo(x-38,0);ctx.lineTo(x-62,gy);ctx.lineTo(x+62,gy);ctx.lineTo(x+38,0);ctx.closePath();ctx.fillStyle=lane%2?'#4f473c55':'#594e4055';ctx.fill();ctx.strokeStyle='#ffffff0a';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,gy);ctx.stroke()}if(now<state.oilUntil){ctx.fillStyle='#ff672218';ctx.fillRect(0,gy-h*.31,w,h*.31);ctx.strokeStyle='#ff833888';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(0,gy-h*.31);ctx.lineTo(w,gy-h*.31);ctx.stroke();ctx.setLineDash([])}gate(state,w,gy);for(const e of state.enemies)if(!e.dead)enemy(e,w);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/(p.max||1));ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r||2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(pulse){const age=(performance.now()-pulse.t)/700;if(age<1){ctx.strokeStyle=pulse.ready?`rgba(255,210,115,${1-age})`:`rgba(170,180,194,${1-age})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(pulse.x,pulse.y,18+age*30,0,Math.PI*2);ctx.stroke()}else pulse=null}ctx.save();ctx.translate(w*.5,gy+6);ctx.fillStyle='#252c32';ctx.fillRect(-22,-28,44,36);ctx.fillStyle='#454e56';ctx.fillRect(-7,-49,14,28);ctx.restore()}
  return{resize,size,tick,draw,blast,oil,burst:add};
}
