(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const key='levelup-main-character-real-v1';
  const guards=['安全','健康','時間','お金','関係','今回は保留'];
  let modal,guard='安全';
  function ensureLauncher(){const retry=$('#retryBtn');if(!retry||$('[data-real-hero-launch]'))return;const b=document.createElement('button');b.type='button';b.className='primary real-hero-launch';b.dataset.realHeroLaunch='1';b.textContent='今の決断を1件、自分で決める →';b.addEventListener('click',open);retry.before(b)}
  function ensureModal(){if(modal)return modal;modal=document.createElement('div');modal.className='real-hero-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="real-hero-card" role="dialog" aria-modal="true" aria-labelledby="realHeroTitle"><div class="real-hero-head"><div><small>REAL LIFE / TAKE THE PEN</small><h2 id="realHeroTitle">大胆になるのではなく、<br>決定権を自分へ戻す。</h2></div><button data-rh-close type="button" aria-label="閉じる">×</button></div>
    <section data-rh-step="voices"><label><span>いま迷っていること</span><textarea data-rh-decision maxlength="180" placeholder="例：引き受けたくない仕事を断るか迷っている。"></textarea></label><label><span>周囲・世間・不安の声</span><textarea data-rh-others maxlength="180" placeholder="例：断ったら感じが悪いと思われるかも。普通は引き受けるべき。"></textarea></label><label><span>自分の声</span><textarea data-rh-self maxlength="180" placeholder="例：本当は今週の余白を守りたい。"></textarea></label><div class="real-hero-meter"><div><span>決定権が自分にある感覚</span><strong><b data-rh-before-v>4</b>/10</strong></div><input data-rh-before type="range" min="0" max="10" value="4"></div><button class="real-hero-primary" data-rh-next type="button" disabled>守るものを決める →</button></section>
    <section data-rh-step="choose" hidden><p>主人公＝無謀ではない。守るものも、自分で選ぶ。</p><div class="real-hero-guards">${guards.map((v,i)=>`<button type="button" data-rh-guard="${v}" class="${i===0?'selected':''}">${v}</button>`).join('')}</div><label><span>自分で決めるなら、今回はどうする？</span><textarea data-rh-choice maxlength="180" placeholder="例：今回は断る。代わりに来週ならできると伝える。"></textarea></label><label><span>30秒でできる最初の1手</span><input data-rh-action maxlength="100" placeholder="例：断り文を1行書く"></label><div class="real-hero-meter"><div><span>いま、決定権が自分にある感覚</span><strong><b data-rh-after-v>4</b>/10</strong></div><input data-rh-after type="range" min="0" max="10" value="4"></div><small>上がらなくてもOK。結論より「誰が決めたか」を見る。</small><button class="real-hero-primary" data-rh-finish type="button">決定権のBefore / Afterを見る</button></section>
    <section data-rh-step="done" hidden><h3 data-rh-done-title>自分の人生の決定権を、1件だけ取り戻した。</h3><div class="real-hero-result"><div><small>SCENE</small><p data-rh-decision-out></p></div><div class="voices"><small>OTHERS</small><p data-rh-others-out></p></div><div class="self"><small>MY VOICE</small><p data-rh-self-out></p></div><div class="decision"><small>MY DECISION / 守るもの：<b data-rh-guard-out></b></small><strong data-rh-choice-out></strong></div><div><small>FIRST CUT</small><p data-rh-action-out></p></div></div><div class="real-hero-delta" data-rh-delta></div><div class="real-hero-history" data-rh-history hidden></div><button class="real-hero-secondary" data-rh-again type="button">別の決断でもう1件</button></section></div>`;document.body.appendChild(modal);$('[data-rh-close]',modal).onclick=close;['decision','self'].forEach(id=>$(`[data-rh-${id}]`,modal).addEventListener('input',validate));$('[data-rh-before]',modal).oninput=e=>$('[data-rh-before-v]',modal).textContent=e.target.value;$('[data-rh-after]',modal).oninput=e=>$('[data-rh-after-v]',modal).textContent=e.target.value;$('[data-rh-next]',modal).onclick=()=>{const before=$('[data-rh-before]',modal).value;$('[data-rh-after]',modal).value=before;$('[data-rh-after-v]',modal).textContent=before;show('choose');try{window.LevelUpTelemetry?.step?.('real-hero-choice')}catch{}};$$('[data-rh-guard]',modal).forEach(b=>b.onclick=()=>{guard=b.dataset.rhGuard;$$('[data-rh-guard]',modal).forEach(x=>x.classList.toggle('selected',x===b))});$('[data-rh-finish]',modal).onclick=finish;$('[data-rh-again]',modal).onclick=reset;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('show'))close()});return modal}
  function validate(){const d=$('[data-rh-decision]',modal).value.trim(),s=$('[data-rh-self]',modal).value.trim();$('[data-rh-next]',modal).disabled=d.length<2||s.length<2}
  function show(n){$$('[data-rh-step]',modal).forEach(s=>s.hidden=s.dataset.rhStep!==n)}
  function open(){ensureModal();reset();modal.classList.add('show');modal.setAttribute('aria-hidden','false');requestAnimationFrame(()=>$('[data-rh-decision]',modal).focus({preventScroll:true}));try{window.LevelUpTelemetry?.action?.('real-hero-start')}catch{}}
  function close(){modal?.classList.remove('show');modal?.setAttribute('aria-hidden','true');$('[data-real-hero-launch]')?.focus({preventScroll:true})}
  function reset(){ensureModal();guard='安全';['decision','others','self','choice','action'].forEach(id=>$(`[data-rh-${id}]`,modal).value='');$('[data-rh-before]',modal).value='4';$('[data-rh-after]',modal).value='4';$('[data-rh-before-v]',modal).textContent='4';$('[data-rh-after-v]',modal).textContent='4';$('[data-rh-next]',modal).disabled=true;$$('[data-rh-guard]',modal).forEach(b=>b.classList.toggle('selected',b.dataset.rhGuard==='安全'));show('voices')}
  function finish(){const decision=$('[data-rh-decision]',modal).value.trim(),others=$('[data-rh-others]',modal).value.trim()||'（周囲の声は未記入）',self=$('[data-rh-self]',modal).value.trim(),choice=$('[data-rh-choice]',modal).value.trim(),action=$('[data-rh-action]',modal).value.trim()||'決めた内容を1行だけメモする';if(choice.length<2){$('[data-rh-choice]',modal).focus();return}const before=Number($('[data-rh-before]',modal).value),after=Number($('[data-rh-after]',modal).value),delta=after-before;$('[data-rh-decision-out]',modal).textContent=decision;$('[data-rh-others-out]',modal).textContent=others;$('[data-rh-self-out]',modal).textContent=self;$('[data-rh-choice-out]',modal).textContent=choice;$('[data-rh-action-out]',modal).textContent=action;$('[data-rh-guard-out]',modal).textContent=guard;$('[data-rh-done-title]',modal).textContent=delta>0?'決定権が、自分側へ少し戻った。':delta===0?'感覚は同じ。でも自分の結論を言葉にした。':'まだ自分で決めた感じが弱い。結論を急がず、自分の声だけ残す。';$('[data-rh-delta]',modal).textContent=`決定権 ${before} → ${after}　／　守る：${guard}`;save({delta,guard});history();show('done');try{window.dispatchEvent(new CustomEvent('levelup:real-bridge-complete',{detail:{slug:'main-character',delta,guard}}));window.LevelUpTelemetry?.complete?.('real-hero')}catch{}}
  function save(run){try{const prev=JSON.parse(localStorage.getItem(key)||'[]'),runs=Array.isArray(prev)?prev.slice(-19):[];runs.push({...run,at:Date.now()});localStorage.setItem(key,JSON.stringify(runs))}catch{}}
  function history(){try{const runs=JSON.parse(localStorage.getItem(key)||'[]'),el=$('[data-rh-history]',modal);if(!Array.isArray(runs)||!runs.length){el.hidden=true;return}const up=runs.filter(r=>Number(r.delta)>0).length;el.hidden=false;el.textContent=`現実の決断 ${runs.length}件。${up}件で決定権の感覚が上がりました。`;}catch{}}
  ensureLauncher();
})();
