(() => {
  const $ = (sel) => document.querySelector(sel);
  const $$ = (sel) => [...document.querySelectorAll(sel)];
  const storageKey = 'levelup-ten-years-back-v1';
  const yearNow = new Date().getFullYear();
  const state = { age: null, offset: 0, phase: 'forward', mood: '', regret: '', action: '', saved: false };
  const moodOptions = ['めちゃくちゃ嬉しい','まだ間に合う','時間を無駄にしたくない','会いたい人が浮かんだ','やりたいことが出てきた','なんでもできそう'];
  const regretHelpers = [['家族','家族との時間をもっと大事にすればよかった'],['会いたい人','会いたい人に会えばよかった'],['挑戦','やりたいことにもっと挑戦すればよかった'],['健康','体をもっと大切にすればよかった'],['仕事','本当にやりたい仕事に時間を使えばよかった'],['遊び','もっと遊んで、楽しめばよかった'],['旅','行きたい場所へ行けばよかった'],['自分','人の目より自分の気持ちを選べばよかった']];
  const actionSizer = [['10分にする',(v)=>`10分だけ、${trimLead(v)}`],['最初の1個にする',(v)=>`まず1個だけ、${trimLead(v)}`],['連絡1通にする',()=> '会いたい人・必要な人に、連絡を1通送る']];
  function trimLead(value){return String(value||'').replace(/^(もっと|まず|今日|10分だけ)[、\s]*/u,'').trim()||'やる'}
  function readStore(){try{const raw=JSON.parse(localStorage.getItem(storageKey)||'{}');return raw&&typeof raw==='object'?raw:{}}catch{return {}}}
  function writeStore(next){try{localStorage.setItem(storageKey,JSON.stringify(next));return true}catch{return false}}
  function showScreen(id){$$('.screen').forEach((screen)=>screen.classList.toggle('active',screen.id===id));window.scrollTo({top:0,behavior:'smooth'})}
  function vibrate(pattern=10){try{navigator.vibrate?.(pattern)}catch{}}
  function flash(){const el=$('#flash');el.classList.remove('on');void el.offsetWidth;el.classList.add('on')}
  function escapeHtml(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function setupReturnContext(){const store=readStore();if(store.sessions>0){const note=$('#returnNote');note.hidden=false;note.innerHTML=`<strong>未来から戻ってきて ${store.sessions+1}回目。</strong><br>前回の一手を思い出してから、また10年を取り戻せます。`}if(store.lastAction){const last=$('#lastAction');last.hidden=false;last.innerHTML=`前回、10歳若い自分が決めたこと<br><strong>${escapeHtml(store.lastAction)}</strong>`}if(store.lastAge)$('#ageInput').value=store.lastAge}
  function renderDots(){$('#yearDots').innerHTML=Array.from({length:11},()=>'<i></i>').join('')}
  function updateTimeline(){const offset=Number($('#timeRange').value);state.offset=offset;$('#yearLabel').textContent=yearNow+offset;$('#ageHero').textContent=state.age+offset;$('#ageCaption').textContent=offset===0?'今のあなた':offset===10?'10年後のあなた':`${offset}年後`;$('#ageStage').style.transform=`scale(${1+(offset/10)*.08})`;if(state.phase==='forward'){$('#timelineInstruction').textContent=offset<10?'指で、10年先まで時間を進める。':'着きました。ここが10年後です。';if(offset===10){$('#futureMessage').hidden=false;$('#futureAgeLine').textContent=`${state.age+10}歳のあなたです。`;vibrate([20,40,20])}else{$('#futureMessage').hidden=true}}else{$('#timelineInstruction').textContent=offset>0?'今度は、時間を今日まで巻き戻す。':'戻ってきました。';$('#futureMessage').hidden=true;if(offset===0)revealReborn()}}
  function revealReborn(){if(state.phase==='done')return;state.phase='done';flash();vibrate([30,40,30,40,60]);$('#fromFutureLine').textContent=`${state.age+10}歳だったあなたは、`;$('#rebornAge').textContent=state.age;setTimeout(()=>showScreen('rebornScreen'),260)}
  function renderMoodChoices(){$('#moodChoices').innerHTML=moodOptions.map((mood)=>`<button class="choice" type="button" data-mood="${escapeHtml(mood)}">${escapeHtml(mood)}</button>`).join('');$$('#moodChoices .choice').forEach((btn)=>btn.addEventListener('click',()=>{$$('#moodChoices .choice').forEach((other)=>other.classList.remove('selected'));btn.classList.add('selected');state.mood=btn.dataset.mood;$('#moodOther').value='';$('#moodNextBtn').disabled=false;vibrate()}))}
  function renderRegretHelpers(){$('#regretHelpers').innerHTML=regretHelpers.map(([label,value])=>`<button class="helper-chip" type="button" data-value="${escapeHtml(value)}">${escapeHtml(label)}</button>`).join('');$$('#regretHelpers .helper-chip').forEach((btn)=>btn.addEventListener('click',()=>{$('#regretInput').value=btn.dataset.value;syncRegret();$('#regretInput').focus();vibrate()}))}
  function renderActionSizers(){$('#actionSizers').innerHTML=actionSizer.map(([label],index)=>`<button class="size-chip" type="button" data-index="${index}">${escapeHtml(label)}</button>`).join('');$$('#actionSizers .size-chip').forEach((btn)=>btn.addEventListener('click',()=>{const idx=Number(btn.dataset.index);const current=$('#actionInput').value.trim()||deriveAction(state.regret);$('#actionInput').value=actionSizer[idx][1](current).slice(0,100);syncAction();vibrate()}))}
  function deriveAction(regret){const text=String(regret||'').trim();if(/会いたい|家族|連絡/u.test(text))return '会いたい人に、連絡を1通送る';if(/健康|体|運動/u.test(text))return '10分だけ歩く';if(/旅|場所/u.test(text))return '行きたい場所を1つだけ調べる';if(/仕事|作り|書|挑戦|やりたい/u.test(text))return 'やりたいことの最初の1行だけ書く';return '未来の自分が後悔しないことを、10分だけやる'}
  function syncRegret(){state.regret=$('#regretInput').value.trim();$('#regretNextBtn').disabled=state.regret.length<2}
  function syncAction(){state.action=$('#actionInput').value.trim();$('#actionNextBtn').disabled=state.action.length<2}
  function buildResult(){$('#resultAge').textContent=state.age;$('#resultMood').textContent=state.mood?`いまの気分：「${state.mood}」`:'';$('#resultAction').textContent=state.action;$('#resultRegret').textContent=`10年後の後悔：「もっと、${state.regret}」`;state.saved=false;$('#savedNote').textContent='';$('#doneBtn').disabled=false;$('#doneBtn span').textContent='今日の一手を保存'}
  function saveResult(){if(state.saved)return;const store=readStore();const history=Array.isArray(store.history)?store.history.slice(-9):[];history.push({at:new Date().toISOString(),age:state.age,mood:state.mood,regret:state.regret,action:state.action});const persisted=writeStore({...store,sessions:Number(store.sessions||0)+1,lastAge:state.age,lastMood:state.mood,lastRegret:state.regret,lastAction:state.action,lastAt:new Date().toISOString(),history});if(!persisted){$('#savedNote').textContent='この環境では保存できません。結果はこの画面で使えます。';return}state.saved=true;$('#savedNote').textContent='保存しました。未来から戻りたい日に、またここへ。';$('#doneBtn').disabled=true;$('#doneBtn span').textContent='保存済み';vibrate([20,30,50])}
  function shareText(){return `私は10年後から戻ってきた。\n10歳若返った今日、やること：\n「${state.action}」\n\n10歳若返りました。 | LEVEL UP`}
  async function shareResult(){const text=shareText();try{if(navigator.share){await navigator.share({title:'10歳若返りました。',text,url:location.href});return}await navigator.clipboard.writeText(`${text}\n${location.href}`);$('#savedNote').textContent='シェア文をコピーしました。'}catch(err){if(err?.name!=='AbortError')$('#savedNote').textContent='シェアできませんでした。もう一度試してください。'}}
  function resetFlow({keepAge=true}={}){const oldAge=state.age;state.age=keepAge?oldAge:null;state.offset=0;state.phase='forward';state.mood='';state.regret='';state.action='';state.saved=false;$('#timeRange').value=0;$('#futureMessage').hidden=true;$('#moodOther').value='';$('#regretInput').value='';$('#actionInput').value='';$$('#moodChoices .choice').forEach((el)=>el.classList.remove('selected'));$('#moodNextBtn').disabled=true;$('#regretNextBtn').disabled=true;$('#actionNextBtn').disabled=true;showScreen('ageScreen');if(!keepAge)$('#ageInput').value='';$('#ageInput').focus()}
  $('#ageForm').addEventListener('submit',(event)=>{event.preventDefault();const age=Number($('#ageInput').value);if(!Number.isInteger(age)||age<10||age>110){$('#ageError').textContent='10〜110歳の範囲で入力してください。';return}$('#ageError').textContent='';state.age=age;state.phase='forward';$('#timelineEyebrow').textContent='MOVE THE CLOCK';$('#timeRange').value=0;$('#futureMessage').hidden=true;updateTimeline();showScreen('timelineScreen')});
  $('#timeRange').addEventListener('input',updateTimeline);
  $('#turnBackBtn').addEventListener('click',()=>{state.phase='backward';$('#timelineEyebrow').textContent='RETURN TO TODAY';$('#timelineInstruction').textContent='今度は、時間を今日まで巻き戻す。';$('#futureMessage').hidden=true;$('#timeRange').focus();vibrate()});
  $('#rebornNextBtn').addEventListener('click',()=>showScreen('moodScreen'));
  $('#moodOther').addEventListener('input',()=>{const value=$('#moodOther').value.trim();if(value){state.mood=value;$$('#moodChoices .choice').forEach((el)=>el.classList.remove('selected'));$('#moodNextBtn').disabled=false}else if(!$$('#moodChoices .choice.selected').length){state.mood='';$('#moodNextBtn').disabled=true}});
  $('#moodNextBtn').addEventListener('click',()=>{$('#futureAgeQuestion').textContent=`${state.age+10}歳`;showScreen('regretScreen');setTimeout(()=>$('#regretInput').focus(),120)});
  $('#regretInput').addEventListener('input',syncRegret);$('#regretNextBtn').addEventListener('click',()=>{state.regret=$('#regretInput').value.trim();$('#regretEcho').textContent=`もっと、${state.regret}`;$('#actionInput').value=deriveAction(state.regret);syncAction();showScreen('actionScreen')});
  $('#actionInput').addEventListener('input',syncAction);$('#actionNextBtn').addEventListener('click',()=>{state.action=$('#actionInput').value.trim();buildResult();flash();showScreen('resultScreen')});
  $('#doneBtn').addEventListener('click',saveResult);$('#shareBtn').addEventListener('click',shareResult);$('#againBtn').addEventListener('click',()=>resetFlow({keepAge:true}));$('#resetBtn').addEventListener('click',()=>resetFlow({keepAge:false}));
  renderDots();renderMoodChoices();renderRegretHelpers();renderActionSizers();setupReturnContext();
})();
