(() => {
  'use strict';
  const canvas=document.getElementById('world'),ctx=canvas.getContext('2d');
  const els={life:document.getElementById('lifeScore'),balance:document.getElementById('balanceScore'),cycle:document.getElementById('cycleScore'),nutrient:document.getElementById('nutrientValue'),tray:document.getElementById('speciesTray'),message:document.getElementById('message'),intro:document.getElementById('intro'),complete:document.getElementById('complete'),best:document.getElementById('bestBalance'),sound:document.getElementById('soundBtn'),objective:document.getElementById('objective'),objectiveIcon:document.getElementById('objectiveIcon'),objectiveTitle:document.getElementById('objectiveTitle'),objectiveDetail:document.getElementById('objectiveDetail'),objectiveBar:document.getElementById('objectiveBar'),chainHint:document.getElementById('chainHint')};
  const SPECIES=[
    {key:'algae',name:'藻・水草',sub:'二つの枝の入口',icon:'🪷',color:'#78c59d',target:70,unlock:()=>true,lock:'最初から',add:10},
    {key:'daphnia',name:'ミジンコ',sub:'藻を食べる',icon:'◌',color:'#d7d89d',target:32,unlock:s=>s.algae>=38,lock:'水草 38+',add:8},
    {key:'snail',name:'タニシ',sub:'もう一つの草食者',icon:'🐌',color:'#c9aa78',target:18,unlock:s=>s.algae>=42,lock:'水草 42+',add:5},
    {key:'medaka',name:'メダカ',sub:'ミジンコを食べる',icon:'🐟',color:'#9fcdd4',target:16,unlock:s=>s.daphnia>=12,lock:'ミジンコ 12+',add:4},
    {key:'turtle',name:'カメ',sub:'タニシを食べる',icon:'🐢',color:'#8eb892',target:7,unlock:s=>s.snail>=7,lock:'タニシ 7+',add:2},
    {key:'kingfisher',name:'カワセミ',sub:'魚を狙う水辺の主役',icon:'🐦',color:'#76bcd0',target:5,unlock:s=>s.medaka>=7,lock:'メダカ 7+',add:1.5},
    {key:'fungi',name:'菌類',sub:'死を水と土へ戻す',icon:'🍄',color:'#c5a0ce',target:20,unlock:s=>s.detritus>=10,lock:'分解材料 10+',add:6}
  ];
  const state={algae:20,daphnia:0,snail:0,medaka:0,turtle:0,kingfisher:0,fungi:0,nutrients:50,detritus:1,water:55,sunlight:55,introduced:{algae:true},score:0,bestBalance:0,completionHold:0,completed:false,started:false,fx:true,time:0,flashes:[],hunts:[],particles:[]};
  const targets=Object.fromEntries(SPECIES.map(s=>[s.key,s.target])),seeds={},terrain=Array.from({length:90},(_,i)=>({x:pseudo(i*7.1),y:pseudo(i*13.3),a:pseudo(i*3.4)}));
  let lastObjective='',msgTimer,last=performance.now(),uiClock=0;
  function pseudo(n){return Math.abs(Math.sin(n*12.9898)*43758.5453)%1} function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function fmt(v){return Math.max(0,Math.round(v))} function rand(a,b){return a+Math.random()*(b-a)}
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',resize);resize();
  SPECIES.forEach(sp=>{const b=document.createElement('button');b.className='species-card';b.dataset.species=sp.key;b.innerHTML=`<span class="species-icon">${sp.icon}</span><span class="pop">0</span><b>${sp.name}</b><small>${sp.sub}</small><span class="lock-copy"></span><span class="foodline" style="background:${sp.color}"></span>`;b.addEventListener('click',()=>introduce(sp.key));els.tray.appendChild(b)});
  function whisper(text,kicker='変化'){clearTimeout(msgTimer);els.message.querySelector('.message-kicker').textContent=kicker;els.message.querySelector('strong').textContent=text;els.message.classList.add('is-visible');msgTimer=setTimeout(()=>els.message.classList.remove('is-visible'),2400)}
  function flashObjective(){els.objective.classList.remove('flash');void els.objective.offsetWidth;els.objective.classList.add('flash');setTimeout(()=>els.objective.classList.remove('flash'),500)}
  function burst(key,count){if(!state.fx)return;const sp=SPECIES.find(s=>s.key===key);for(let i=0;i<count;i++)state.particles.push({x:rand(.12,.88),y:rand(.46,.87),vx:rand(-.04,.04),vy:rand(-.12,-.03),life:rand(.5,1),color:sp?.color||'#fff'})}
  function introduce(key){if(!state.started)return;const sp=SPECIES.find(x=>x.key===key);if(!sp||!sp.unlock(state))return;const first=!state.introduced[key];state.introduced[key]=true;state[key]+=sp.add;burst(key,first?12:6);const copy={algae:'水草が広がり、二つの食物連鎖の土台になった。',daphnia:'ミジンコが藻を食べ始めた。魚につながる枝だ。',snail:'タニシが水草を食べ始めた。もう一つの枝が伸びた。',medaka:'メダカがミジンコを追い始めた。',turtle:'カメがタニシを探して池底を動き始めた。',kingfisher:'カワセミが水面を見張り始めた。',fungi:'菌類が落ち葉と死骸を水と土へ戻し始めた。'};whisper(copy[key],first?'新しい命':'個体数 +');flashObjective()}
  document.querySelectorAll('.action-card').forEach(btn=>btn.addEventListener('click',()=>{if(!state.started)return;const a=btn.dataset.action;btn.animate([{transform:'scale(.95)'},{transform:'scale(1)'}],{duration:180});if(a==='sun'){state.sunlight=clamp(state.sunlight+24,0,100);state.algae+=5;state.flashes.push({type:'sun',life:1});burst('algae',7);whisper('日差しで藻と水草が伸びた。','☀ 日差し')}else if(a==='rain'){state.water=clamp(state.water+30,0,100);state.nutrients=clamp(state.nutrients+4,0,100);state.algae+=2;state.flashes.push({type:'rain',life:1});whisper('雨で水が入れ替わり、水質が回復した。','💧 雨')}else{state.detritus+=9;state.flashes.push({type:'leaf',life:1});whisper(state.fungi>0?'菌類が落ち葉を分解している。':'落ち葉が沈んだ。分解者がいれば循環を閉じられる。','🍂 落ち葉')}flashObjective()}));
  document.getElementById('startBtn').addEventListener('click',()=>{state.started=true;els.intro.classList.remove('is-open');whisper('まず日差しで、水草を増やそう。','最初の一歩');document.querySelector('[data-action="sun"]').classList.add('pulse');setTimeout(()=>document.querySelector('[data-action="sun"]').classList.remove('pulse'),2400)});
  document.getElementById('continueBtn').addEventListener('click',()=>els.complete.classList.remove('is-open'));els.sound.addEventListener('click',()=>{state.fx=!state.fx;els.sound.textContent=state.fx?'✦':'·';els.sound.style.opacity=state.fx?'1':'.45'});
  function simulate(dt){if(!state.started)return;state.time+=dt;state.sunlight+=(55-state.sunlight)*dt*.04;state.water+=(58-state.water)*dt*.03;const env=(state.nutrients/100)*.4+(state.sunlight/100)*.3+(state.water/100)*.3,growth=2.4*env*(1-state.algae/125),eatD=.025*state.daphnia*state.algae/(20+state.algae),eatS=.02*state.snail*state.algae/(20+state.algae),aDeath=state.algae*.005;state.algae+=(growth-eatD-eatS-aDeath)*dt;state.nutrients-=Math.max(0,growth)*.035*dt;state.detritus+=aDeath*.2*dt;
    const dBirth=.15*state.daphnia*(state.algae/(20+state.algae)),dPred=.055*state.medaka*state.daphnia/(7+state.daphnia),dDeath=.04*state.daphnia;state.daphnia+=(dBirth-dPred-dDeath)*dt;state.detritus+=dDeath*.12*dt;
    const sBirth=.10*state.snail*(state.algae/(25+state.algae)),sPred=.06*state.turtle*state.snail/(5+state.snail),sDeath=.03*state.snail;state.snail+=(sBirth-sPred-sDeath)*dt;state.detritus+=sDeath*.3*dt;
    const mBirth=.11*state.medaka*(state.daphnia/(8+state.daphnia)),mPred=.065*state.kingfisher*state.medaka/(4+state.medaka),mDeath=.032*state.medaka;state.medaka+=(mBirth-mPred-mDeath)*dt;state.detritus+=mDeath*.3*dt;
    const tBirth=.06*state.turtle*(state.snail/(5+state.snail)),tDeath=.026*state.turtle;state.turtle+=(tBirth-tDeath)*dt;state.detritus+=tDeath*.7*dt;
    const kBirth=.05*state.kingfisher*(state.medaka/(4+state.medaka)),kDeath=.03*state.kingfisher;state.kingfisher+=(kBirth-kDeath)*dt;state.detritus+=kDeath*.8*dt;
    const fGrowth=.12*state.fungi*(state.detritus/(7+state.detritus)),fDeath=.045*state.fungi,decomp=Math.min(state.detritus,.17*state.fungi*state.detritus/(6+state.detritus));state.fungi+=(fGrowth-fDeath)*dt;state.detritus-=decomp*dt;state.nutrients+=decomp*.95*dt;
    SPECIES.forEach(sp=>state[sp.key]=clamp(state[sp.key],0,180));state.detritus=clamp(state.detritus,0,90);state.nutrients=clamp(state.nutrients,2,100);const bal=getBalance(),web=getWeb();state.score+=dt*(.25+bal/215+web/250);state.bestBalance=Math.max(state.bestBalance,bal);maybeHunt(dt);updateFx(dt);const all=SPECIES.every(sp=>state.introduced[sp.key]&&state[sp.key]>.35);if(all&&bal>=74&&web>=88){state.completionHold+=dt;if(state.completionHold>10&&!state.completed){state.completed=true;els.best.textContent=`${Math.round(state.bestBalance)}%`;els.complete.classList.add('is-open');burst('algae',25);localStorage.setItem('cycle-biome','pond-complete')}}else state.completionHold=Math.max(0,state.completionHold-dt*.7)}
  function getBalance(){const active=SPECIES.filter(sp=>state.introduced[sp.key]);if(!active.length)return 0;let sum=0;active.forEach(sp=>{const ratio=state[sp.key]/sp.target;sum+=clamp(1-Math.abs(Math.log(Math.max(.02,ratio)))*.55,0,1)});return clamp(sum/active.length*100,0,100)}
  function getWeb(){const living=['algae','daphnia','snail','medaka','turtle','kingfisher'],present=living.filter(k=>state.introduced[k]&&state[k]>.4).length;return clamp(present/6*60+(state.introduced.fungi&&state.fungi>.5?25:0)+(state.nutrients>18&&state.nutrients<88?10:3)+(state.detritus<35?5:1),0,100)}
  function health(k){const r=state[k]/targets[k];return r<.68?'少ない':r>1.38?'多すぎ':'安定'}
  function finalCorrection(){let worst=null;SPECIES.forEach(sp=>{const r=state[sp.key]/sp.target,dist=Math.abs(Math.log(Math.max(.03,r)));if(!worst||dist>worst.dist)worst={sp,r,dist}});if(!worst||worst.dist<.34)return null;const {sp,r}=worst;if(r<1)return{key:`low-${sp.key}`,icon:sp.icon,title:`${sp.name}が少ない`,detail:`${sp.name}カードで少し増やす`,progress:clamp(r,0,1),target:sp.key};const predator={algae:'daphnia',daphnia:'medaka',snail:'turtle',medaka:'kingfisher'}[sp.key];if(predator){const p=SPECIES.find(x=>x.key===predator);return{key:`high-${sp.key}`,icon:p.icon,title:`${sp.name}が増えすぎ`,detail:`${p.name}を増やして食べてもらう`,progress:clamp(1/r,0,1),target:predator}}return{key:`watch-${sp.key}`,icon:'◌',title:`${sp.name}が多め`,detail:'少し見守ると自然に落ち着く',progress:clamp(1/r,0,1),target:'watch'}}
  function objective(){if(state.algae<38)return{key:'algae38',icon:'🪷',title:'水辺を育てる',detail:`水草 ${fmt(state.algae)} / 38`,progress:state.algae/38,target:'algae'};if(!state.introduced.daphnia)return{key:'add-daphnia',icon:'◌',title:'ミジンコを迎える',detail:'魚につながる枝の始まり',progress:1,target:'daphnia'};if(state.daphnia<12)return{key:'daphnia12',icon:'◌',title:'ミジンコを増やす',detail:`ミジンコ ${fmt(state.daphnia)} / 12`,progress:state.daphnia/12,target:'daphnia'};if(!state.introduced.medaka)return{key:'add-medaka',icon:'🐟',title:'メダカを迎える',detail:'最初の枝を伸ばす',progress:1,target:'medaka'};if(!state.introduced.snail)return{key:'add-snail',icon:'🐌',title:'別の枝をつくる',detail:'タニシを迎える',progress:1,target:'snail'};if(state.snail<7)return{key:'snail7',icon:'🐌',title:'タニシを増やす',detail:`タニシ ${fmt(state.snail)} / 7`,progress:state.snail/7,target:'snail'};if(!state.introduced.turtle)return{key:'add-turtle',icon:'🐢',title:'カメを迎える',detail:'貝の枝を伸ばす',progress:1,target:'turtle'};if(state.medaka<7)return{key:'medaka7',icon:'🐟',title:'メダカを増やす',detail:`メダカ ${fmt(state.medaka)} / 7`,progress:state.medaka/7,target:'medaka'};if(!state.introduced.kingfisher)return{key:'add-kingfisher',icon:'🐦',title:'カワセミを迎える',detail:'魚の枝を頂点までつなぐ',progress:1,target:'kingfisher'};if(state.detritus<10)return{key:'detritus10',icon:'🍂',title:'分解材料をつくる',detail:`落ち葉・死骸 ${fmt(state.detritus)} / 10`,progress:state.detritus/10,target:'detritus'};if(!state.introduced.fungi)return{key:'add-fungi',icon:'🍄',title:'菌類を迎える',detail:'二つの枝を循環で閉じる',progress:1,target:'fungi'};return finalCorrection()||{key:'stable',icon:'◌',title:'食物網を安定させる',detail:`BALANCE ${Math.round(getBalance())}% · WEB ${Math.round(getWeb())}%`,progress:Math.min(getBalance()/74,getWeb()/88),target:'stable'}}
  function updateUI(){const bal=getBalance(),web=getWeb(),obj=objective();els.life.textContent=Math.floor(state.score).toLocaleString('ja-JP');els.balance.textContent=`${Math.round(bal)}%`;els.cycle.textContent=`${Math.round(web)}%`;els.nutrient.textContent=Math.round(state.nutrients);els.objectiveIcon.textContent=obj.icon;els.objectiveTitle.textContent=obj.title;els.objectiveDetail.textContent=obj.detail;els.objectiveBar.style.width=`${clamp(obj.progress,0,1)*100}%`;if(obj.key!==lastObjective&&state.started){lastObjective=obj.key;flashObjective()};document.querySelectorAll('.species-card').forEach(card=>{const sp=SPECIES.find(x=>x.key===card.dataset.species),unlocked=sp.unlock(state),ready=unlocked&&!state.introduced[sp.key]&&obj.target===sp.key,correct=obj.target===sp.key&&state.introduced[sp.key];card.disabled=!unlocked;card.classList.toggle('locked',!unlocked);card.classList.toggle('active',!!state.introduced[sp.key]);card.classList.toggle('ready',ready||correct);card.querySelector('.pop').textContent=fmt(state[sp.key]);card.querySelector('.lock-copy').textContent=!unlocked?`🔒 ${sp.lock}`:(ready?'← 今ここをタップ':state.introduced[sp.key]?`${health(sp.key)} · タップで追加`:'迎えられる');card.querySelector('.foodline').style.transform=`scaleX(${clamp(state[sp.key]/sp.target,0,1)})`});els.chainHint.textContent=obj.target==='stable'?'10秒安定で完成':'必要な生き物が光る'}
  function maybeHunt(dt){if(!state.fx||Math.random()>dt*.6)return;const pairs=[['medaka','daphnia'],['turtle','snail'],['kingfisher','medaka']],valid=pairs.filter(([p,q])=>state[p]>.7&&state[q]>1);if(!valid.length)return;const [pred,prey]=valid[Math.floor(Math.random()*valid.length)];state.hunts.push({pred,prey,x:rand(.16,.84),y:rand(.5,.82),life:1})}
  function updateFx(dt){state.flashes.forEach(x=>x.life-=dt*1.3);state.flashes=state.flashes.filter(x=>x.life>0);state.hunts.forEach(x=>x.life-=dt*.85);state.hunts=state.hunts.filter(x=>x.life>0);state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.05*dt});state.particles=state.particles.filter(p=>p.life>0)}
  function seed(k,i){seeds[k]=seeds[k]||[];if(!seeds[k][i])seeds[k][i]={x:pseudo(i*7.2+k.length),y:pseudo(i*11.8+k.length*2),p:pseudo(i*5.7)*Math.PI*2};return seeds[k][i]} function count(k,max){const sp=SPECIES.find(x=>x.key===k);return Math.min(max,Math.ceil(state[k]/Math.max(1,sp.target/max)))}
  function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);drawPond(w,h);drawPlants(w,h);drawCreatures(w,h);drawHunts(w,h);drawCycle(w,h);drawParticles(w,h);drawWeather(w,h)}
  function drawPond(w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0d2930');g.addColorStop(.37,'#35615a');g.addColorStop(1,'#183636');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle='#294b36';ctx.beginPath();ctx.moveTo(0,h*.35);ctx.bezierCurveTo(w*.2,h*.28,w*.36,h*.42,w*.54,h*.33);ctx.bezierCurveTo(w*.72,h*.25,w*.86,h*.4,w,h*.31);ctx.lineTo(w,h*.48);ctx.lineTo(0,h*.5);ctx.fill();ctx.fillStyle='#174d50';ctx.beginPath();ctx.ellipse(w*.5,h*.7,w*.48,h*.27,-.03,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(190,235,225,.13)';ctx.lineWidth=1;for(let i=0;i<8;i++){const y=h*(.57+i*.04);ctx.beginPath();ctx.moveTo(w*.08,y);ctx.quadraticCurveTo(w*.5+Math.sin(state.time+i)*15,y-5,w*.92,y);ctx.stroke()}terrain.forEach((p,i)=>{ctx.globalAlpha=.08+p.a*.1;ctx.fillStyle=i%2?'#d0d6a3':'#7b6a4c';ctx.beginPath();ctx.arc(p.x*w,h*(.72+p.y*.2),1.5,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
  function drawPlants(w,h){const n=Math.min(120,Math.floor(state.algae*1.6));for(let i=0;i<n;i++){const x=pseudo(i*4.3)*w,y=h*(.58+pseudo(i*8.1)*.32),len=5+pseudo(i*3.8)*14;ctx.strokeStyle='rgba(94,181,128,.55)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y+len);ctx.quadraticCurveTo(x+Math.sin(state.time+i)*2,y+len*.4,x,y);ctx.stroke();if(i%8===0){ctx.fillStyle='rgba(131,205,157,.55)';ctx.beginPath();ctx.ellipse(x+3,y+3,4,2,-.4,0,Math.PI*2);ctx.fill()}}if(state.algae>52){ctx.globalAlpha=.65;for(let i=0;i<8;i++){const x=pseudo(i*8.5)*w,y=h*(.52+pseudo(i*3.2)*.22);ctx.fillStyle='#7bb88d';ctx.beginPath();ctx.ellipse(x,y,11,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d7a7cb';ctx.beginPath();ctx.arc(x,y-2,2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}}
  function drawCreatures(w,h){for(let i=0;i<count('daphnia',15);i++){const s=seed('daphnia',i),x=s.x*w,y=h*(.53+s.y*.28);ctx.strokeStyle='#d5d59a';ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x+2,y);ctx.lineTo(x+5,y-3);ctx.stroke()}ctx.globalAlpha=1;for(let i=0;i<count('snail',10);i++){const s=seed('snail',i),x=s.x*w,y=h*(.78+s.y*.13);ctx.fillStyle='#af8c64';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#5e4f3c';ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#9ab37e';ctx.fillRect(x+3,y+2,7,3)}for(let i=0;i<count('medaka',12);i++){const s=seed('medaka',i),x=(s.x*w+Math.sin(state.time*.7+s.p)*12+w)%w,y=h*(.56+s.y*.2);ctx.save();ctx.translate(x,y);ctx.fillStyle='#9fcdd4';ctx.beginPath();ctx.ellipse(0,0,8,3.4,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-7,0);ctx.lineTo(-13,-5);ctx.lineTo(-13,5);ctx.closePath();ctx.fill();ctx.fillStyle='#10282b';ctx.beginPath();ctx.arc(5,-1,1,0,Math.PI*2);ctx.fill();ctx.restore()}for(let i=0;i<count('turtle',6);i++){const s=seed('turtle',i),x=s.x*w,y=h*(.72+s.y*.15);ctx.fillStyle='#759d7b';ctx.beginPath();ctx.ellipse(x,y,10,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8dbb91';ctx.beginPath();ctx.arc(x+10,y,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#58775b';ctx.beginPath();ctx.moveTo(x-6,y-5);ctx.lineTo(x+6,y+5);ctx.moveTo(x+6,y-5);ctx.lineTo(x-6,y+5);ctx.stroke()}for(let i=0;i<count('kingfisher',4);i++){const s=seed('kingfisher',i),x=(s.x*w+state.time*(12+i))%(w+80)-40,y=h*(.28+s.y*.15)+Math.sin(state.time+s.p)*8;ctx.save();ctx.translate(x,y);ctx.fillStyle='#4ea7bc';ctx.beginPath();ctx.ellipse(0,0,8,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d28d52';ctx.beginPath();ctx.moveTo(7,-1);ctx.lineTo(18,1);ctx.lineTo(7,2);ctx.fill();ctx.strokeStyle='#77c2d1';ctx.beginPath();ctx.moveTo(-3,0);ctx.lineTo(-14,-8);ctx.moveTo(-3,1);ctx.lineTo(-14,8);ctx.stroke();ctx.restore()}for(let i=0;i<count('fungi',14);i++){const s=seed('fungi',i),x=s.x*w,y=h*(.83+s.y*.1);ctx.fillStyle='#d5c7ad';ctx.fillRect(x-1,y,2,6);ctx.fillStyle='#b993c3';ctx.beginPath();ctx.arc(x,y,4,Math.PI,0);ctx.fill()}}
  function drawHunts(w,h){const icons={daphnia:'◌',snail:'🐌',medaka:'🐟',turtle:'🐢',kingfisher:'🐦'};state.hunts.forEach(e=>{const t=1-e.life,x=e.x*w,y=e.y*h;ctx.save();ctx.globalAlpha=Math.min(1,e.life*2);ctx.font='19px system-ui';ctx.fillText(icons[e.prey],x+15*(1-t),y);ctx.font='23px system-ui';ctx.fillText(icons[e.pred],x-24+30*t,y-7*Math.sin(t*Math.PI));ctx.restore()})}
  function drawCycle(w,h){if(state.fungi<1)return;ctx.save();ctx.globalAlpha=clamp(state.fungi/20,0,.6);ctx.strokeStyle='#a9d6c2';ctx.setLineDash([3,6]);ctx.beginPath();ctx.arc(w*.5,h*.73,Math.min(w*.31,110),0,Math.PI*1.85);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#b7decf';ctx.font='10px system-ui';ctx.fillText('水と土へ戻る',w*.39,h*.51);ctx.restore()}
  function drawParticles(w,h){state.particles.forEach(p=>{ctx.globalAlpha=clamp(p.life,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*w,p.y*h,2,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1}
  function drawWeather(w,h){state.flashes.forEach(f=>{ctx.save();ctx.globalAlpha=f.life*.25;if(f.type==='sun'){const g=ctx.createRadialGradient(w*.78,h*.2,5,w*.78,h*.2,150);g.addColorStop(0,'#fff1a8');g.addColorStop(1,'rgba(255,240,170,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}else if(f.type==='rain'){ctx.strokeStyle='#c1e5ed';for(let i=0;i<35;i++){const x=pseudo(i*7.2+state.time)*w,y=(pseudo(i*3.6)+state.time*.8)%1*h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3,y+12);ctx.stroke()}}else{ctx.fillStyle='#a7804f';for(let i=0;i<18;i++)ctx.fillRect(pseudo(i*8.2)*w,h*(.4+((pseudo(i*4.4)+state.time*.05)%1)*.5),4,2)}ctx.restore()})}
  function frame(now){const dt=Math.min(.08,(now-last)/1000);last=now;simulate(dt);draw();uiClock+=dt;if(uiClock>.14){updateUI();uiClock=0}requestAnimationFrame(frame)}updateUI();requestAnimationFrame(frame);
})();
