let core=null,mode='AUTO',samples=[],last=performance.now(),lowSince=0,stableSince=0,button=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitCore(){for(let i=0;i<180;i++){if(window.__ASTRAL_CORE?.renderer)return window.__ASTRAL_CORE;await sleep(50)}throw new Error('Astral renderer unavailable');}
const dpr=()=>window.devicePixelRatio||1;

function pickAuto(){const mem=navigator.deviceMemory||8,cores=navigator.hardwareConcurrency||8,mobile=matchMedia('(max-width:720px),(pointer:coarse)').matches;if(navigator.connection?.saveData)return 'ECO';if(mobile&&(mem<=4||cores<=4))return 'BALANCED';return 'HIGH';}
function shadowLight(){return core.scene.children.find(x=>x.isDirectionalLight&&x.castShadow);}
function apply(name,announce=true){const r=core.renderer,light=shadowLight();mode=name;const actual=name==='AUTO'?pickAuto():name;if(actual==='HIGH'){r.setPixelRatio(Math.min(dpr(),1.8));r.shadowMap.enabled=true;if(light){light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.map?.dispose?.();light.shadow.map=null;}}
  else if(actual==='BALANCED'){r.setPixelRatio(Math.min(dpr(),1.28));r.shadowMap.enabled=true;if(light){light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.map?.dispose?.();light.shadow.map=null;}}
  else{r.setPixelRatio(Math.min(dpr(),1));r.shadowMap.enabled=false;if(light)light.castShadow=false;}
  r.setSize(innerWidth,innerHeight,false);if(button){button.textContent=name==='AUTO'?`Q·A`:(actual==='HIGH'?'Q·H':actual==='BALANCED'?'Q·B':'Q·E');button.title=`描画品質: ${name==='AUTO'?`AUTO → ${actual}`:actual}`;}localStorage.setItem('astral-quality',name);if(announce)core.toast(`描画品質: ${name==='AUTO'?`AUTO (${actual})`:actual}`,1300);samples.length=0;lowSince=stableSince=0;}

function inject(){const s=document.createElement('style');s.textContent=`#qualityToggle{position:fixed;z-index:15;right:64px;top:101px;width:42px;height:38px;border-radius:99px;border:1px solid rgba(255,255,255,.15);background:rgba(8,17,23,.58);backdrop-filter:blur(12px);color:#d9e6df;cursor:pointer;font:800 9px system-ui;letter-spacing:.08em;box-shadow:0 10px 32px rgba(0,0,0,.2)}@media(max-width:720px){#qualityToggle{right:54px;top:76px;width:39px;height:34px}}`;document.head.appendChild(s);button=document.createElement('button');button.id='qualityToggle';button.setAttribute('aria-label','描画品質切替');document.body.appendChild(button);button.onclick=()=>{const order=['AUTO','HIGH','BALANCED','ECO'],i=order.indexOf(mode);apply(order[(i+1)%order.length])};}

function measure(now){const dt=now-last;last=now;if(dt>0&&dt<250){samples.push(1000/dt);if(samples.length>120)samples.shift();}if(mode==='AUTO'&&samples.length>=90){const avg=samples.reduce((a,b)=>a+b,0)/samples.length;if(avg<37){if(!lowSince)lowSince=now;if(now-lowSince>5000){const auto=pickAuto();if(auto==='HIGH'){rampAuto('BALANCED')}else if(auto==='BALANCED'){rampAuto('ECO')}lowSince=now}}else lowSince=0;if(avg>56){if(!stableSince)stableSince=now}else stableSince=0;}requestAnimationFrame(measure);}
function rampAuto(target){const r=core.renderer,light=shadowLight();if(target==='BALANCED'){r.setPixelRatio(Math.min(dpr(),1.24));if(light){light.shadow.mapSize.set(1024,1024);light.shadow.map?.dispose?.();light.shadow.map=null;}button&&(button.textContent='Q·A↓');core.toast('AUTO: 描画負荷を調整',1000)}else{r.setPixelRatio(Math.min(dpr(),1));r.shadowMap.enabled=false;if(light)light.castShadow=false;button&&(button.textContent='Q·A↓');core.toast('AUTO: フレーム安定を優先',1000)}r.setSize(innerWidth,innerHeight,false);samples.length=0;}

(async()=>{try{core=await waitCore();inject();const saved=localStorage.getItem('astral-quality');apply(['AUTO','HIGH','BALANCED','ECO'].includes(saved)?saved:'AUTO',false);requestAnimationFrame(measure);addEventListener('resize',()=>{core.renderer.setSize(innerWidth,innerHeight,false)});}catch(err){console.warn('[Astral Dawn] adaptive quality layer skipped.',err)}})();
