(() => {
  'use strict';
  const KEY='hitobito-sports-data-v1';
  const $=id=>document.getElementById(id);
  const sample=[
    {id:'sample-1',date:'2026-08-01',sport:'野球',subject:'Player A',metric:'スコア',value:72,unit:'点',note:'サンプルデータ'},
    {id:'sample-2',date:'2026-08-08',sport:'野球',subject:'Player A',metric:'スコア',value:78,unit:'点',note:'サンプルデータ'},
    {id:'sample-3',date:'2026-08-15',sport:'野球',subject:'Player B',metric:'スコア',value:81,unit:'点',note:'サンプルデータ'},
    {id:'sample-4',date:'2026-08-22',sport:'野球',subject:'Player B',metric:'スコア',value:84,unit:'点',note:'サンプルデータ'},
    {id:'sample-5',date:'2026-08-10',sport:'ゴルフ',subject:'Player C',metric:'飛距離',value:247,unit:'yd',note:'サンプルデータ'},
    {id:'sample-6',date:'2026-08-24',sport:'ゴルフ',subject:'Player D',metric:'飛距離',value:261,unit:'yd',note:'サンプルデータ'}
  ];
  const el={
    tabs:[...document.querySelectorAll('.tab')],views:[...document.querySelectorAll('.view')],auth:$('authButton'),badge:$('syncBadge'),
    dm:$('dashboardMetric'),cm:$('compareMetric'),form:$('recordForm'),date:$('recordDate'),sport:$('recordSport'),subject:$('recordSubject'),metric:$('recordMetric'),value:$('recordValue'),unit:$('recordUnit'),note:$('recordNote'),
    sample:$('sampleButton'),csv:$('csvInput'),export:$('exportButton'),search:$('searchInput'),sf:$('sportFilter'),mf:$('metricFilter'),tbody:$('dataTableBody'),tableEmpty:$('tableEmpty'),chips:$('subjectChips'),cards:$('compareCards'),compareEmpty:$('compareEmpty'),
    canvas:$('trendChart'),chartEmpty:$('chartEmpty'),ranking:$('rankingList'),rankingEmpty:$('rankingEmpty'),recent:$('recentList'),recentEmpty:$('recentEmpty'),
    hc:$('heroRecordCount'),hm:$('heroMetricCount'),hs:$('heroSportCount'),sr:$('statRecords'),sa:$('statAverage'),sau:$('statAverageUnit'),sm:$('statMax'),smu:$('statMaxUnit'),ss:$('statSubjects'),range:$('trendRange'),toast:$('toast')
  };
  const valid=r=>r&&typeof r==='object'&&typeof r.id==='string'&&typeof r.date==='string'&&typeof r.sport==='string'&&typeof r.subject==='string'&&typeof r.metric==='string'&&Number.isFinite(Number(r.value));
  const load=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v.filter(valid):[]}catch{return[]}};
  const state={records:load(),user:null,auth:null,db:null,selected:[],timer:null,cloud:false};
  el.date.value=new Date().toISOString().slice(0,10);
  const id=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
  const norm=r=>({id:String(r.id||id()),date:String(r.date||'').slice(0,10),sport:String(r.sport||'その他').slice(0,40),subject:String(r.subject||'').slice(0,60),metric:String(r.metric||'').slice(0,40),value:Number(r.value),unit:String(r.unit||'').slice(0,16),note:String(r.note||'').slice(0,120)});
  const uniq=k=>[...new Set(state.records.map(r=>r[k]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ja'));
  const num=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(Number(n)):'—';
  function toast(t){el.toast.textContent=t;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2300)}
  function badge(type,text){el.badge.dataset.state=type;el.badge.textContent=text}
  function save(){localStorage.setItem(KEY,JSON.stringify(state.records));if(state.user&&state.db){clearTimeout(state.timer);state.timer=setTimeout(saveCloud,400)}}
  async function saveCloud(){if(!state.user||!state.db)return;try{await state.db.collection('levelupUsers').doc(state.user.uid).set({sportsData:{version:1,records:state.records,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}},{merge:true});badge('cloud','FIREBASE')}catch(e){console.error(e);badge('local','LOCAL');toast('Firebase保存に失敗。端末には保存済みです')}}
  async function initFirebase(){if(!window.firebase)return;try{const res=await fetch('/__/firebase/init.json',{cache:'no-store'});if(!res.ok)throw new Error(`init ${res.status}`);const cfg=await res.json();if(!firebase.apps.length)firebase.initializeApp(cfg);state.auth=firebase.auth();state.db=firebase.firestore();state.cloud=true;state.auth.onAuthStateChanged(onUser);await state.auth.getRedirectResult().catch(()=>null)}catch(e){console.warn('local mode',e);badge('local','LOCAL')}}
  async function onUser(user){state.user=user||null;if(!user){el.auth.textContent='Googleで同期';badge('local','LOCAL');return}el.auth.textContent=user.displayName?`${user.displayName} ✓`:'同期中 ✓';badge('cloud','SYNC');try{const snap=await state.db.collection('levelupUsers').doc(user.uid).get();const cloud=snap.exists?snap.data()?.sportsData?.records:null;if(Array.isArray(cloud)&&cloud.every(valid)){state.records=cloud.map(norm);localStorage.setItem(KEY,JSON.stringify(state.records));render();toast('Firebaseのデータを読み込みました')}else await saveCloud();badge('cloud','FIREBASE')}catch(e){console.error(e);badge('local','LOCAL');toast('Firebase読込に失敗。端末データを使用します')}}
  async function auth(){if(!state.cloud||!state.auth){toast('Firebase接続を確認できません');return}if(state.user){await state.auth.signOut();toast('ログアウトしました');return}const p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});try{await state.auth.signInWithPopup(p)}catch(e){if(['auth/popup-blocked','auth/popup-closed-by-user','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(e?.code))await state.auth.signInWithRedirect(p);else{console.error(e);toast('Googleログインに失敗しました')}}}
  function options(select,values,empty){const current=select.value;select.textContent='';if(empty){const o=document.createElement('option');o.value='';o.textContent=empty;select.append(o)}values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;select.append(o)});if([...select.options].some(o=>o.value===current))select.value=current}
  function render(){const metrics=uniq('metric'),sports=uniq('sport');options(el.dm,metrics,metrics.length?null:'指標なし');options(el.cm,metrics,metrics.length?null:'指標なし');options(el.sf,sports,'全競技');options(el.mf,metrics,'全指標');el.hc.textContent=state.records.length.toLocaleString('ja-JP');el.hm.textContent=metrics.length;el.hs.textContent=sports.length;dashboard();table();compare()}
  const mr=m=>state.records.filter(r=>r.metric===m&&Number.isFinite(Number(r.value)));
  function dashboard(){const metric=el.dm.value||uniq('metric')[0]||'';if(metric)el.dm.value=metric;const rows=mr(metric).sort((a,b)=>a.date.localeCompare(b.date)),vals=rows.map(r=>Number(r.value)),unit=rows.find(r=>r.unit)?.unit||'',avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,max=vals.length?Math.max(...vals):null;el.sr.textContent=state.records.length.toLocaleString('ja-JP');el.sa.textContent=avg==null?'—':num(avg);el.sau.textContent=unit;el.sm.textContent=max==null?'—':num(max);el.smu.textContent=unit;el.ss.textContent=uniq('subject').length;el.range.textContent=rows.length?`${rows[0].date} → ${rows[rows.length-1].date}`:'データなし';trend(rows);ranking(rows,unit);recent()}
  function trend(rows){const c=el.canvas,ctx=c.getContext('2d'),ratio=Math.max(1,devicePixelRatio||1),W=c.clientWidth||800,H=c.clientHeight||300;c.width=Math.floor(W*ratio);c.height=Math.floor(H*ratio);ctx.scale(ratio,ratio);ctx.clearRect(0,0,W,H);el.chartEmpty.style.display=rows.length?'none':'grid';if(!rows.length)return;const p={l:44,r:18,t:18,b:34},w=W-p.l-p.r,h=H-p.t-p.b,vals=rows.map(r=>Number(r.value));let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const span=max-min;min-=span*.12;max+=span*.12;ctx.font='10px -apple-system,sans-serif';for(let i=0;i<=4;i++){const y=p.t+h*i/4;ctx.strokeStyle='rgba(255,255,255,.08)';ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(p.l+w,y);ctx.stroke();ctx.fillStyle='#77839c';ctx.fillText(num(max-(max-min)*i/4),4,y+3)}const pts=rows.map((r,i)=>({x:p.l+(rows.length===1?w/2:w*i/(rows.length-1)),y:p.t+h-(Number(r.value)-min)/(max-min)*h,r}));ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.strokeStyle='#72a5ff';ctx.lineWidth=3;ctx.stroke();pts.forEach(q=>{ctx.beginPath();ctx.arc(q.x,q.y,4,0,Math.PI*2);ctx.fillStyle='#c7ff4a';ctx.fill()});const picks=pts.length<=4?pts:[pts[0],pts[Math.floor((pts.length-1)/2)],pts[pts.length-1]];ctx.fillStyle='#77839c';picks.forEach(q=>ctx.fillText(q.r.date.slice(5),Math.max(p.l-4,Math.min(q.x-13,W-42)),H-10))}
  function ranking(rows,unit){const by=new Map();rows.forEach(r=>{const old=by.get(r.subject);if(!old||Number(r.value)>Number(old.value))by.set(r.subject,r)});const list=[...by.values()].sort((a,b)=>Number(b.value)-Number(a.value)).slice(0,6);el.ranking.textContent='';el.rankingEmpty.style.display=list.length?'none':'block';list.forEach((r,i)=>{const li=document.createElement('li'),n=document.createElement('span'),name=document.createElement('span'),value=document.createElement('b');n.className='rank-no';n.textContent=String(i+1).padStart(2,'0');name.className='rank-name';name.textContent=r.subject;const meta=document.createElement('small');meta.className='rank-meta';meta.textContent=`${r.sport} · ${r.date}`;name.append(meta);value.className='rank-value';value.textContent=`${num(r.value)}${unit?` ${unit}`:''}`;li.append(n,name,value);el.ranking.append(li)})}
  function recent(){const rows=[...state.records].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);el.recent.textContent='';el.recentEmpty.style.display=rows.length?'none':'block';rows.forEach(r=>{const a=document.createElement('article');a.className='recent-item';const top=document.createElement('div');top.className='recent-top';top.innerHTML=`<span>${esc(r.sport)}</span><span>${esc(r.date)}</span>`;const s=document.createElement('strong');s.textContent=r.subject;const v=document.createElement('b');v.textContent=`${num(r.value)}${r.unit?` ${r.unit}`:''}`;const m=document.createElement('small');m.textContent=r.metric;a.append(top,s,v,m);el.recent.append(a)})}
  function esc(s){return String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
  function table(){const q=el.search.value.trim().toLowerCase(),sport=el.sf.value,metric=el.mf.value;const rows=[...state.records].filter(r=>(!sport||r.sport===sport)&&(!metric||r.metric===metric)&&(!q||[r.sport,r.subject,r.metric,r.unit,r.note,r.date].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));el.tbody.textContent='';el.tableEmpty.style.display=rows.length?'none':'block';rows.forEach(r=>{const tr=document.createElement('tr');[r.date,r.sport,r.subject,r.metric].forEach((t,i)=>{const td=document.createElement('td');if(i===2){const b=document.createElement('strong');b.textContent=t;td.append(b)}else td.textContent=t;tr.append(td)});const val=document.createElement('td');val.className='number';val.textContent=num(r.value);tr.append(val);[r.unit||'—',r.note||'—'].forEach(t=>{const td=document.createElement('td');td.textContent=t;tr.append(td)});const td=document.createElement('td'),b=document.createElement('button');b.className='delete-button';b.type='button';b.dataset.deleteId=r.id;b.setAttribute('aria-label','記録を削除');b.textContent='×';td.append(b);tr.append(td);el.tbody.append(tr)})}
  function compare(){const metric=el.cm.value||uniq('metric')[0]||'';if(metric)el.cm.value=metric;const rows=mr(metric),subjects=[...new Set(rows.map(r=>r.subject))].sort((a,b)=>a.localeCompare(b,'ja'));state.selected=state.selected.filter(s=>subjects.includes(s)).slice(0,4);if(state.selected.length<2)state.selected=subjects.slice(0,Math.min(4,subjects.length));el.chips.textContent='';subjects.forEach(s=>{const b=document.createElement('button');b.type='button';b.className=`subject-chip${state.selected.includes(s)?' selected':''}`;b.dataset.subject=s;b.textContent=s;el.chips.append(b)});const cards=state.selected.map(s=>{const own=rows.filter(r=>r.subject===s).sort((a,b)=>a.date.localeCompare(b.date));if(!own.length)return null;const vals=own.map(r=>Number(r.value));return{subject:s,latest:own.at(-1),average:vals.reduce((a,b)=>a+b,0)/vals.length,count:own.length}}).filter(Boolean);el.cards.textContent='';el.compareEmpty.style.display=cards.length>=2?'none':'block';cards.forEach(c=>{const a=document.createElement('article');a.className='compare-card';const l=document.createElement('span');l.textContent=metric||'指標';const h=document.createElement('h3');h.textContent=c.subject;const v=document.createElement('strong');v.textContent=num(c.latest.value);const u=document.createElement('small');u.textContent=c.latest.unit||'';const d=document.createElement('div');d.className='compare-sub';d.textContent=`最新 ${c.latest.date} · 平均 ${num(c.average)} · ${c.count}件`;a.append(l,h,v,u,d);el.cards.append(a)})}
  function add(e){e.preventDefault();const r=norm({date:el.date.value,sport:el.sport.value,subject:el.subject.value.trim(),metric:el.metric.value.trim(),value:el.value.value,unit:el.unit.value.trim(),note:el.note.value.trim()});if(!r.date||!r.subject||!r.metric||!Number.isFinite(r.value)){toast('必須項目を確認してください');return}state.records.push(r);save();el.value.value='';el.note.value='';render();toast('記録を追加しました')}
  function addSample(){if(state.records.some(r=>r.id.startsWith('sample-'))){toast('サンプルはすでに入っています');return}state.records.push(...sample.map(r=>({...r})));save();render();toast('サンプルデータを追加しました')}
  function del(id){state.records=state.records.filter(r=>r.id!==id);save();render();toast('削除しました')}
  function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
  async function importCsv(file){if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2){toast('CSVにデータがありません');return}const headers=rows[0].map(h=>h.trim().toLowerCase()),aliases={date:['date','日付'],sport:['sport','競技'],subject:['subject','player','team','選手 / チーム','選手','チーム'],metric:['metric','指標'],value:['value','値'],unit:['unit','単位'],note:['note','メモ']},ix={};Object.keys(aliases).forEach(k=>ix[k]=headers.findIndex(h=>aliases[k].includes(h)));if(['date','sport','subject','metric','value'].some(k=>ix[k]<0)){toast('CSV列は 日付,競技,選手 / チーム,指標,値 が必要です');return}const imported=rows.slice(1).map(c=>norm({date:c[ix.date],sport:c[ix.sport],subject:c[ix.subject],metric:c[ix.metric],value:c[ix.value],unit:ix.unit>=0?c[ix.unit]:'',note:ix.note>=0?c[ix.note]:''})).filter(r=>r.date&&r.subject&&r.metric&&Number.isFinite(r.value));state.records.push(...imported);save();render();el.csv.value='';toast(`${imported.length}件を読み込みました`)}
  function exportCsv(){const headers=['日付','競技','選手 / チーム','指標','値','単位','メモ'],quote=v=>`"${String(v??'').replaceAll('"','""')}"`,body=[headers,...state.records.map(r=>[r.date,r.sport,r.subject,r.metric,r.value,r.unit,r.note])].map(row=>row.map(quote).join(',')).join('\r\n'),blob=new Blob(['\ufeff'+body],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`sports-data-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  el.tabs.forEach(tab=>tab.addEventListener('click',()=>{el.tabs.forEach(x=>x.classList.toggle('active',x===tab));el.views.forEach(v=>v.classList.toggle('active',v.id===`${tab.dataset.view}View`));if(tab.dataset.view==='dashboard')setTimeout(dashboard)}));
  el.auth.addEventListener('click',auth);el.form.addEventListener('submit',add);el.sample.addEventListener('click',addSample);el.csv.addEventListener('change',()=>importCsv(el.csv.files?.[0]));el.export.addEventListener('click',exportCsv);[el.search,el.sf,el.mf].forEach(x=>x.addEventListener('input',table));el.dm.addEventListener('change',dashboard);el.cm.addEventListener('change',()=>{state.selected=[];compare()});el.tbody.addEventListener('click',e=>{const b=e.target.closest('[data-delete-id]');if(b)del(b.dataset.deleteId)});el.chips.addEventListener('click',e=>{const b=e.target.closest('[data-subject]');if(!b)return;const s=b.dataset.subject,i=state.selected.indexOf(s);if(i>=0)state.selected.splice(i,1);else if(state.selected.length<4)state.selected.push(s);else{toast('比較は最大4つです');return}compare()});window.addEventListener('resize',()=>{if($('dashboardView').classList.contains('active'))dashboard()});
  render();initFirebase();
})();
